var dicData = {
  // 4학년 1학기
  part: [
    {
      // 전체 단원
      list: [
        // 전체 단원 
      ],
    },
    {
      // 사회 1권 1단원
      
      list: [
        { word: "권력 분립", mean: "권력이 한곳에 집중되는 것을 방지하기 위해 권력을 분산시켜 상호 견제와 균형을 이루고자 하는 제도적 원리", example_f:"",example_b:"은 민주주의 국가에서 권력이 한곳에 집중되는 막아 권력의 남용을 막고 국민의 자유를 보장한다.",hint:"ㄱㄹ ㅂㄹ",hint_b:"은/는 민주주의 국가에서 권력이 한곳에 집중되는 막아 권력의 남용을 막고 국민의 자유를 보장한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "대통령제", mean: "국민이 선거를 통해 대통령과 의회 의원을 각각 선출하고, 국가 원수이자 행정부 수반인 대통령이 행정부를 구성하는 정부 형태", example_f:"우리나라의 정부 형태는 기본적으로",example_b:"를 취하고 있다.",hint:"ㄷㅌㄹㅈ",hint_b:"을/를 취하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "의원내각제", mean: "국민이 의회 의원을 선출하면 의회 다수당의 대표가 총리가 되어 행정부인 내각을 구성하는 정부 형태", example_f:"",example_b:"에서는 입법부와 행정부가 상호 유기적 협력 관계에 있다.",hint:"ㅇㅇㄴㄱㅈ",hint_b:"에서는 입법부와 행정부가 상호 유기적 협력 관계에 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "법률안 제출권", mean: "국회 의원과 정부가 법률안을 제출할 수 있는 권리", example_f:"우리나라에서는 국회 의원 뿐만 아니라 대통령도",example_b:"이 있다.",hint:"ㅂㄹㅇ ㅈㅊㄱ",hint_b:"이/가 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "탄핵 소추권", mean: "특정 공무원이 위법한 행위를 하였을 때 탄핵을 의결할 수 있는 권한", example_f:"국회가 행정부를 견제하는 수단 중 하나는",example_b:"이다.",hint:"ㅌㅎ ㅅㅊㄱ",hint_b:"이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "수반", mean: "행정부의 가장 높은 자리에 있는 사람", example_f:"우리나라에서 대통령은 행정부",example_b:"으로서 행정부를 구성한다.",hint:"ㅅㅂ",hint_b:"(으)로서 행정부를 구성한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "국가 원수", mean: "국가의 최고 지도자이자 국가를 대표하는 주체", example_f:"",example_b:"로서 대통령은 외국과 조약 체결, 헌법 기관 구성 등의 역할을 수행한다.",hint:"ㄱㄱ ㅇㅅ",hint_b:"(으)로서 대통령은 외국과 조약 체결, 헌법 기관 구성 등의 역할을 수행한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "계엄", mean: "국가 비상사태 시 행정권 및 사법권의 전부 또는 일부를 군의 권력이 담당하는 것", example_f:"대통령이",example_b:"을 선포하면 일정 지역의 행정권과 사법권을 군이 맡아 다스리게 된다.",hint:"ㄱㅇ",hint_b:"을/를 선포하면 일정 지역의 행정권과 사법권을 군이 맡아 다스리게 된다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "법률안 거부권", mean: "국회가 의결한 법률안을 대통령이 승인을 거부함으로써 법률로서의 성립을 저지하는 권한", example_f:"지난 달, 대통령이 의료법 법률에 대한",example_b:"을/를 행사하여 법률안이 다시 국회로 돌아가 다시 의결에 부치게 되었다.",hint:"ㅂㄹㅇ ㄱㅂㄱ",hint_b:"을/를 행사하여 법률안이 다시 국회로 돌아가 다시 의결에 부치게 되었다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "국무 회의", mean: "국가 주요 정책을 심의하는 최고 정책 심의 기관", example_f:"우리나라에서는",example_b:"에서 대통령이 회의의 의장이 된다.",hint:"ㄱㅁ ㅎㅇ",hint_b:"에서 대통령이 회의의 의장이 된다.", imageBool: true ,lineBreak:0,abbreviastion:false},
        { word: "행정", mean: "국회가 만든 법률을 구체화하여 집행하는 국가기관의 작용", example_f:"환경부, 교육부와 같은",example_b:"부서의 정책들은 일상생활에서 쉽게 접할 수 있다.",hint:"ㅎㅈ",hint_b:"부서의 정책들은 일상생활에서 쉽게 접할 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "상임 위원회", mean: "국회에서 각 전문 분야로 나누어 조직한 상설 위원회", example_f:"",example_b:"에서는 제안된 법안이 법률로서 적합한지 평가하고 본회의 안건으로의 상정을 결정한다.",hint:"ㅅㅇ ㅇㅇㅎ",hint_b:"에서는 제안된 법안이 법률로서 적합한지 평가하고 본회의 안건으로의 상정을 결정한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "상정", mean: "토의할 내용을 회의에 내어놓는 것", example_f:"회의 안건을",example_b:"하기 위해 대표들이 한자리에 모였다.",hint:"ㅅㅈ",hint_b:"하기 위해 대표들이 한자리에 모였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "공포", mean: "법률 등을 국민에게 알리는 일", example_f:"정부로 이송된 법안은 대통령이",example_b:"함으로써 확정된다.",hint:"ㄱㅍ",hint_b:"함으로써 확정된다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "재정", mean: "국가가 행정 활동이나 정책을 시행하기 위해 필요한 자금을 관리하고 사용하는 모든 경제활동", example_f:"국민의 대표가 모인 국회는",example_b:"에 관한 역할에서 정부가 국민의 세금을계획한 대로 사용하였는지 심사한다.",hint:"ㅈㅈ",hint_b:"에 관한 역할에서 정부가 국민의 세금을계획한 대로 사용하였는지 심사한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "인사 청문회", mean: "대통령이 임명하는 후보자의 자질과 능력을 국회에서 질문과 답변을 통해 검증하는 제도", example_f:"국회는",example_b:"를 실시하여 주요 국가기관 구성원들의 자질을 검증한다.",hint:"ㅇㅅ ㅊㅁㅎ",hint_b:"을/를 실시하여 주요 국가기관 구성원들의 자질을 검증한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "사법", mean: "법을 적용하여 판단하는 국가 작용", example_f:"",example_b:"기관으로서 법원의 역할은 법을 해석하고 적용하여 판결함으로써 사회 질서를 유지하는 것이다.",hint:"ㅅㅂ",hint_b:"기관으로서 법원의 역할은 법을 해석하고 적용하여 판결함으로써 사회 질서를 유지하는 것이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "대법원", mean: "사법부의 최고 법원으로 최종적인 재판을 담당하는 법원", example_f:"",example_b:"은 사법부 최고 법원으로, 최종 판결을 내린다.",hint:"ㄷㅂㅇ",hint_b:"은/는 사법부 최고 법원으로, 최종 판결을 내린다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "고등 법원", mean: "주로 2심 재판을 담당하며, 1심 법원의 판결을 다시 판단해 달라고 요청한 사건을 심판하는 법원", example_f:"",example_b:"은 주로 1심 사건에 대한 항소 사건을 재판한다.",hint:"ㄱㄷ ㅂㅇ",hint_b:"은/는 주로 1심 사건에 대한 항소 사건을 재판한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "지방 법원", mean: "주로 민사 사건이나 형사 사건의 1심 판결을 맡음", example_f:"",example_b:"은 제1심 법원으로서 심판권을 행사한다.",hint:"ㅈㅂ ㅂㅇ",hint_b:"은/는 제1심 법원으로서 심판권을 행사한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "가정 법원", mean: "이혼, 상속과 같은 가사 사건과 소년 보호 사건을 담당하는 법원", example_f:"A씨는 B씨와 이혼을 하기 위해",example_b:"에 서류를 제출하였다.",hint:"ㄱㅈ ㅂㅇ",hint_b:"에 서류를 제출하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "특허 법원", mean: "특허와 관련된 사건을 담당하는 법원", example_f:"A씨는 자신이 만든 기술의 특허권이 침해되었다는 사실을 알고",example_b:"에 소송을 걸었다.",hint:"ㅌㅎ ㅂㅇ",hint_b:"에 소송을 걸었다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "행정 법원", mean: "행정과 관련된 사건을 담당하는 법원", example_f:"",example_b:"은 행정 기관의 잘못으로 국민의 권리가 침해당했을 때 이를 해결한다.",hint:"ㅎㅈ ㅂㅇ",hint_b:"은/는 행정 기관의 잘못으로 국민의 권리가 침해당했을 때 이를 해결한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "위헌 법률 심판", mean: "재판 과정에서 법률이 헌법에 위반되는지 여부가 재판의 전제가 될 경우 법원이 위헌 여부를 심사해 달라고 제청하면 그 법률이 위헌인지 판단하는 심판", example_f:"재판 과정에서 공직 선거법이 헌법에 위반되는지 여부가 재판의 전제가 되는 상황에서 A기관은 헌법재판소에",example_b:"을 제청하였다.",hint:"ㅇㅎ ㅂㄹ ㅅㅍ",hint_b:"을/를 제청하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "헌법 소원 심판", mean: "공권력에 의해 기본권을 침해당한 국민이 구제를 청구했을 때 공권력 행사 또는 불행사의 위헌 여부를 판단하는 심판", example_f:"구치소 수감자는 구치소에 과밀 수용된 것에 대해 헌법재판소에",example_b:"을 제기하였다.",hint:"ㅎㅂ ㅅㅇ ㅅㅍ",hint_b:"을/를 제기하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "정당 해산 심판", mean: "정당의 목적이나 활동이 헌법의 민주적 질서에 어긋났을 때 정부의 청구에 따라 정당의 해산 여부를 판단하는 심판", example_f:"○○ 정당은 헌법의 가치를 훼손할 목적으로 조직되었다는 헌법재판소의",example_b:"판결에 따라 해산되었다.",hint:"ㅈㄷ ㅎㅅ ㅅㅍ",hint_b:"판결에 따라 해산되었다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "권한 쟁의 심판", mean: "국가기관 사이의 권한 다툼이 생겼을 때 권한에 관한 사항을 판단하는 심판", example_f:"헌법재판소는 두 국가기관이 서로 자신의 권한이라고 주장하는 사건에 대해",example_b:"으로 분쟁을 해결하였다.",hint:"ㄱㅎ ㅈㅇ ㅅㅍ",hint_b:"(으)로 분쟁을 해결하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "탄핵 심판", mean: "법률이 정한 공무원이 위법한 행위로 국회에서 탄핵 소추를 의결하면 해당 공무원의 파면 여부를 판단하는 심판", example_f:"국회는 직무 수행 중 헌법을 위반한 공무원에 대해",example_b:"을 소추하였다.",hint:"ㅌㅎ ㅅㅍ",hint_b:"을/를 소추하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 2단원
      
      list: [
        { word: "경제활동", mean: "경제 주체가 재화나 서비스와 같은 상품을 생산, 분배, 소비하는 것", example_f:"여러 경제 주체들은 생산, 분배, 소비 등 다양한",example_b:"을 한다.",hint:"ㄱㅈㅎㄷ",hint_b:"을/를 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "재화", mean: "인간에게 만족감을 주는 것 중 형태가 있는 상품", example_f:"",example_b:"의 종류로는 음식, 옷, 컴퓨터 등이 있다.",hint:"ㅈㅎ",hint_b:"의 종류로는 음식, 옷, 컴퓨터 등이 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "서비스", mean: "인간에게 만족감을 주는 것 중 형태가 없는 인간의 행동", example_f:"",example_b:"의 종류로는 의사의 진료, 교사의 수업, 물건의 배달과 같은 행위 등이 있다.",hint:"ㅅㅂㅅ",hint_b:"의 종류로는 의사의 진료, 교사의 수업, 물건의 배달과 같은 행위 등이 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "생산", mean: "가치를 만들거나 증대시키는 것", example_f:"상품을 만드는 것뿐만 아니라 상품을 운반, 저장하고 판매하는 것도",example_b:"에 포함된다.",hint:"ㅅㅅ",hint_b:"에 포함된다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "분배", mean: "생산에 참여한 대가를 주고받는 것", example_f:"생산 요소를 제공한 사람들이 임금, 지대, 이자 등의 대가를 받음으로써",example_b:"가 일어난다.",hint:"ㅂㅂ",hint_b:"이/가 일어난다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "소비", mean: "만족감을 얻기 위해 상품을 사용하는 것", example_f:"생산, 분배,",example_b:" 활동은 서로 긴밀히 연결되어 순환하고 있다.",hint:"ㅅㅂ",hint_b:" 활동은 서로 긴밀히 연결되어 순환하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "자원의 희소성", mean: "인간의 욕구는 무한한 데 비해 충족시켜 줄 자원은 한정되어 있는 성질", example_f:"",example_b:"때문에 우리는 다양한 선택의 문제에 직면하게 된다.",hint:"ㅈㅇㅇ ㅎㅅㅅ",hint_b:"때문에 우리는 다양한 선택의 문제에 직면하게 된다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "선택의 문제", mean: "희소성 때문에 무언가를 선택해야 하는 문제", example_f:"자원의 희소성 때문에 우리는 다양한",example_b:"에 직면하게 된다.",hint:"ㅅㅌㅇ ㅁㅈ",hint_b:"에 직면하게 된다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "비용", mean: "선택을 위해 지불해야 하는 대가", example_f:"우리가 사용할 수 있는 자원의 양은 한정되어 있기 때문에 최소의",example_b:"으로 최대의 편익을 얻을 수 있는 대안을 선택해야 한다.",hint:"ㅂㅇ",hint_b:"(으)로 최대의 편익을 얻을 수 있는 대안을 선택해야 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "편익", mean: "선택으로 얻게 되는 이득이나 만족감의 크기", example_f:"우리가 사용할 수 있는 자원의 양은 한정되어 있기 때문에 최소의 비용으로 최대의",example_b:"을 얻을 수 있는 대안을 선택해야 한다.",hint:"ㅍㅇ",hint_b:"을/를 얻을 수 있는 대안을 선택해야 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "합리적 선택", mean: "최소의 비용으로 최대의 편익을 얻을 수 있는 대안을 선택하는 것", example_f:"",example_b:"을 함으로써 희소한 자원을 효율적으로 활용할 수 있다.",hint:"ㅎㄹㅈ ㅅㅌ",hint_b:"을/를 함으로써 희소한 자원을 효율적으로 활용할 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "이윤", mean: "기업의 생산 활동에 대한 대가로, 판매 수입에서 생산비를 뺀 나머지 부분", example_f:"가계와 기업은 합리적 선택을 통해 한정된 예산 안에서 가장 큰 만족감이나",example_b:"을 얻을 수 있다.",hint:"ㅇㅇ",hint_b:"을/를 얻을 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "기회비용", mean: "선택에 따라 금전적으로 지출하는 비용뿐만 아니라 포기해야 하는 대안의 가치를 합한 것", example_f:"합리적 선택을 하기 위해서는 여러 대안의",example_b:"을 따져 봐야 한다.",hint:"ㄱㅎㅂㅇ",hint_b:"을/를 따져 봐야 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "생애 주기", mean: "시간의 흐름에 따라 개인의 삶이 어떻게 변화하는지를 단계로 나타낸 것", example_f:"인간의 경제생활은",example_b:"에 따라 다르게 나타난다.",hint:"ㅅㅇ ㅈㄱ",hint_b:"에 따라 다르게 나타난다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "금융", mean: "필요한 때에 금전을 적절하게 융통하는 것", example_f:"안정적인",example_b:"생활을 하려면 자신의 자산과 신용을 철저히 관리해야 한다.",hint:"ㄱㅇ",hint_b:"생활을 하려면 자신의 자산과 신용을 철저히 관리해야 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "금융 자산", mean: "예금이나 적금, 보험, 연금 그리고 각종 투자 상품과 같이 돈의 흐름과 관련된 것", example_f:"오늘날에는 자산 관리 수단으로서",example_b:"의 중요성이 더욱 강조되고 있다.",hint:"ㄱㅇ ㅈㅅ",hint_b:"의 중요성이 더욱 강조되고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "수익성", mean: "투자를 통해 얻을 수 있는 이익의 정도", example_f:"투자 상품은 저축 상품보다",example_b:"이 높다.",hint:"ㅅㅇㅅ",hint_b:"이/가 높다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "안전성", mean: "투자한 원금에 손실을 주지 않는 정도", example_f:"저축 상품은 투자 상품보다",example_b:"이 높다.",hint:"ㅇㅈㅅ",hint_b:"이/가 높다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "유동성", mean: "자산을 손실 없이 얼마나 쉽게 현금으로 전환할 수 있는지 그 정도", example_f:"자산은 그 종류에 따라 수익성, 안전성,",example_b:"의 크기가 서로 다르므로 이를 고려하여 자산 관리 계획을 세워야 한다.",hint:"ㅇㄷㅅ",hint_b:"의 크기가 서로 다르므로 이를 고려하여 자산 관리 계획을 세워야 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "자산", mean: "경제적인 가치가 있는 것", example_f:"금융 자산과 달리 구체적인 형태가 있는",example_b:"으로 귀금속, 건물, 토지 등과 같은 실물 자산이 있다.",hint:"ㅈㅅ",hint_b:"(으)로 귀금속, 건물, 토지 등과 같은 실물 자산이 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "예·적금", mean: "일정 기간 돈을 은행에 맡기고 원금과 정해진 이자를 받는 상품", example_f:"안정적으로 목돈을 마련하고자 한다면",example_b:"상품을 드는 것이 좋다.",hint:"ㅇ·ㅈㄱ",hint_b:"상품을 드는 것이 좋다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "보험", mean: "보험사에 돈을 미리 지불하고 질병에 걸리거나 사고가 났을 때 정해진 돈을 받는 상품", example_f:"혹시 모를 질병이나 사고에 대비하려면",example_b:"상품을 드는 것이 좋다.",hint:"ㅂㅎ",hint_b:"상품을 드는 것이 좋다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "연금", mean: "청년기, 중년기에 벌어들인 소득의 일정 금액을 미리 납입하고 은퇴 이후 배달 일정 금액을 받는 상품", example_f:"소득이 줄어드는 노후에 대비하려면",example_b:"상품을 드는 것이 좋다.",hint:"ㅇㄱ",hint_b:"상품을 드는 것이 좋다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "주식", mean: "기업의 소유 지분", example_f:"높은 수익률을 추구한다면",example_b:"이나 채권, 펀드 등의 다양한 투자 상품을 드는 것이 좋다.",hint:"ㅈㅅ",hint_b:"(이)나 채권, 펀드 등의 다양한 투자 상품을 드는 것이 좋다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "채권", mean: "기업 등에 돈을 빌려주고 받는 차용 증서", example_f:"높은 수익률을 추구한다면 주식이나",example_b:", 펀드 등의 다양한 투자 상품을 드는 것이 좋다.",hint:"ㅊㄱ",hint_b:", 펀드 등의 다양한 투자 상품을 드는 것이 좋다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "신용", mean: "미래의 어느 시점에 갚을 것을 약속하고 상품이나 돈을 빌리 수 있는 능력과 이에 대한 사회적 평가", example_f:"오늘날에는",example_b:"또한 하나의 자산과 같은 역할을 한다.",hint:"ㅅㅇ",hint_b:"또한 하나의 자산과 같은 역할을 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "기업", mean: "재화나 서비스의 생산을 담당하는 경제 주체", example_f:"",example_b:"은 상품을 연구·개발하고 생산하며, 고용을 창출하고 세금을 납부하는 역할을 한다.",hint:"ㄱㅇ",hint_b:"은/는 상품을 연구·개발하고 생산하며, 고용을 창출하고 세금을 납부하는 역할을 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "자유 경쟁", mean: "국가의 개입 없이 개별 기업들이 이윤을 추구하며 자유롭게 경쟁하는 것", example_f:"우리나라의 경제는",example_b:"을 바탕으로 여러 기업들이 자유롭게 경쟁하고 있다.",hint:"ㅈㅇ ㄱㅈ",hint_b:"을/를 바탕으로 여러 기업들이 자유롭게 경쟁하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "시장경제", mean: "시장에서 결정된 가격에 따라 경제활동이 이루어지는 경제 체제", example_f:"",example_b:"에서 기업의 주된 목표는 이윤을 얻는 것이다.",hint:"ㅅㅈㄱㅈ",hint_b:"에서 기업의 주된 목표는 이윤을 얻는 것이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "기업의 사회적 책임", mean: "기업이 사회 구성원으로서의 책임과 역할을 다하는 것", example_f:"",example_b:"에는 법령과 윤리를 준수하고 사회의 발전을 위해 공헌하는 것을 포함한다.",hint:"ㄱㅇㅇ ㅅㅎㅈ ㅊㅇ",hint_b:"에는 법령과 윤리를 준수하고 사회의 발전을 위해 공헌하는 것을 포함한다.", imageBool: false,lineBreak:3,abbreviastion:false },
        { word: "지속가능 경영(EGS)", mean: "기업을 경영할 때 경제적 가치 외에 사회·환경적 가치도 함께 고려하는 것", example_f:"",example_b:"의 ESG는 Environment, Social, Governance의 머리 글자를 딴 단어이다.",hint:"ㅈㅅㄱㄴ ㄱㅇ(EGS)",hint_b:"의 ESG는 Environment, Social, Governance의 머리 글자를 딴 단어이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "기업가 정신", mean: "이윤 추구를 위해 위험을 무릅쓰고 새로운 것에 과감히 도전하는 혁신적이고 창의적인 기업가의 자세", example_f:"오늘날",example_b:"은 이윤을 추구하면서 사회적 가치를 실현하는 것으로 확대되고 있다.",hint:"ㄱㅇㄱ ㅈㅅ",hint_b:"은/는 이윤을 추구하면서 사회적 가치를 실현하는 것으로 확대되고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 3단원
      list: [
        { word: "시장", mean: "상품의 형태나 거래 장소와 상관없이 구매자와 판매자가 자유롭게 재화와 서비스를 거래하는 공간", example_f:"인터넷 쇼핑몰은 구체적인 장소는 없지만 상품을 거래한다는 점에서",example_b:"으로 볼 수 있다.",hint:"ㅅㅈ",hint_b:"(으)로 볼 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "분업", mean: "사회가 필요로 하는 상품을 여러 주체가 분담하여 생산하는 것", example_f:"물건을 만들 때 생산 과정을 여러 사람이",example_b:"함으로써 상품의 질이 향상되고 생산량이 증가할 수 있었다.",hint:"ㅂㅇ",hint_b:"함으로써 상품의 질이 향상되고 생산량이 증가할 수 있었다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "특화", mean: "각 경제 주체가 자신에게 유리한 상품을 전문적으로 생산하는 것", example_f:"시장이 발달하면서 사람들은 자신이 더 잘 만들 수 있는 물건을",example_b:"하여 생산하였다.",hint:"ㅌㅎ",hint_b:"하여 생산하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "수요", mean: "상품을 구매하고자 하는 욕구", example_f:"시장은 경제생활에 필요한 재화나 서비스의",example_b:"와 공급을 연결하는 역할을 한다.",hint:"ㅅㅇ",hint_b:"과/와 공급을 연결하는 역할을 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "수요량", mean: "특정한 가격이 정해졌을 때 실제로 구매하고자 하는 상품의 수량", example_f:"가격이 하락하면",example_b:"은 증가한다.",hint:"ㅅㅇㄹ",hint_b:"은/는 증가한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "수요 법칙", mean: "가격과 수요량이 음(-)의 관계에 있다는 법칙", example_f:"",example_b:"에 따르면 가격과 수요량은 반대 방향으로 움직인다.",hint:"ㅅㅇ ㅂㅊ",hint_b:"에 따르면 가격과 수요량은 반대 방향으로 움직인다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "수요 곡선", mean: "가격에 따른 수요량의 변화를 그래프로 나타낸 것", example_f:"",example_b:"은 오른쪽 아래 방향으로 내려가는 모양이다.",hint:"ㅅㅇ ㄱㅅ",hint_b:"은/는 오른쪽 아래 방향으로 내려가는 모양이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "공급", mean: "상품을 판매하고자 하는 욕구", example_f:"시장은 경제생활에 필요한 재화나 서비스의 수요와",example_b:"을 연결하는 역할을 한다.",hint:"ㄱㄱ",hint_b:"을/를 연결하는 역할을 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "공급량", mean: "특정한 가격이 정해졌을 때 실제로 판매하고자 하는 상품의 수량", example_f:"가격이 하락하면",example_b:"이 감소한다.",hint:"ㄱㄱㄹ",hint_b:"이/가 감소한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "공급 법칙", mean: "가격과 공급량이 양(+)의 관계에 있다는 법칙", example_f:"",example_b:"에 따르면 가격과 공급량이 같은 방향으로 움직인다.",hint:"ㄱㄱ ㅂㅊ",hint_b:"에 따르면 가격과 공급량이 같은 방향으로 움직인다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "공급 곡선", mean: "가격에 따른 공급량의 변화를 그래프로 나타낸 것", example_f:"",example_b:"은 오른쪽 위 방향으로 올라가는 모양이다.",hint:"ㄱㄱ ㄱㅅ",hint_b:"은/는 오른쪽 위 방향으로 올라가는 모양이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "초과 수요", mean: "일정한 가격에서 수요량이 공급량보다 많은 상태", example_f:"",example_b:"의 경우 수요자는 상품을 구매하기 위해 점점 더 높은 가격을 제시하여 상품 가격이 상승하게 된다.",hint:"ㅊㄱ ㅅㅇ",hint_b:"의 경우 수요자는 상품을 구매하기 위해 점점 더 높은 가격을 제시하여 상품 가격이 상승하게 된다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "초과 공급", mean: "일정한 가격에서 공급량이 수요량보다 많은 상태", example_f:"",example_b:"의 경우 공급자들은 상품을 판매하기 위해 점점 더 낮은 가격을 제시하여 상품 가격이 하락하게 된다.",hint:"ㅊㄱ ㄱㄱ",hint_b:"의 경우 공급자들은 상품을 판매하기 위해 점점 더 낮은 가격을 제시하여 상품 가격이 하락하게 된다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "시장 가격", mean: "시장 수요량과 시장 공급량이 일치할 때 결정되는 상품의 가격", example_f:"",example_b:"은 수요 곡선과 공급 곡선이 만나는 지점에서 결정된다.",hint:"ㅅㅈ ㄱㄱ",hint_b:"은/는 수요 곡선과 공급 곡선이 만나는 지점에서 결정된다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "균형 가격", mean: "시장 수요량과 시장 공급량이 균형을 이룰 때의 가격", example_f:"",example_b:"에서는 수요자와 공급자 모두 원하는 양을 거래할 수 있다.",hint:"ㄱㅎ ㄱㄱ",hint_b:"에서는 수요자와 공급자 모두 원하는 양을 거래할 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "균형 거래량", mean: "시장 수요량과 시장 공급량이 균형을 이룰 때의 거래량", example_f:"시장이 균형을 이룰 때 균형 가격과",example_b:"이 결정된다.",hint:"ㄱㅎ ㄱㄹㄹ",hint_b:"이/가 결정된다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "대체재", mean: "비슷한 만족감을 주어 서로 대신 쓸 수 있는 관계에 있는 재화", example_f:"돼지고기의",example_b:"는 대체할 수 있는 닭고기이다.",hint:"ㄷㅊㅈ",hint_b:"은/는 대체할 수 있는 닭고기이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "보완재", mean: "함께 사용하면 더 큰 만족감을 주는 관계에 있는 재화", example_f:"돼지고기의",example_b:"는 함께 먹을 수 있는 상추이다.",hint:"ㅂㅇㅈ",hint_b:"은/는 함께 먹을 수 있는 상추이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "생산비", mean: "상품을 생산하기 위해 필요한 모든 비용", example_f:"",example_b:"가 감소하면 더 많은 상품을 생산할 수 있어 공급이 증가한다.",hint:"ㅅㅅㅂ",hint_b:"이/가 감소하면 더 많은 상품을 생산할 수 있어 공급이 증가한다.", imageBool: false,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 4단원
      list: [
        { word: "경제 성장", mean: "국내 총생산이 증가하여 나라의 생산 능력과 경제 규모가 커지는 것", example_f:"우리나라의",example_b:"이전과 이후의 모습은 크게 다르다.",hint:"ㄱㅈ ㅅㅈ",hint_b:"이전과 이후의 모습은 크게 다르다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "일일생활권", mean: "하루 동안 볼일을 끝내고 되돌아올 수 있는 거리 안에 있는 범위", example_f:"도로가 정비되고 교통 기술이 발달하면서 전국이",example_b:"이 되었다.",hint:"ㅇㅇㅅㅎㄱ",hint_b:"이/가 되었다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "국내 총생산(GDP)", mean: "해당 국가의 생산 능력을 나타내는 것으로, 일정 기간 동안 한 나라 안에서 새롭게 생산한 최종 생산물의 시장 가치를 모두 더한 값", example_f:"",example_b:"(GDP)는 한 나라의 경제 규모를 파악하는 데 활용되는 대표적인 경제 지표이다.",hint:"ㄱㄴ ㅊㅅㅅ(GDP)",hint_b:"(GDP)은/는 한 나라의 경제 규모를 파악하는 데 활용되는 대표적인 경제 지표이다.", imageBool: false,lineBreak:0,abbreviastion:true },
        { word: "국민 경제 지표", mean: "국민 소득, 물가, 실업률 등 한 나라가 처한 경제 상황을 파악할 수 있도록 수치화한 통계 자료", example_f:"한 나라의 경제 상황은 다양한",example_b:"를 통해 확인할 수 있다.",hint:"ㄱㅁ ㄱㅈ ㅈㅍ",hint_b:"을/를 통해 확인할 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "1인당 국내 총생산", mean: "국내 총생산을 그 나라의 인구수로 나눈 값", example_f:"국민의 평균적인 삶의 수준을 알고자 할 때는",example_b:"으로 파악할 수 있다.",hint:"1ㅇㄷ ㄱㄴ ㅊㅅㅅ",hint_b:"(으)로 파악할 수 있다.", imageBool: false,lineBreak:3,abbreviastion:false },
        { word: "물가", mean: "시장에서 거래되는 재화와 서비스의 평균적인 가격 수준", example_f:"가격은 각각의 개별 상품의 값을 의미하는 것이고,",example_b:"는 여러 상품의 종합적인 가격 수준을 나타낸다.",hint:"ㅁㄱ",hint_b:"은/는 여러 상품의 종합적인 가격 수준을 나타낸다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "물가 지수", mean: "어느 시점의 물가를 100이라고 할 때, 비교하려는 시점의 물가를 숫자로 표시한 것", example_f:"대표적인",example_b:"로 소비자가 일상생활을 꾸려 나가기 위해 구매하는 상품을 대상으로 조사한 소비자 물가 지수가 있다.",hint:"ㅁㄱ ㅈㅅ",hint_b:"로 소비자가 일상생활을 꾸려 나가기 위해 구매하는 상품을 대상으로 조사한 소비자 물가 지수가 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "인플레이션", mean: "물가가 지속적으로 오르는 현상", example_f:"",example_b:"이 발생하면 같은 돈으로 살 수 있는 상품의 양이 줄어들어 소비자의 부담이 늘어난다.",hint:"ㅇㅍㄹㅇㅅ",hint_b:"이/가 발생하면 같은 돈으로 살 수 있는 상품의 양이 줄어들어 소비자의 부담이 늘어난다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "실업", mean: "일할 의사와 능력이 있는데도 일자리를 갖지 못한 상태", example_f:"대부분의 국가에서는 실업률을 조사하여 고용 수준의 변화를 파악하고,",example_b:"을 해결하기 위해 노력한다.",hint:"ㅅㅇ",hint_b:"을/를 해결하기 위해 노력한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "자아 존중감", mean: "자기 자신이 가치 있고 소중한 존재라고 믿는 마음", example_f:"개인은 실업으로 인해",example_b:"이 낮아지거나 자아실현의 기회를 잃을 수 있다.",hint:"ㅈㅇ ㅈㅈㄱ",hint_b:"이/가 낮아지거나 자아실현의 기회를 잃을 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "국제 통화 기금(IMF) 외환 위기", mean: "1997년에 우리나라가 가진 외환이 부족해 국제 통화 기금(IMF)으로부터 자금 지원을 받은 사건", example_f:"1997년에 국제 통화 기금(IMF)",example_b:"가 일어나 우리나라 국민은 실업 등 여러 형태의 경제적 어려움을 겪었다.",hint:"ㄱㅈ ㅌㅎ ㄱㄱ(IMF) ㅇㅎ ㅇㄱ",hint_b:"이/가 일어나 우리나라 국민은 실업 등 여러 형태의 경제적 어려움을 겪었다.", imageBool: false,lineBreak:13,abbreviastion:true },
        { word: "국제 거래", mean: "국가 간에 재화와 서비스, 자본, 노동 등 여러 가지 상품을 사고파는 것", example_f:"",example_b:"가 이루어지면 나라마다 경쟁력 있는 제품을 전문적으로 생산하면서 세계의 자원을 더 효율적으로 쓸 수 있다.",hint:"ㄱㅈ ㄱㄹ",hint_b:"이/가 이루어지면 나라마다 경쟁력 있는 제품을 전문적으로 생산하면서 세계의 자원을 더 효율적으로 쓸 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "수입", mean: "다른 나라로부터 상품이나 기술을 국내로 사들이는 것", example_f:"외국산 스마트폰을",example_b:"하거나 국산 스마트폰을 수출한다.",hint:"ㅅㅇ",hint_b:"하거나 국산 스마트폰을 수출한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "수출", mean: "국내의 상품이나 기술을 외국으로 팔아 내보내는 것", example_f:"외국산 스마트폰을 수입하거나 국산 스마트폰을",example_b:"한다.",hint:"ㅅㅊ",hint_b:"한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "세계화", mean: "국가 간 교류가 늘어나고 세계 여러 나라가 다양한 분야에서 서로 영향을 주고받으며 상호 의존성이 강해지는 현상", example_f:"",example_b:"시대에 국가 간 관계가 긴밀해지면서 국제 거래가 더욱 활발해지고 있다.",hint:"ㅅㄱㅎ",hint_b:"시대에 국가 간 관계가 긴밀해지면서 국제 거래가 더욱 활발해지고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "지식 재산권", mean: "지적 활동으로 인하여 발생하는 모든 재산권", example_f:"최근 국제 거래는 문화 창작물 및 특허권과 같은",example_b:"의 거래가 늘어난 경향이 있다.",hint:"ㅈㅅ ㅈㅅㄱ",hint_b:"의 거래가 늘어난 경향이 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "환율", mean: "두 나라 사이의 화폐가 교환되는 비율", example_f:"",example_b:"은 외화의 수요와 공급에 따라 상승 또는 하락한다.",hint:"ㅎㅇ",hint_b:"은/는 외화의 수요와 공급에 따라 상승 또는 하락한다.", imageBool: false,lineBreak:0,abbreviastion:false },
      ],
    },
    {
     // 사회 1권 5단원
      list: [
        { word: "국제 사회", mean: "세계 여러 나라와 사람들이 서로 교류하고 의존하면서 함께 살아가는 사회", example_f:"",example_b:"에는 국가, 국제기구 등 다양한 행위 주체들이 활동하고 있다.",hint:"ㄱㅈ ㅅㅎ",hint_b:"에는 국가, 국제기구 등 다양한 행위 주체들이 활동하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "주권", mean: "국가의 의사를 최종적으로 결정할 수 있는 권력", example_f:"",example_b:"을 가진 국가는 국제 사회에서 가장 기본이 되는 행위 주체이다.",hint:"ㅈㄱ",hint_b:"을/를 가진 국가는 국제 사회에서 가장 기본이 되는 행위 주체이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "국가", mean: "일정한 영토와 거기에 사는 사람들로 구성되고, 주권에 의한 하나의 통치 조직을 가지고 있는 사회 집단", example_f:"",example_b:"는 국제법상 평등하고 독립적인 지위를 가지고 외교 활동을 한다.",hint:"ㄱㄱ",hint_b:"은/는 국제법상 평등하고 독립적인 지위를 가지고 외교 활동을 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "국제기구", mean: "어떤 국제적인 목적이나 활동을 위해서 두 나라 이상의 회원국으로 구성된 조직체", example_f:"국제적 목표나 활동을 위해 설립된",example_b:"는 국제 사회의 중요한 행위 주체이다.",hint:"ㄱㅈㄱㄱ",hint_b:"은/는 국제 사회의 중요한 행위 주체이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "정부 간 국제기구", mean: "각국 정부가 회원으로 참여하는 국제기구", example_f:"국제 연합(UN), 세계 보건 기구(WHO)는",example_b:"이다.",hint:"ㅈㅂ ㄱ ㄱㅈㄱㄱ",hint_b:"이다.", imageBool: false,lineBreak:4,abbreviastion:false },
        { word: "국제 연합(UN)", mean: "전쟁 방지와 평화 유지를 위해 설립된 국제기구", example_f:"",example_b:"(UN) 총회에서 결핵 종식을 위한 세계적인 대응 방안에 대해 논의하였다.",hint:"ㄱㅈ ㅇㅎ(UN)",hint_b:"(UN) 총회에서 결핵 종식을 위한 세계적인 대응 방안에 대해 논의하였다.", imageBool: false,lineBreak:0,abbreviastion:true },
        { word: "국제 비정부 기구", mean: "개인이나 민간단체가 모여 조직한 국제기구", example_f:"국경 없는 의사회, 그린피스 등은",example_b:"이다.",hint:"ㄱㅈ ㅂㅈㅂ ㄱㄱ",hint_b:"이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "국경 없는 의사회", mean: "전쟁, 재해, 전염병 등으로 고통받는 사람들에게 종교, 민족 등과 관계없이 의료 서비스를 제공하는 단체", example_f:"",example_b:"에서 모로코 지진 피해 지역에 의약품과 의료 기기 등을 지원하였다.",hint:"ㄱㄱ ㅇㄴ ㅇㅅㅎ",hint_b:"에서 모로코 지진 피해 지역에 의약품과 의료 기기 등을 지원하였다.", imageBool: false,lineBreak:5,abbreviastion:false },
        { word: "다국적 기업", mean: "여러 국가에 제조 공장이나 자회사 등을 세우고 세계적인 범위와 규모로 제품이나 서비스를 생산하고 판매하는 기업", example_f:"오늘날",example_b:"은 경제력을 바탕으로 국제 사회의 여러 분야에 영향력을 행사한다.",hint:"ㄷㄱㅈ ㄱㅇ",hint_b:"은/는 경제력을 바탕으로 국제 사회의 여러 분야에 영향력을 행사한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "협력", mean: "힘을 합하여 서로 도움.", example_f:"국제 사회의 여러 행위 주체는 국제 문제 해결 등 공동의 목표를 달성하기 위해",example_b:"한다.",hint:"ㅎㄹ",hint_b:"한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "경쟁", mean: "같은 목적에 대하여 이기거나 앞서려고 서로 겨룸.", example_f:"다국적 기업 A사와 S사가 생성형 인공 지능(AI) 기능을 담은 스마트폰을 두고",example_b:"하고 있다.",hint:"ㄱㅈ",hint_b:"하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "갈등", mean: "개인이나 집단 사이에 목표나 이해관계가 달라 서로 적대시하거나 충돌함.", example_f:"국제 사회의 행위 주체는 더 많은 이익을 얻기 위해 다른 행위 주체와",example_b:"을 겪기도 한다.",hint:"ㄱㄷ",hint_b:"을 겪기도 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "파리 협정", mean: "2015년 파리에서 채택된 기후 변화 협약으로, 온실가스 배출량을 단계적으로 감축하는 내용을 담고 있음.", example_f:"2017년 미국은 자국의 이익을 고려해",example_b:"의 탈퇴를 선언하였다.",hint:"ㅍㄹ ㅎㅈ",hint_b:"의 탈퇴를 선언하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "안전 보장 이사회", mean: "국제 평화와 안전 유지에 필요한 행동을 취할 책임과 권한을 가지는 국제 연합(UN)의 핵심 기관", example_f:"국제 연합(UN)",example_b:"의 주요 결정은 상임 이사국 5개국을 모두 포함한 9개국 이상의 찬성으로 이루어진다.",hint:"ㅇㅈ ㅂㅈ ㅇㅅㅎ",hint_b:"의 주요 결정은 상임 이사국 5개국을 모두 포함한 9개국 이상의 찬성으로 이루어진다.", imageBool: false,lineBreak:5,abbreviastion:false },
        { word: "국제법", mean: "국가 간 합의에 따라 국가 간의 권리와 의무를 규정한 국제 사회의 법률", example_f:"국제 사회의 여러 행위 주체는",example_b:"을 준수하고자 노력한다.",hint:"ㄱㅈㅂ",hint_b:"을/를 준수하고자 노력한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "전쟁", mean: "국가와 국가, 또는 이에 준하는 집단 사이에 무력을 사용하여 싸움.", example_f:"러시아와 우크라이나 간",example_b:"으로 두 나라 국민들의 일상이 무너졌다.",hint:"ㅈㅈ",hint_b:"(으)로 두 나라 국민들의 일상이 무너졌다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "테러", mean: "폭력을 써서 적이나 상대편을 위협하거나 공포에 빠뜨리게 하는 행위", example_f:"국가 간 경쟁과 갈등이 심해지면",example_b:"나 전쟁 같은 극단적인 상황이 발생하기도 한다.",hint:"ㅌㄹ",hint_b:"(이)나 전쟁 같은 극단적인 상황이 발생하기도 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "영유권", mean: "일정한 영토에 대한 해당 국가의 관할권", example_f:"중요한 위치에 있으며 석유가 매장된 포클랜드 제도의",example_b:"을 둘러싸고 영국과 아르헨티나가 갈등을 겪고 있다.",hint:"ㅇㅇㄱ",hint_b:"을/를 둘러싸고 영국과 아르헨티나가 갈등을 겪고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "이스라엘∙팔레스타인 분쟁", mean: "팔레스타인 지역을 두고 이스라엘을 건국한 유대인과, 이슬람교를 믿는 팔레스타인인이 충돌하여 생긴 갈등", example_f:"하나의 지역을 두고 이스라엘과 팔레스타인이",example_b:"을 겪고 있다.",hint:"ㅇㅅㄹㅇ∙ㅍㄹㅅㅌㅇ ㅂㅈ",hint_b:"을/를 겪고 있다.", imageBool: false,lineBreak:5,abbreviastion:false },
        { word: "포클랜드 분쟁", mean: "포클랜드 제도의 소유권을 둘러싼 영국과 아르헨티나의 갈등", example_f:"포클랜드 영유권을 둘러싸고 영국과 아르헨티나가",example_b:"을 겪고 있다.",hint:"ㅍㅋㄹㄷ ㅂㅈ",hint_b:"을/를 겪고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "자원", mean: "인간 생활이나 경제적 생산에 이용되는 원료, 노동력, 기술 등을 통틀어 이르는 말", example_f:"방대한",example_b:"이 매장된 북극해를 둘러싸고 북극해 연안 5개국과 유럽연합(EU) 등이 북극에 대한 영유권을 주장하고 있다.",hint:"ㅈㅇ",hint_b:"이/가 매장된 북극해를 둘러싸고 북극해 연안 5개국과 유럽연합(EU) 등이 북극에 대한 영유권을 주장하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "영토", mean: "한 국가의 주권이 미치는 땅", example_f:"우리나라의",example_b:"은/는 한반도와 부속 섬을 포함한다.",hint:"ㅇㅌ",hint_b:"는 한반도와 부속 섬을 포함한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "센카쿠 열도[댜오위다오] 분쟁", mean: "센카쿠 열도(댜오위다오)의 영유권 및 주변 해역의 관할권을 둘러싼 갈등", example_f:"해역에 대한 통제권을 확보하고, 매장된 자원을 차지하기 위해",example_b:"이 발생하였다.",hint:"ㅅㅋㅋ ㅇㄷ[ㄷㅇㅇㄷㅇ] ㅂㅈ",hint_b:"이/가 발생하였다.", imageBool: false,lineBreak:13,abbreviastion:false },
        { word: "다중적인 시민", mean: "국제 사회 구성원으로서 지역, 국가, 그리고 세계시민으로서의 다중적인 지위와 역할을 인식하는 시민", example_f:"국제 사회의",example_b:"으로서 역할과 책임을 균형 잡힌 시각에서 실천해야 한다.",hint:"ㄷㅈㅈㅇ ㅅㅁ",hint_b:"(으)로서 역할과 책임을 균형 잡힌 시각에서 실천해야 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "지역 이기주의", mean: "자기 지역의 이익만을 고집하는 현상", example_f:"",example_b:"를 넘어서는 것은 세계시민의 가장 중요하면서도 어려운 숙제이다.",hint:"ㅈㅇ ㅇㄱㅈㅇ",hint_b:"을/를 넘어서는 것은 세계시민의 가장 중요하면서도 어려운 숙제이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "분단국가", mean: "본래는 하나의 국가였으나 전쟁이나 외국의 지배하에서 강제된 경계선에 의하여 2개 이상으로 나위어 있는 국가", example_f:"우리나라는 세계 유일한",example_b:"로 군사적 긴장 상태에 있다.",hint:"ㅂㄷㄱㄱ",hint_b:"(으)로 군사적 긴장 상태에 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "선진국", mean: "다른 나라보다 정치, 경제, 문화 따위의 발달이 앞선 나라", example_f:"다른 나라와의 활발한 무역을 바탕으로 경제 성장을 이룬 우리나라는 국제 사회",example_b:"으로서 그 지위를 인정받고 있다.",hint:"ㅅㅈㄱ",hint_b:"(으)로서 그 지위를 인정받고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "비핵화", mean: "핵무기를 없게 하는 것", example_f:"우리나라는 한반도",example_b:"문제를 비롯한 각종 군사적 갈등을 겪고 있다.",hint:"ㅂㅎㅎ",hint_b:"문제를 비롯한 각종 군사적 갈등을 겪고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "안보", mean: "안전 보장'을 줄여 이르는 말", example_f:"우리나라의 군사적 갈등은 강대국 간",example_b:"경쟁으로 이어지기도 한다.",hint:"ㅇㅂ",hint_b:"경쟁으로 이어지기도 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "자유 무역 협정(FTA)", mean: "특정 국가 간의 상호 무역 증진을 위해 물자나 서비스의 이동을 자유롭게 하는 협정", example_f:"우리나라는 세계 여러 국가와",example_b:"(FTA)을 맺어 국제 교역량을 확대하고 있다.",hint:"ㅈㅇ ㅁㄱ ㅎㅂ(FTA)",hint_b:"(FTA)을/를 맺어 국제 교역량을 확대하고 있다.", imageBool: false,lineBreak:0,abbreviastion:true },
        { word: "세계 금융 위기", mean: "전 세계가 금융에서 비롯된 경제 위기를 맞는 것", example_f:"",example_b:"와 같은 국제 경제 문제의 영향으로 국내 경제가 불안을 경험하기도 한다.",hint:"ㅅㄱ ㄱㅇ ㅇㄱ",hint_b:"과/와 같은 국제 경제 문제의 영향으로 국내 경제가 불안을 경험하기도 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "난민", mean: "인종, 종교, 국적, 특정 사회 집단의 구성원 신분 또는 정치적 견해로 박해받을 가능성이 있어 자국의 보호를 받을 수 없거나 보호받기를 원하지 않는 자", example_f:"최근에는 세계 선진국으로서 책임이 강조되면서 그동안 우리에게 생소했던 국제",example_b:", 인권 문제 등이 우리 사회의 쟁점이 되고 있다.",hint:"ㄴㅁ",hint_b:", 인권 문제 등이 우리 사회의 쟁점이 되고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "관세", mean: "국가 간 거래에 내는 세금", example_f:"자유 무역 협정(FTA)이 체결되면",example_b:"가 낮아지거나 없어져 무역이 더욱 활발해질 수 있다.",hint:"ㄱㅅ",hint_b:"이/가 낮아지거나 없어져 무역이 더욱 활발해질 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "외교", mean: "한 국가가 국제 사회에서 자국의 이익을 평화적으로 실현하기 위해 수행하는 활동", example_f:"정부는",example_b:"활동으로 국가의 이익을 추구하는 동시에 선진국으로서 국제 사회에서의 역할과 책임을 다할 수 있어야 한다.",hint:"ㅇㄱ",hint_b:"활동으로 국가의 이익을 추구하는 동시에 선진국으로서 국제 사회에서의 역할과 책임을 다할 수 있어야 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "시민사회", mean: "신분적 구속에 지배되지 않으며, 자유롭고 평등한 개인의 이성적 결합으로 이루어진 사회", example_f:"국경을 뛰어넘는",example_b:"의 연대는 국가 간 이해관계가 복잡하게 얽힌 국제 문제를 해결하는 데 의미 있는 역할을 한다.",hint:"ㅅㅁㅅㅎ",hint_b:"의 연대는 국가 간 이해관계가 복잡하게 얽힌 국제 문제를 해결하는 데 의미 있는 역할을 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "반크(VANK)", mean: "인터넷을 통해 한국을 알리는 일을 하는 사이버 외교 사절단", example_f:"사이버 외교 사절단인",example_b:"(VANK)는 국제 문제를 해결하기 위한 다양한 민간 외교 활동을 수행한다.",hint:"ㅂㅋ(VANK)",hint_b:"(VANK)은/는 국제 문제를 해결하기 위한 다양한 민간 외교 활동을 수행한다.", imageBool: false,lineBreak:0,abbreviastion:true },
      ],
    },
    {
      // 사회 1권 6단원
      list: [
        { word: "사회 변동", mean: "시간이 흐름에 따라 한 사회의 정치, 경제, 문화 등이 다양한 요인에 의해 변화하는 현상", example_f:"오늘날에는 이전보다 훨씬 빠르게 과학 기술이 발전하면서",example_b:"의 속도도 더욱 빨라지고 있다.",hint:"ㅅㅎ ㅂㄷ",hint_b:"의 속도도 더욱 빨라지고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "세계화", mean: "국가 간 교류가 늘어나고 세계 여러 나라가 다양한 분야에서 서로 영향을 주고받으며 상호 의존성이 강해지는 현상", example_f:"",example_b:"시대에 국가 간 관계가 긴밀해지면서 국제 거래가 더욱 활발해지고 있다.",hint:"ㅅㄱㅎ",hint_b:"시대에 국가 간 관계가 긴밀해지면서 국제 거래가 더욱 활발해지고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "다문화적 변화", mean: "한 사회 안에 다양한 인종, 민족, 종교, 문화가 공존하는 사회로 변화하는 현상", example_f:"",example_b:"로 우리나라 안에서도 다양한 문화를 접할 수 있는 공간이 점차 많아지고 있다.",hint:"ㄷㅁㅎㅈ ㅂㅎ",hint_b:"(으)로 우리나라 안에서도 다양한 문화를 접할 수 있는 공간이 점차 많아지고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "저출산∙고령화", mean: "새롭게 태어나는 아이의 수는 줄어드는 반면 노인 인구가 차지하는 비중은 늘어나는 현상", example_f:"",example_b:"현상으로 어린이집은 줄어들고, 노인 요양원은 늘어나고 있다.",hint:"ㅈㅊㅅ∙ㄱㄹㅎ",hint_b:"현상으로 어린이집은 줄어들고, 노인 요양원은 늘어나고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "인공 지능(AI)", mean: "인간의 지능이 가지는 학습, 추리, 적응, 논증 등의 기능을 갖춘 컴퓨터 시스템", example_f:"지식 정보∙서비스 사회로 변화하면서",example_b:"(AI) 기술에 대한 관심이 높아졌다.",hint:"ㅇㄱ ㅈㄴ(AI)",hint_b:"(AI) 기술에 대한 관심이 높아졌다.", imageBool: false,lineBreak:0,abbreviastion:true },
        { word: "딥페이크(Deepfake)", mean: "인공 지능(AI) 기술을 활용해 사진이나 영상에 다른 이미지를 합성해 가공의 새 이미지나 영상을 만들어 내는 기술", example_f:"지식 정보∙서비스 사회로의 변화는",example_b:"(Deepfake) 범죄 등 새로운 사회문제를 일으키기도 한다.",hint:"ㄷㅍㅇㅋ(Deepfake)",hint_b:"(Deepfake) 범죄 등 새로운 사회문제를 일으키기도 한다.", imageBool: false,lineBreak:0,abbreviastion:true },
        { word: "크리스퍼 유전자 가위", mean: "생물체의 디엔에이(DNA)에서 특정 유전자를 잘라내어 편집할 수 있는 기술", example_f:"",example_b:"기술을 활용하면 작물의 품종을 개량할 수 있다.",hint:"ㅋㄹㅅㅍ ㅇㅈㅈ ㄱㅇ",hint_b:"기술을 활용하면 작물의 품종을 개량할 수 있다.", imageBool: false,lineBreak:4,abbreviastion:false },
        { word: "자율 주행 기술", mean: "목적지를 입력하면 운전자의 조작 없이 최적의 주행 경로로 자동차가 스스로 주행하는 기술", example_f:"",example_b:"을 통해 자동차가 스스로 위험을 주변 환경을 인식하고 위험을 판단하는 자율적이고 안전한 운행이 가능하다.",hint:"ㅈㅇ ㅈㅎ ㄱㅅ",hint_b:"을/를 통해 자동차가 스스로 위험을 주변 환경을 인식하고 위험을 판단하는 자율적이고 안전한 운행이 가능하다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "개인 맞춤형 콘텐츠 추천 기술", mean: "디지털 플랫폼이나 프로그램을 이용하는 사람들의 정보를 수집하고 분석하여 사용자에게 맞춤형 정보를 제공하는 기술", example_f:"",example_b:"을 통해 관심사에 맞는 정보를 편리하게 제공받을 수 있다.",hint:"ㄱㅇ ㅁㅊㅎ ㅋㅌㅊ ㅊㅊ ㄳ",hint_b:"을/를 통해 관심사에 맞는 정보를 편리하게 제공받을 수 있다.", imageBool: false,lineBreak:6,abbreviastion:false },
        { word: "사회문제", mean: "사회 구성원 다수에게 부정적인 영향을 미쳐 사람들이 이를 문제로 인식하고 개선해야 한다고 생각하는 문제", example_f:"",example_b:"는 시대와 장소에 따라 다르게 인식되기도 한다.",hint:"ㅅㅎㅁㅈ",hint_b:"은/는 시대와 장소에 따라 다르게 인식되기도 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "빈곤", mean: "가난해서 생활이 어려운 상태", example_f:"과거에는",example_b:"을 개인의 문제이자 책임이라고 생각했지만, 오늘날에는 우리 사회가 함께 해결해야 할 중요한 사회문제로 인식하고 있다.",hint:"ㅂㄱ",hint_b:"을/를 개인의 문제이자 책임이라고 생각했지만, 오늘날에는 우리 사회가 함께 해결해야 할 중요한 사회문제로 인식하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "사회 불평등", mean: "경제∙정치∙사회적 자원이 불평등하게 분배되면서 개인이나 집단이 평등한 사회적 지위를 갖지 못하고 서열화되어 있는 현상", example_f:"서울 시민 10명 중 7명이",example_b:"이 심각하다고 생각하고 있다.",hint:"ㅅㅎ ㅂㅍㄷ",hint_b:"이/가 심각하다고 생각하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "기후위기", mean: "지구의 평균 기온이 지속적으로 상승하여 지구 생태계와 인류의 생존에 위협을 가하는 현상", example_f:"",example_b:"에 따른 이상 기후 현상은 반복적으로 재난을 발생시켜 우리 생활에 큰 피해를 준다.",hint:"ㄱㅎㅇㄱ",hint_b:"에 따른 이상 기후 현상은 반복적으로 재난을 발생시켜 우리 생활에 큰 피해를 준다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "지구 온난화", mean: "지구의 평균 기온이 높아지는 현상", example_f:"온실 기체를 흡수할 수 있는 세계 곳곳의 숲이 파괴되면서",example_b:"가 심화되고 있다.",hint:"ㅈㄱ ㅇㄶ",hint_b:"이/가 심화되고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "생물 다양성", mean: "생태계 안에서 조화롭게 어울려 사는 생물들을 통틀어 이르는 말", example_f:"지구 온난화로",example_b:"파괴, 식량 위기, 기후 재난, 기후 난민 등의 문제가 발생하고 있다.",hint:"ㅅㅁ ㄷㅇㅅ",hint_b:"파괴, 식량 위기, 기후 재난, 기후 난민 등의 문제가 발생하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "팬데믹", mean: "감염병이 전 세계적으로 크게 유행하는 현상", example_f:"",example_b:"을 겪으며 전 세계적으로 교육 불평등, 소득 격차 심화 등 다양한 문제가 나타나고 있다.",hint:"ㅍㄷㅁ",hint_b:"을/를 겪으며 전 세계적으로 교육 불평등, 소득 격차 심화 등 다양한 문제가 나타나고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "이상 기후", mean: "기온이나 강수량 등이 정상적인 상태를 벗어난 상태", example_f:"",example_b:"현상 때문에 폭우가 잦아지면서 침수 피해가 커지고 있다.",hint:"ㅇㅅ ㄱㅎ",hint_b:"현상 때문에 폭우가 잦아지면서 침수 피해가 커지고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "모자이크 정책", mean: "캐나다에서 실시하는 다양한 민족의 정체성과 문화를 존중하는 정책", example_f:"캐나다의",example_b:"은 다문화적 변화에 대응한 성공적인 사례로 인정받고 있다.",hint:"ㅁㅈㅇㅋ ㅈㅊ",hint_b:"은/는 다문화적 변화에 대응한 성공적인 사례로 인정받고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "채식", mean: "고기류를 피하고 주로 채소, 과일, 해초 등의 식물성 음식을 중심으로 하는 식사", example_f:"원하는 학생들에게",example_b:"급식을 제공함으로써 기후위기의 요인 중 하나로 지적받는 과도한 육류 소비를 줄여 환경 보호에 기여할 수 있다.",hint:"ㅊㅅ",hint_b:"급식을 제공함으로써 기후위기의 요인 중 하나로 지적받는 과도한 육류 소비를 줄여 환경 보호에 기여할 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "연대 임금제", mean: "기업, 노동자, 국가가 합의를 통해 기업의 규모와 수익과 관계없이 같은 일을 하는 노동자에게 같은 임금을 보장하는 제도", example_f:"스웨덴은",example_b:"를 통해 비정규직 문제, 임금 격차 문제 등의 노동 문제를 해소하고 평등한 노동 시장을 만들었다.",hint:"ㅇㄷ ㅇㄱㅈ",hint_b:"을/를 통해 비정규직 문제, 임금 격차 문제 등의 노동 문제를 해소하고 평등한 노동 시장을 만들었다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "플로깅(Plogging)", mean: "걷기와 달리 운동을 하며 쓰레기를 줍는 환경 운동", example_f:"",example_b:"(Plogging)을 통해 편안한 신발에 쓰레기봉투만 있으면 누구나 쉽게 기후위기 문제에 대응할 수 있다.",hint:"ㅍㄹㄱ(Plogging)",hint_b:"(Plogging)을/를 통해 편안한 신발에 쓰레기봉투만 있으면 누구나 쉽게 기후위기 문제에 대응할 수 있다.", imageBool: false,lineBreak:0,abbreviastion:true },
      ],
    },
    {
      // 사회 1권 7단원
      list: [
        { word: "표준시", mean: "우리나라는 동경 135° 선의 시각을 표준시로 사용하여 경도 0°에 위치한 영국보다 9시간 빠르다.", example_f:"우리나라는 동경 135° 선의 시각을",example_b:"로 사용하여 경도 0°에 위치한 영국보다 9시간 빠르다.",hint:"ㅍㅈㅅ",hint_b:"(으)로 사용하여 경도 0°에 위치한 영국보다 9시간 빠르다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "반도국", mean: "우리나라는 반도국으로 대륙과 해양을 통해 세계와 교류하기에 유리하다.", example_f:"우리나라는",example_b:"으로 대륙과 해양을 통해 세계와 교류하기에 유리하다",hint:"ㅂㄷㄱ",hint_b:"(으)로 대륙과 해양을 통해 세계와 교류하기에 유리하다", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "북반구", mean: "우리나라는 북반구 중위도에 위치하여 사계절의 변화가 뚜렷하다.", example_f:"우리나라는",example_b:"중위도에 위치하여 사계절의 변화가 뚜렷하다.",hint:"ㅂㅂㄱ",hint_b:"중위도에 위치하여 사계절의 변화가 뚜렷하다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "해리", mean: "영해는 보통 기준선으로부터 12해리까지의 범위이다.", example_f:"영해는 보통 기준선으로부터 12",example_b:"까지의 범위이다.",hint:"ㅎㅇ",hint_b:"까지의 범위이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "통상 기선", mean: "해안선이 단조로운 동해안과 제주도, 울릉도, 독도에서는 통상 기선을 기준선으로 삼는다.", example_f:"해안선이 단조로운 동해안과 제주도, 울릉도, 독도에서는",example_b:"을 기준선으로 삼는다.",hint:"ㅌㅅ ㄱㅅ",hint_b:"을/를 기준선으로 삼는다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "대한 해협", mean: "일본과 거리가 가까운 대한 해협에서는 직선 기선으로부터 3해리까지만을 영해로 설정한다.", example_f:"일본과 거리가 가까운",example_b:"에서는 직선 기선으로부터 3해리까지만을 영해로 설정한다.",hint:"ㄷㅎ ㅎㅎ",hint_b:"에서는 직선 기선으로부터 3해리까지만을 영해로 설정한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "독도", mean: "독도는 우리 국토의 최동단에 위치한 섬이다.", example_f:"",example_b:"는 우리 국토의 최동단에 위치한 섬이다.",hint:"ㄷㄷ",hint_b:"은/는 우리 국토의 최동단에 위치한 섬이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "영공", mean: "영공의 범위는 보통 대기권까지로 한정한다.", example_f:"",example_b:"의 범위는 보통 대기권까지로 한정한다.",hint:"ㅇㄱ",hint_b:"의 범위는 보통 대기권까지로 한정한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "영역", mean: "우리나라의 영역에 다른 국가의 배나 비행기가 들어오려면 보통 우리나라 정부의 사전 허가를 받아야 한다.", example_f:"우리나라의",example_b:"에 다른 국가의 배나 비행기가 들어오려면 보통 우리나라 정부의 사전 허가를 받아야 한다.",hint:"ㅇㅇ",hint_b:"에 다른 국가의 배나 비행기가 들어오려면 보통 우리나라 정부의 사전 허가를 받아야 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "영토", mean: "우리나라의 영토는 한반도와 부속 섬을 포함한다.", example_f:"우리나라의",example_b:"는 한반도와 부속 섬을 포함한다.",hint:"ㅇㅌ",hint_b:"은/는 한반도와 부속 섬을 포함한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "영해", mean: "영해를 설정하는 기준선에는 통상 기선과 직선 기선이 있다.", example_f:"",example_b:"를 설정하는 기준선에는 통상 기선과 직선 기선이 있다.",hint:"ㅇㅎ",hint_b:"을/를 설정하는 기준선에는 통상 기선과 직선 기선이 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "배타적 경제 수역", mean: "배타적 경제 수역에서는 연안국이 어업 활동이나 자원 탐사를 할 수 있다.", example_f:"",example_b:"에서는 연안국이 어업 활동이나 자원 탐사를 할 수 있다.",hint:"ㅂㅌㅈ ㄱㅈ ㅅㅇ",hint_b:"에서는 연안국이 어업 활동이나 자원 탐사를 할 수 있다.", imageBool: false,lineBreak:3,abbreviastion:false },
        { word: "직선 기선", mean: "해안선이 복잡한 서·남해안에서는 가장 외곽에 있는 섬들을 연결한 직선 기선을 기준선으로 삼는다.", example_f:"해안선이 복잡한 서·남해안에서는 가장 외곽에 있는 섬들을 연결한",example_b:"을 기준선으로 삼는다.",hint:"ㅈㅅ ㄱㅅ",hint_b:"을/를 기준선으로 삼는다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "지정학", mean: "우리나라는 유라시아 대륙과 태평양을 연결할 수 있는 지정학적 이점을 지니고 있다.", example_f:"우리나라는 유라시아 대륙과 태평양을 연결할 수 있는",example_b:"적 이점을 지니고 있다.",hint:"ㅈㅈㅎ",hint_b:"적 이점을 지니고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "지경학", mean: "우리나라는 동아시아 주요 도시에 쉽게 접근할 수 있는 지경학적 이점을 지니고 있다.", example_f:"우리나라는 동아시아 주요 도시에 쉽게 접근할 수 있는",example_b:"적 이점을 지니고 있다.",hint:"ㅈㄱㅎ",hint_b:"적 이점을 지니고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "자유 무역 협정(FTA)", mean: "우리나라는 세계 여러 국가와 자유 무역 협정(FTA)을 맺어 국제 교역량을 확대하고 있다", example_f:"우리나라는 세계 여러 국가와",example_b:"(FTA)을 맺어 국제 교역량을 확대하고 있다.",hint:"ㅈㅇ ㅁㅇ ㅎㅈ(FTA)",hint_b:"(FTA)을/를 맺어 국제 교역량을 확대하고 있다.", imageBool: false,lineBreak:0,abbreviastion:true },
        { word: "행정구역", mean: "우리나라는 국토를 효율적으로 관리하기 위해 행정구역으로 지역을 구분하였다.", example_f:"우리나라는 국토를 효율적으로 관리하기 위해",example_b:"으로 지역을 구분하였다.",hint:"ㅎㅈㄱㅇ",hint_b:"(으)로 지역을 구분하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "장소감", mean: "동일한 장소라도 그에 대한 장소감은 사람마다 다르게 나타날 수 있다.", example_f:"동일한 장소라도 그에 대한",example_b:"은 사람마다 다르게 나타날 수 있다.",hint:"ㅈㅅㄱ",hint_b:"은/는 사람마다 다르게 나타날 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "장소애", mean: "작가 이효석은 소설 <메밀꽃 필 무렵>에서 자신의 고향 봉평에 대한 장소애를 표현하였다.", example_f:"작가 이효석은 소설 <메밀꽃 필 무렵>에서 자신의 고향 봉평에 대한",example_b:"를 표현하였다.",hint:"ㅈㅅㅇ",hint_b:"을/를 표현하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "장소성", mean: "서울의 전통적인 주거지인 서촌, 최신 유행이 모여 있는 홍대 거리는 장소성이 뚜렷한 곳이다.", example_f:"서울의 전통적인 주거지인 서촌, 최신 유행이 모여 있는 홍대 거리는",example_b:"이 뚜렷한 곳이다.",hint:"ㅈㅅㅅ",hint_b:"이/가 뚜렷한 곳이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "시각화", mean: "문제의 현황을 효과적으로 분석하여 전달하기 위해서는 적절한 시각화 방법을 선택하는 것이 중요하다.", example_f:"문제의 현황을 효과적으로 분석하여 전달하기 위해서는 적절한",example_b:"방법을 선택하는 것이 중요하다.",hint:"ㅅㄱㅎ",hint_b:"방법을 선택하는 것이 중요하다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "커뮤니티매핑", mean: "커뮤니티매핑은 지역의 재난 관리, 공공 서비스 등 다양한 영역에서 지리적 문제를 해결하는 방법으로 활용되고 있다.", example_f:"",example_b:"은 지역의 재난 관리, 공공 서비스 등 다양한 영역에서 지리적 문제를 해결하는 방법으로 활용되고 있다.",hint:"ㅋㅁㄴㅌㅁㅍ",hint_b:"은/는 지역의 재난 관리, 공공 서비스 등 다양한 영역에서 지리적 문제를 해결하는 방법으로 활용되고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "카드 뉴스", mean: "카드 뉴스는 일반 기사 뉴스보다 내용을 쉽게 파악할 수 있고, 다른 사람과 쉽게 공유할 수 있다는 장점이 있다.", example_f:"",example_b:"는 일반 기사 뉴스보다 내용을 쉽게 파악할 수 있고, 다른 사람과 쉽게 공유할 수 있다는 장점이 있다.",hint:"ㅋㄷ ㄴㅅ",hint_b:"은/는 일반 기사 뉴스보다 내용을 쉽게 파악할 수 있고, 다른 사람과 쉽게 공유할 수 있다는 장점이 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "마이크로 모빌리티", mean: "마이크로 모빌리티는 친환경 동력을 활용하는 소형 이동수단으로, 주로 근거리 주행에 사용된다.", example_f:"",example_b:"는 친환경 동력을 활용하는 소형 이동수단으로, 주로 근거리 주행에 사용된다.",hint:"ㅁㅇㅋㄹ ㅁㅂㄹㅌ",hint_b:"은/는 친환경 동력을 활용하는 소형 이동수단으로, 주로 근거리 주행에 사용된다.", imageBool: false,lineBreak:4,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 8단원
      list: [
        { word: "돌산", mean: "바위로 이루어진 산", example_f:"북한산이나 설악산과 같은",example_b:"은 봉우리와 산등성이에 바위가 그대로 드러나는 아름다운 경관으로 잘 알려져 있다.",hint:"ㅇㅅ",hint_b:"은/는 봉우리와 산등성이에 바위가 그대로 드러나는 아름다운 경관으로 잘 알려져 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "흙산", mean: "두꺼운 토양으로 덮인 산", example_f:"대표적인",example_b:"인 지리산은 토양층이 발달해 정상부까지 풀과 나무가 자란다.",hint:"ㅎㅅ",hint_b:"인 지리산은 토양층이 발달해 정상부까지 풀과 나무가 자란다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "조차", mean: "밀물과 썰물 때의 해수면 수위 차이", example_f:"",example_b:"가 큰 서해안과 남해안에는 갯벌이 형성된다.",hint:"ㅈㅊ",hint_b:"이/가 큰 서해안과 남해안에는 갯벌이 형성된다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "갯벌", mean: "밀물 때 바다에 잠기고, 썰물 때 드러나는 땅", example_f:"우리나라 최대 규모인 신안",example_b:"은 다양한 생물종이 살고 있어 생태계의 보고라고 불린다.",hint:"ㄱㅂ",hint_b:"은/는 다양한 생물종이 살고 있어 생태계의 보고라고 불린다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "모래사장", mean: "강가나 바닷가에 있는 넓고 큰 모래벌판", example_f:"육지 쪽으로 들어간 만에서는 파랑의 퇴적 작용이 활발하게 일어나",example_b:"이 형성된다.",hint:"ㅁㄹㅅㅈ",hint_b:"이/가 형성된다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "석호", mean: "모래톱으로 바다와 분리된 호수", example_f:"",example_b:"는 모래톱으로 바다와 분리된 호수로, 고성의 화진포, 강릉의 경포호가 대표적이다.",hint:"ㅅㅎ",hint_b:"은/는 모래톱으로 바다와 분리된 호수로, 고성의 화진포, 강릉의 경포호가 대표적이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "침식 작용", mean: "파랑, 바람 등의 자연 현상이 지표를 깎는 일", example_f:"곶에서는 파랑의",example_b:"이 활발하게 일어나 해안 절벽, 해안 동굴, 시 스택 등이 형성된다.",hint:"ㅊㅅ ㅈㅇ",hint_b:"이/가 활발하게 일어나 해안 절벽, 해안 동굴, 시 스택 등이 형성된다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "퇴적 작용", mean: "암석의 파편 등이 파랑, 바람 등의 작용으로 운반되어 일정한 곳에 쌓이는 일", example_f:"파랑의",example_b:"으로 만에 모래가 쌓여 모래사장이 형성되었다.",hint:"ㅌㅈ ㅈㅇ",hint_b:"(으)로 만에 모래가 쌓여 모래사장이 형성되었다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "해안선", mean: "바다와 육지가 맞닿은 선", example_f:"동해안은 수심이 깊고",example_b:"이 단조롭다.",hint:"ㅎㅇㅅ",hint_b:"이/가 단조롭다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "다도해", mean: "수많은 섬이 펼쳐진 바다", example_f:"남해안은 수많은 섬이 펼쳐진",example_b:"를 이룬다.",hint:"ㄷㄷㅎ",hint_b:"을/를 이룬다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "강수", mean: "비, 눈, 우박, 안개 등으로 땅에 내린 물", example_f:"우리나라는 계절에 따라 기온과",example_b:"량의 차이가 크다.",hint:"ㄱㅅ",hint_b:"량의 차이가 크다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "계절풍", mean: "계절마다 방향과 성질이 다른 바람", example_f:"우리나라는 대륙의 동쪽에 위치하여 계절마다 방향과 성질이 다른",example_b:"이 분다.",hint:"ㄱㅈㅍ",hint_b:"이/가 분다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "기온", mean: "대기의 온도", example_f:"봄에는 평균",example_b:"이 오르면서 개나리, 진달래, 벚꽃 등의 꽃이 핀다.",hint:"ㄱㅇ",hint_b:"이/가 오르면서 개나리, 진달래, 벚꽃 등의 꽃이 핀다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "기후", mean: "어떤 지역에서 오랜 기간에 걸쳐 나타나는 대기 현상의 평균적인 상태", example_f:"우리나라는 온대 및 냉대",example_b:"가 나타난다.",hint:"ㄱㅎ",hint_b:"이/가 나타난다", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "중위도", mean: "저위도와 고위도 사이의 위도 30°~60° 부근", example_f:"우리나라는",example_b:"에 위치하여 사계절이 나타난다.",hint:"ㅈㅇㄷ",hint_b:"에 위치하여 사계절이 나타난다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "기단", mean: "넓은 지역에 걸쳐 있으며 지표의 성질을 닮아 일정한 온도나 습도 특징을 지니는 공기 덩어리", example_f:"시베리아",example_b:"의 영향을 많이 받는 겨울은 춥고 건조하며, 눈이 내리기도 한다.",hint:"ㄱㄷ",hint_b:"의 영향을 많이 받는 겨울은 춥고 건조하며, 눈이 내리기도 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "열대야", mean: "밤 최저 기온이 25℃를 넘는 무더운 날", example_f:"한여름에는 불볕더위와",example_b:"가 나타난다.",hint:"ㅇㄷㅇ",hint_b:"이/가 나타난다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "소나기", mean: "더운 공기가 상승하여 구름을 형성하고, 갑자기 세차게 쏟아지다가 곧 그치는 비", example_f:"여름에 갑자기 내리는",example_b:"는 더위를 식혀 주기도 한다.",hint:"ㅅㄴㄱ",hint_b:"은/는 더위를 식혀 주기도 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "고랭지 농업", mean: "해발 고도가 높아 여름철 서늘한 기후가 나타나는 지역에서 배추, 무 등을 재배하는 것", example_f:"대관령 일대에서는 한여름에도 서늘한 기후를 이용하여",example_b:"이 이루어진다.",hint:"ㄱㄹㅈ ㄴㅇ",hint_b:"이/가 이루어진다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "장마", mean: "여름철에 여러 날을 계속해서 내리는 비", example_f:"",example_b:"의 영향을 받는 여름철에 많은 비가 내린다.",hint:"ㅈㅁ",hint_b:"의 영향을 받는 여름철에 많은 비가 내린다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "온실 기체", mean: "지구의 기온을 올리는 데 영향을 주는 이산화 탄소, 메탄 등의 기체", example_f:"석탄, 석유 등 화석 연료의 소비가 늘어나면서",example_b:"의 배출량이 증가하고 있다.",hint:"ㅇㄱ ㅅㅊ",hint_b:"의 배출량이 증가하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "열섬 현상", mean: "녹지 면적 감소와 냉·난방열 증가로 도시 지역의 기온이 도시 주변 지역보다 높게 나타나는 현상", example_f:"우리나라는 기후변화의 영향으로 대도시의 기온이 주변 지역보다 높은",example_b:"도 확대되었다.",hint:"ㅇㅅ ㅎㅅ",hint_b:"도 확대되었다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "지구 온난화", mean: "지구의 평균 기온이 높아지는 현상", example_f:"온실 기체를 흡수할 수 있는 세계 곳곳의 숲이 파괴되면서",example_b:"가 심화되고 있다.",hint:"ㅈㄱ ㅇㄴㅎ",hint_b:"이/가 심화되고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "재생 에너지", mean: "태양열, 수력, 풍력, 조력, 지열 고갈되지 않고 지속해서 사용할 수 있는 에너지", example_f:"온실 기체의 배출량을 줄이기 위해",example_b:"의 사용 비중을 늘리고 있다.",hint:"ㅈㅅ ㅇㄴㅈ",hint_b:"의 사용 비중을 늘리고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "이상 기후", mean: "기온이나 강수량 등이 정상적인 상태를 벗어난 상태", example_f:"",example_b:"현상 때문에 폭우가 잦아지면서 침수 피해가 커지고 있다.",hint:"ㅇㅅ ㄱㅎ",hint_b:"현상 때문에 폭우가 잦아지면서 침수 피해가 커지고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "자연재해", mean: "기상 현상이나 지각 변동이 우리 생활에 큰 피해를 주는 현상", example_f:"우리나라는 홍수, 가뭄, 태풍 등의",example_b:"가 자주 발생한다.",hint:"ㅈㅇㅈㅎ",hint_b:"이/가 자주 발생한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "폭설", mean: "짧은 시간에 많은 눈이 내리는 것", example_f:"",example_b:"은 교통 혼잡을 일으키고 산간 마을을 고립시키기도 한다.",hint:"ㅍㅅ",hint_b:"은/는 교통 혼잡을 일으키고 산간 마을을 고립시키기도 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "홍수", mean: "비가 많이 내려 하천에 갑자기 크게 불은 물", example_f:"",example_b:"발생 시 저지대를 중심으로 침수 피해가 발생하기도 한다.",hint:"ㅎㅅ",hint_b:"발생 시 저지대를 중심으로 침수 피해가 발생하기도 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "가뭄", mean: "오랫동안 비가 내리지 않아 메마른 날씨", example_f:"",example_b:"이 발생하면 농작물이 말라 죽고, 각종 용수가 부족해 생활에 어려움을 겪는다.",hint:"ㄱㅁ",hint_b:"이/가 발생하면 농작물이 말라 죽고, 각종 용수가 부족해 생활에 어려움을 겪는다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "산사태", mean: "폭우나 지진 발생 시 토사가 빠른 속도로 흘러내리는 현상", example_f:"",example_b:"는 폭우나 지진 발생 시 토사가 빠른 속도로 흘러내리는 현상으로 가옥이나 도로가 매몰되는 피해를 유발한다.",hint:"ㅅㅅㅌ",hint_b:"은/는 폭우나 지진 발생 시 토사가 빠른 속도로 흘러내리는 현상으로 가옥이나 도로가 매몰되는 피해를 유발한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "지진", mean: "지구 내부의 힘으로 지각이 갈라지거나 흔들리는 현상", example_f:"",example_b:"은 지구 내부의 힘으로 지각이 갈라지거나 흔들리는 현상으로, 건물 붕괴 피해를 주기도 한다.",hint:"ㅈㅈ",hint_b:"은/는 지구 내부의 힘으로 지각이 갈라지거나 흔들리는 현상으로, 건물 붕괴 피해를 주기도 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "태풍", mean: "적도 부근 바다에서 발생해 중위도 쪽으로 이동하는 저기압", example_f:"",example_b:"은 강풍과 호우를 동반하여 시설물 파괴나 침수 피해를 준다",hint:"ㅌㅍ",hint_b:"은/는 강풍과 호우를 동반하여 시설물 파괴나 침수 피해를 준다", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "활성 단층", mean: "과거 활동을 한 적이 있고, 가까운 미래에 다시 활동할 가능성이 있는 단층", example_f:"지진은",example_b:"이 위치한 경북 남동부 지역에서 자주 발생하고 있다.",hint:"ㅎㅅ ㄷㅊ",hint_b:"이/가 위치한 경북 남동부 지역에서 자주 발생하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 9단원
      list: [
        { word: "수도권", mean: "서울특별시, 인천광역시, 경기도로 구성됨.", example_f:"",example_b:"에는 우리나라 인구의 절반가량이 모여 있다.",hint:"ㅅㄷㄱ",hint_b:"에는 우리나라 인구의 절반가량이 모여 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "석회 동굴", mean: "지하수가 석회암과 반응하여 생긴 동굴", example_f:"강원 동해, 삼척, 정선 일대와 충북 단양의 석회암 지대에서는",example_b:"을 볼 수 있다.",hint:"ㅅㅎ ㄷㄱ",hint_b:"을/를 볼 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "대도시권", mean: "대도시를 포함하여 그와 밀접한 관계가 있는 주변 지역", example_f:"수도권의 도시들은 다양한 교통수단으로 연결되어 하나의",example_b:"을 형성하고 있다.",hint:"ㄷㄷㅅㄱ",hint_b:"을 형성하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "도심", mean: "상업과 업무 기능이 밀집해 있는 도시의 중심부", example_f:"서울에는 전통 ㄷㅅ인 중구, 종로구 외에도 여의도, 강남이",example_b:"으로 성장하였다.",hint:"ㄷㅅ",hint_b:"(으)로 성장하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "신도시", mean: "대도시의 근교에 계획적으로 개발한 새 주거 지역", example_f:"서울의 주택 부족 문제를 해결하고자 경기와 인천에 여러",example_b:"가 조성되었다.",hint:"ㅅㄷㅅ",hint_b:"가 조성되었다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "탈공업화", mean: "전체 산업에서 제조업의 비중은 감소하고 서비스업의 비중이 높아지는 현상", example_f:"",example_b:"가 진행되면서 서울에는 부가 가치가 높은 서비스업이 발달하였다.",hint:"ㅌㄱㅇㅎ",hint_b:"이/가 진행되면서 서울에는 부가 가치가 높은 서비스업이 발달하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "서비스업", mean: "물자의 생산 대신에 서비스를 제공하는 산업", example_f:"강원 지역은 관광 산업이 발달하며",example_b:"종사자 비중이 늘어나고 있다.",hint:"ㅅㅂㅅㅇ",hint_b:"종사자 비중이 늘어나고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "고속 국도", mean: "주요 도시를 잇는 자동차 전용의 고속 교통용 국도", example_f:"충청 지역의 산업 단지는 철도,",example_b:"등 다양한 교통망을 따라 분포한다.",hint:"ㄱㅅ ㄱㄷ",hint_b:"등 다양한 교통망을 따라 분포한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "고속 철도", mean: "시속 약 200km 이상으로 운행되는 철도", example_f:"경춘선 전철과",example_b:"가 개통되자 수도권과 강원 지역을 오가는 출퇴근 인구가 늘어났다.",hint:"ㄱㅅ ㅊㄷ",hint_b:"이/가 개통되자 수도권과 강원 지역을 오가는 출퇴근 인구가 늘어났다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "교통수단", mean: "사람이 이동하거나 짐을 옮기는 데 쓰는 수단", example_f:"충청 지역은 수도권과 남부 지역을 연결하는 위치에 있어 일찍부터 다양한",example_b:"이 발달하였다.",hint:"ㄱㅌㅅㄷ",hint_b:"이/가 발달하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "첨단 산업", mean: "첨단 기술을 중심으로 이루어지는 산업", example_f:"오창 과학 산업 단지에는 반도체, 의약품, 화장품 등을 생산하는 다양한 기업이 들어오면서",example_b:"이 발달하였다.",hint:"ㅊㄷ ㅅㅇ",hint_b:"이/가 발달하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "비수도권", mean: "수도권을 제외한 나머지 지역", example_f:"",example_b:"에는 수도권보다 기업이 적어 고용 기회가 부족하다.",hint:"ㅂㅅㄷㄱ",hint_b:"에는 수도권보다 기업이 적어 고용 기회가 부족하다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "특례시", mean: "지방 자치법에 따라 인구 100만 명 이상의 시인 수원, 고양, 용인, 창원을 특례시로 지정함.", example_f:"특별자치도,",example_b:"등을 지정하여 지방 자치 단체의 권한과 역할을 강조하고 있다.",hint:"ㅌㄹㅅ",hint_b:"등을 지정하여 지방 자치 단체의 권한과 역할을 강조하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "성장 거점 개발", mean: "성장 잠재력이 큰 특정 지역을 집중적으로 개발해서 성장 이익이 다른 지역으로 퍼지도록 하는 개발 방법", example_f:"우리나라는 경제 성장 과정에서 수도권을 중심으로",example_b:"을 추진하였다.",hint:"ㅅㅈ ㄱㅈ ㄱㅂ",hint_b:"을/를 추진하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "혁신 도시", mean: "수도권 집중도를 낮추기 위해 공공 기관을 지방으로 이전하여 조성한 도시", example_f:"",example_b:"를 조성하여 공공 기관을 비수도권으로 이전하고 있다.",hint:"ㅎㅅ ㄷㅅ",hint_b:"을/를 조성하여 공공 기관을 비수도권으로 이전하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 10단원
      list: [
        { word: "만입부", mean: "바다와 육지가 만나는 해안에서 육지 쪽으로 들어가 있는 부분", example_f:"남부 지역의 해안은 조차가 커서",example_b:"곳곳에 갯벌이 형성되었다.",hint:"ㅁㅇㅂ",hint_b:"곳곳에 갯벌이 형성되었다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "김해평야", mean: "낙동강 하구에 발달한 우리나라 최대의 충적 평야", example_f:"",example_b:"는 낙동강 하구 삼각주에 발달한 우리나라 최대의 충적 평야이다.",hint:"ㄱㅎㅍㅇ",hint_b:"은/는 낙동강 하구 삼각주에 발달한 우리나라 최대의 충적 평야이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "염전", mean: "소금을 만들기 위하여 바닷물을 끌어 들여 논처럼 만든 곳", example_f:"갯벌이 발달하고 일조량이 풍부한 곳에서는",example_b:"을 만들어 소금을 생산한다.",hint:"ㅇㅈ",hint_b:"을 만들어 소금을 생산한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "호남평야", mean: "우리나라에서 가장 큰 곡창 지대로, 전라도 서부에 펼쳐진 평야", example_f:"",example_b:"는 우리나라에서 가장 큰 곡창 지대로 금강, 만경강, 영산강 등이 지난다.",hint:"ㅎㄴㅍㅇ",hint_b:"은/는 우리나라에서 가장 큰 곡창 지대로 금강, 만경강, 영산강 등이 지난다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "화산 지형", mean: "화산 작용으로 생기는 지형", example_f:"제주 지역에서는 독특한 방언, 가옥 구조, 음식 문화가 나타나며 다양한",example_b:"을 볼 수 있다.",hint:"ㅎㅅ ㅈㅎ",hint_b:"을/를 볼 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "전통문화", mean: "그 나라에서 발생하여 전해 내려오는 그 나라 고유의 문화", example_f:"",example_b:"를 잘 간직하고 있는 경주의 양동 마을과 안동의 하회 마을은 유네스코 세계 문화유산으로 등재되었다.",hint:"ㅈㅌㅁㅎ",hint_b:"을/를 잘 간직하고 있는 경주의 양동 마을과 안동의 하회 마을은 유네스코 세계 문화유산으로 등재되었다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "중화학 공업", mean: "철강, 기계, 석유 화학 제품 등을 생산하는 공업", example_f:"서해안의 서산, 당진 등은 석유 화학, 제철 등",example_b:"이 발달했다.",hint:"ㅈㅎㅎ ㄱㅇ",hint_b:"이/가 발달했다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "남동 임해 공업 지역", mean: "경북 포항에서 전남 여수에 이르는 임해 공업 지역", example_f:"경북 포항에서 전남 여수에 이르는",example_b:"은 국내 최대의 중화학 공업 지역이다.",hint:"ㄴㄷ ㅇㅎ ㄱㅇ ㅈㅇ",hint_b:"은/는 국내 최대의 중화학 공업 지역이다.", imageBool: false,lineBreak:5,abbreviastion:false },
        { word: "제조업", mean: "원료를 가공하여 제품을 생산하는 산업", example_f:"천연자원이 부족한 우리나라는 자원을 수입하여 가공하고, 완제품을 수출하는 형태의",example_b:"이 발달하였다.",hint:"ㅈㅈㅇ",hint_b:"이/가 발달하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "조선업", mean: "배를 설계하여 만드는 일", example_f:"거제와 울산의",example_b:"은 우리나라를 대표하는 제조업이다.",hint:"ㅈㅅㅇ",hint_b:"은/는 우리나라를 대표하는 제조업이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "석유 화학 공업", mean: "석유나 천연가스를 원료로 하여 여러 가지 화학 제품을 만드는 공업", example_f:"여수의",example_b:"은 우리나라를 대표하는 제조업이다.",hint:"ㅅㅇ ㅎㅎ ㄱㅇ",hint_b:"은/는 우리나라를 대표하는 제조업이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "제철 공업", mean: "철광석을 용광로에 녹여 철을 뽑아내는 산업", example_f:"포항과 광양은",example_b:"이 발달하였다.",hint:"ㅈㅊ ㄱㅇ",hint_b:"이/가 발달하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "순환 경제", mean: "쓰레기를 줄이고 자원을 최대한 활용하는 것", example_f:"영·호남 지역은 최근 기후변화에 대응하고,",example_b:"를 이루기 위해 노력하고 있다.",hint:"ㅅㅎ ㄱㅈ",hint_b:"을/를 이루기 위해 노력하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "스마트 팜", mean: "정보 통신 기술을 농업 기술에 접목하여 자동 원격으로 농작물을 키울 수 있도록 조성한 농장", example_f:"최첨단 기술을 활용하여 작물의 생산성과 안정성을 높일 수 있는",example_b:"의 확산을 추진하고 있으며, 다양한 대체 식량의 연구와 개발에 힘쓰고 있다.",hint:"ㅅㅁㅌ ㅍ",hint_b:"의 확산을 추진하고 있으며, 다양한 대체 식량의 연구와 개발에 힘쓰고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "국제 자유 도시", mean: "사람, 상품, 자본 등의 이동이 자유롭고 기업 활동의 편의가 최대한 보장되도록 규제가 완화되는 지역", example_f:"특별자치도이자",example_b:"인 제주도는 관광·교육·첨단 산업 등을 집중하여 육성하고 있다.",hint:"ㄱㅈ ㅈㅇ ㄷㅅ",hint_b:"인 제주도는 관광·교육·첨단 산업 등을 집중하여 육성하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "모빌리티", mean: "사람들의 이동을 편리하게 해 주는 서비스나 이동 수단", example_f:"제주도는 관광객을 위한 자율 주행",example_b:"서비스를 제공하고 있다.",hint:"ㅁㅂㄹㅌ",hint_b:"서비스를 제공하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "인포그래픽", mean: "디자인 요소를 활용하여 정보, 자료, 지식을 시각적으로 표현한 것.", example_f:"",example_b:"을 활용하여 지리적 문제를 시각화할 수 있다.",hint:"ㅇㅍㄱㄹㅍ",hint_b:"을/를 활용하여 지리적 문제를 시각화할 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 11단원
      list: [
        { word: "피난민", mean: "재난이나 전쟁과 같은 이유로 다른 지역에 머무는 사람", example_f:"속초의 아바이 마을은 과거",example_b:"들이 정착하여 살게 되었다.",hint:"ㅍㄴㅁ",hint_b:"들이 정착하여 살게 되었다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "개마고원", mean: "백두산 서남쪽에 위치하며 우리나라에서 가장 높고 넓은 고원", example_f:"북동쪽에는 함경산맥과 마천령산맥 등 높고 험준한 산지와 화산 활동으로 형성된 백두산과",example_b:"이 있다.",hint:"ㄱㅁㄱㅇ",hint_b:"이/가 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "백두산", mean: "화산 활동으로 만들어진 우리나라에서 가장 높은 산 ", example_f:"천지는",example_b:"정상에 있는 호수로, 화산 활동으로 만들어졌다.",hint:"ㅂㄷㅅ",hint_b:"정상에 있는 호수로, 화산 활동으로 만들어졌다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "대륙성 기후", mean: "육지의 영향을 많이 받는 기후로 기온의 연교차와 일교차가 매우 크다.", example_f:"북부 지역은",example_b:"의 특징이 뚜렷하게 나타나 겨울이 춥고 길며, 여름은 짧다.",hint:"ㄷㄹㅅ ㄱㅎ",hint_b:"의 특징이 뚜렷하게 나타나 겨울이 춥고 길며, 여름은 짧다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "밭작물", mean: "밭에서 나는 곡식이나 작물", example_f:"북부 지역은 옥수수, 감자, 콩 등",example_b:"의 생산량이 많고, 이를 활용한 음식이 많다.",hint:"ㅂㅈㅁ",hint_b:"의 생산량이 많고, 이를 활용한 음식이 많다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "사회주의", mean: "개인보다 사회 전체의 이익을 중요시 여기는 이념", example_f:"북부 지역은 1991년대",example_b:" 경제권 붕괴를 계기로 경제 정책의 변화를 꾀하였다.",hint:"ㅅㅎㅈㅇ",hint_b:" 경제권 붕괴를 계기로 경제 정책의 변화를 꾀하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "개방 지역", mean: "영토의 일부를 외국의 자본과 기술을 도입할 수 있는 지역", example_f:"",example_b:"으로 1992년에 나선 경제 무역 지대를 지정하였으며, 이후 신의주 특별 행정구, 금강산 관광특구, 개성공업 지구 등을 지정하여 외국 자본을 끌어들이기 위해 노력하였다.",hint:"ㄱㅂ ㅈㅇ",hint_b:"(으)로 1992년에 나선 경제 무역 지대를 지정하였으며, 이후 신의주 특별 행정구, 금강산 관광특구, 개성공업 지구 등을 지정하여 외국 자본을 끌어들이기 위해 노력하였다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "서해 갑문", mean: "북부 지역의 남포와 은율은 잇는 세계적 규모의 갑문", example_f:"북부 지역의 항구는 동해안의 공업 도시와",example_b:"이 위치한 남포 등을 중심으로 분포한다.",hint:"ㅅㅎ ㄱㅁ",hint_b:"이/가 위치한 남포 등을 중심으로 분포한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "출경", mean: "어떤 지방의 경계를 넘어 다른 지방으로 나가는 것", example_f:"선수들은 평양에 가기 위해 버스를 타고 경기도 파주의 도라산 남북 출입 사무소에서",example_b:"절차를 밟았다.",hint:"ㅊㄱ",hint_b:"절차를 밟았다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "휴전선", mean: "전쟁 중인 두 국가 사이에 휴전을 합의하고 그어지는 군사행동의 경계선", example_f:"6·25전쟁이 1953년 7월 27일 23시에 휴전됨으로써 한반도의 가운데를 가로질러",example_b:"이 그어졌다.",hint:"ㅎㅈㅅ",hint_b:"이/가 그어졌다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "이산가족", mean: "진정, 자연재해 등으로 이리저리 흩어져서 서로 소식을 모르는 가족", example_f:"분단 기간이 길어지면서 남북 간의 언어와 가치관, 생활 모습 등의 차이가 커졌으며,",example_b:"이 오랜 기간 만나지 못하는 아픔도 계속되고 있다.",hint:"ㅇㅅㄱㅈ",hint_b:"이/가 오랜 기간 만나지 못하는 아픔도 계속되고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "접경지역", mean: "국가 간의 경계가 서로 맞닿은 지역으로, 국경 인근 지역 또는 경계에 인접한 곳 ", example_f:"우리나라에는 남북 사이의",example_b:"과 중국, 러시아와의 접경지역이 있다.",hint:"ㅈㄱㅈㅇ",hint_b:"과 중국, 러시아와의 접경지역이 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "비무장 지대(DMZ)", mean: "휴전선에서 남북으로 각각 2km씩의 구간에 설정된 지대로, 남북한은 이곳에 군대나 무기, 군사 시설을 설치하지 않는 지역", example_f:"",example_b:"(DMZ)는 그동안 남과 북이 대립하고 갈등하는 분단의 상징으로 인식되었으나, 이제는 생물 다양성의 보고이자 평화의 상징성을 지닌 공간으로 그 가치가 주목받고 있다.",hint:"ㅂㅁㅈ ㅈㄷ(DMZ)",hint_b:"(DMZ)은/는 그동안 남과 북이 대립하고 갈등하는 분단의 상징으로 인식되었으나, 이제는 생물 다양성의 보고이자 평화의 상징성을 지닌 공간으로 그 가치가 주목받고 있다.", imageBool: false,lineBreak:0,abbreviastion:true },
        { word: "완충 지대", mean: "두 지역 사이의 충돌을 완화하기 위해 설치한 중립 지역", example_f:"남북 사이의 접경지역은 군사적",example_b:"로서 오랫동안 사람들의 출입이 제한된 비무장 지대(DMZ)와 그 인근 지역을 말한다.",hint:"ㅇㅊ ㅈㄷ",hint_b:"(으)로서 오랫동안 사람들의 출입이 제한된 비무장 지대(DMZ)와 그 인근 지역을 말한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "민간인 통제선", mean: "군사 작전상 민간인의 출입을 통제하기 위하여 설정한 선(휴전선 남방 5~20km 범위)", example_f:"대성동 마을은",example_b:"내에 있는 마을이다.",hint:"ㅁㄱㅇ ㅌㅈㅅ",hint_b:"내에 있는 마을이다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "경제 무역 지대", mean: "중국의 경제 특구를 모방하여 외국과의 합작 투자 및 무역 진흥을 도모하기 위하여 설치한 지역", example_f:"중국, 러시아와 인접한 접경지역에는 대외 무역과 외국 자본 유치를 통해 경제를 활성화하는",example_b:"가 지정되었다",hint:"ㄱㅈ ㅁㅇ ㅈㄷ",hint_b:"이/가 지정되었다", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "천연기념물", mean: "학술 및 관상적 가치가 높아 그 보호와 보존을 법률로써 지정한 동물·식물·지질·광물과 그 밖의 천연물", example_f:"비무장 지대(DMZ) 내에 서식하는",example_b:"로 수달, 두루미, 산양 등이 있다.",hint:"ㅊㅇㄱㄴㅁ",hint_b:"(으)로 수달, 두루미, 산양 등이 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "멸종 위기종", mean: "개체수가 매우 적거나 서식지 파괴, 기후변화 등으로 인해 멸종의 위험이 있는 동물", example_f:"비무장 지대(DMZ) 는 오랫동안 인간의 출입이 제한되어",example_b:"이 서식하고 있다.",hint:"ㅁㅈ ㅇㄱㅈ",hint_b:"이/가 서식하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "아시안 하이웨이", mean: "아시아와 유럽의 여러 국가를 연결하는 고속 국도", example_f:"",example_b:"를 통해, 도로망 연결되어 국가 간의 교류와 협력이 강화되고 있다.",hint:"ㅇㅅㅇ ㅎㅇㅇㅇ",hint_b:"을/를 통해, 도로망 연결되어 국가 간의 교류와 협력이 강화되고 있다.", imageBool: false,lineBreak:3,abbreviastion:false },
        { word: "베를린 장벽", mean: "냉전 시대 동독이 건설한 것으로서 서베를린을 동베를린과 분리하는 장벽", example_f:"주변 국가들의 협조와 주민들 간 활발한 교류를 통해 마침내",example_b:"을 허물고 1991년에 통일했다.",hint:"ㅂㄹㄹ ㅈㅂ",hint_b:"을/를 허물고 1991년에 통일했다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "동아시아 지역", mean: "대한민국, 중국, 일본 등의 나라가 속해있는 아시아의 동북부 지역", example_f:"한반도의 평화 속에서 우리나라는",example_b:"교류의 중심지로서 주변 국가들의 갈등을 중재하고, 평화와 협력을 끌어내는 데 주도적인 역할을 할 수 있다.",hint:"ㄷㅇㅅㅇ ㅈㅇ",hint_b:"교류의 중심지로서 주변 국가들의 갈등을 중재하고, 평화와 협력을 끌어내는 데 주도적인 역할을 할 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "유라시아", mean: "유럽과 아시아를 하나로 묶어 부르는 이름", example_f:"통일이 된다면 우리나라는 연결하는 물류 중심지로 성장할 수 있으며 한반도와",example_b:"전체를 대상으로 경제활동을 할 수 있게 된다",hint:"ㅇㄹㅅㅇ",hint_b:"전체를 대상으로 경제활동을 할 수 있게 된다", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "생활권", mean: "행정 구역과는 관계없이 통학이나 통근, 쇼핑, 오락 따위의 일상생활을 하느라고 활동하는 범위", example_f:"통일이 된다면",example_b:"이 확대되고 새로운 직업과 일자리가 늘어나 경제가 발전한다.",hint:"ㅅㅎㄱ",hint_b:"이/가 확대되고 새로운 직업과 일자리가 늘어나 경제가 발전한다.", imageBool: false,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 12단원
      list: [
        { word: "식량 자원", mean: "쌀, 보리, 콩, 옥수수 등 사람의 먹을거리가 되는 자원", example_f:"",example_b:"은 인간이 생존하는 데 필요한 각종 영양소를 공급하는 자원으로 곡물, 육류, 채소와 과실을 포함한다.",hint:"ㅅㄹ ㅈㅇ",hint_b:"은/는 인간이 생존하는 데 필요한 각종 영양소를 공급하는 자원으로 곡물, 육류, 채소와 과실을 포함한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "자급률", mean: "필요한 자원을 해당 국가에서 자체적으로 공급하는 비율", example_f:"우리나라는 쌀을 제외한 콩, 밀, 옥수수 등의 곡물을 대부분 수입에 의존해 곡물 자원의",example_b:"이 낮다.",hint:"ㅈㄱㄹ",hint_b:"이/가 낮다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "비축 기지", mean: "주요 자원의 수급을 원활히 하고 가격 안정과 경제 사회적 혼란을 예방하기 위하여 자원을 비축해 두는 기지", example_f:"주요 곡물과 수입 의존도가 높은 농산물에 대해서는 해외 공급망을 확보하고, 농산물",example_b:"를 구축해 수요와 공급을 조절하는 방안을 마련하고 있다.",hint:"ㅂㅊ ㄱㅈ",hint_b:"을/를 구축해 수요와 공급을 조절하는 방안을 마련하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "스마트 팜", mean: "정보 통신 기술을 농업 기술에 접목하여 자동 원격으로 농작물을 키울 수 있도록 조성한 농장", example_f:"최첨단 기술을 활용하여 작물의 생산성과 안정성을 높일 수 있는",example_b:"의 확산을 추진하고 있으며, 다양한 대체 식량의 연구와 개발에 힘쓰고 있다.",hint:"ㅅㅁㅌ ㅍ",hint_b:"의 확산을 추진하고 있으며, 다양한 대체 식량의 연구와 개발에 힘쓰고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "식물성 고기", mean: "식물성 원료를 이용하여 고기와 유사하게 만든 음식", example_f:"최근 환경 보전, 건강한 식생활, 동물 복지 등에 대한 관심이 커지면서 다양한",example_b:"제품이 출시되어 시장 규모가 점차 커지고 있다.",hint:"ㅅㅁㅅ ㄱㄱ",hint_b:"제품이 출시되어 시장 규모가 점차 커지고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "화석 에너지", mean: "석탄, 석유, 천연가스 등 동식물이 오랜 시간에 걸쳐 온도와 압력의 변화로 만들어진 연료로 ", example_f:"",example_b:"의 매장량은 한정되어 있으며, 환경오염의 문제를 가지고 있다.",hint:"ㅎㅅ ㅇㄴㅈ",hint_b:"의 매장량은 한정되어 있으며, 환경오염의 문제를 가지고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "재생 에너지", mean: "태양열, 수력, 풍력, 조력, 지열 고갈되지 않고 지속해서 사용할 수 있는 에너지", example_f:"온실 기체의 배출량을 줄이기 위해",example_b:"의 사용 비중을 늘리고 있다.",hint:"ㅈㅅ ㅇㄴㅈ",hint_b:"의 사용 비중을 늘리고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "미세 먼지", mean: "자동차, 화력 발전소 등에서 배출된 오염 물질이 공기 중 다른와 결합된 입자가 매우 작은 먼지 ", example_f:"",example_b:"주의보가 내렸을 때에는 실외 활동을 줄이고, 외출시 마스크를 착용한다.",hint:"ㅁㅅ ㅁㅈ",hint_b:"주의보가 내렸을 때에는 실외 활동을 줄이고, 외출시 마스크를 착용한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "전자 쓰레기", mean: "더 이상 가치가 없게 된 낡고 수명이 다한 여러 가지 형태의 전기·전자 제품", example_f:"기술의 발달로 기능이 향상된 신제품의 출시 주기는 짧아지고 경제성장에 따라 소비자의 구매성향이 다양해지면서 버려지는",example_b:"가 꾸준히 증가하고 있다.",hint:"ㅈㅈ ㅆㄹㄱ",hint_b:"이/가 꾸준히 증가하고 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "글로컬 환경 이슈", mean: "지역 또는 세계적인 규모에서 발생하는 환경 문제 중 원인과 해결 방안에 대한 입장이 서로 달라 논쟁이 벌어지는 것", example_f:"세계 곳곳에서는 지역 개발과 환경 보전을 둘러싼",example_b:"가 발생하고 있다.",hint:"ㄱㄹㅋ ㅎㄱ ㅇㅅ",hint_b:"이/가 발생하고 있다.", imageBool: false,lineBreak:3,abbreviastion:false },
        { word: "플랜테이션", mean: "열대 기후 지역에서 선진국의 자본과 원주민의 노동력으로 커피, 카카오, 바나나 등의 상품 작물을 대규모로 재배하는 농업 형태", example_f:"초국적 기업은 개발 도상국에 생산 공장을 짓거나",example_b:"농장을 만들었는데, 토양 황폐화와 식수 오염, 생태계 파괴 등 다양한 환경 문제를 유발하기도 했다.",hint:"ㅍㄹㅌㅇㅅ",hint_b:"농장을 만들었는데, 토양 황폐화와 식수 오염, 생태계 파괴 등 다양한 환경 문제를 유발하기도 했다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "팜유", mean: "기름야자 열매의 과육을 쪄서 압축 채유되는 식물성 유지", example_f:"",example_b:"덕분에 우리는 과자, 라면, 초콜릿 등을 저렴한 가격에 먹을 수 있다. 팜유가 없다면 이를 대체할 수 있는 식물성 기름이 있어야한다.",hint:"ㅍㅇ",hint_b:"덕분에 우리는 과자, 라면, 초콜릿 등을 저렴한 가격에 먹을 수 있다. 팜유가 없다면 이를 대체할 수 있는 식물성 기름이 있어야한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "웰빙", mean: "몸과 마음의 건강을 통해 행복을 추구하며 살아가는 일", example_f:"지구촌 구성원 모두가 세계시민으로서 책임감을 가지고 환경과 인간의 공존을 추구해야 하며, 자신과 공동체의",example_b:"을 기반으로 지속가능한 발전을 위해 참여하고 실천해야 한다",hint:"ㅇㅂ",hint_b:"을/를 기반으로 지속가능한 발전을 위해 참여하고 실천해야 한다", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "친환경 소비", mean: "지구 환경에 주는 부담을 주지 않거나 최대한 적게 하는 소비 행태", example_f:"개인은 자원을 절약하고",example_b:"를 실천하며, 환경 보호 활동에 참여해야 한다.",hint:"ㅊㅎㄱ ㅅㅂ",hint_b:"을/를 실천하며, 환경 보호 활동에 참여해야 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "합성 섬유", mean: "석유, 석탄, 천연가스 등을 원료로 하여 화학적으로 합성한 섬유", example_f:"옷이 소각될 때 저렴한 비용으로 만든",example_b:"가 타면서 유독 물질이 발생하여 환경을 오염하고 인체에도 나쁜 영향을 미친다.",hint:"ㅎㅅ ㅅㅇ",hint_b:"이/가 타면서 유독 물질이 발생하여 환경을 오염하고 인체에도 나쁜 영향을 미친다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "플로깅", mean: "산책하거나 달리기를 하면서 쓰레기를 줍는 환경 보호 활동", example_f:"쓰레기봉투만 있으면 언제 어디서든 할 수 있는 활동이며,",example_b:"을 통해 체력을 기르는 동시에 환경을 정화하는 효과를 얻을 수 있어 환경을 지키기 위한 작은 실천에 동참할 수 있다.",hint:"ㅍㄹㄱ",hint_b:"을/를 통해 체력을 기르는 동시에 환경을 정화하는 효과를 얻을 수 있어 환경을 지키기 위한 작은 실천에 동참할 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "지역문제 해결 플랫폼", mean: "지역 사회의 문제를 주민, 정부, 지방 자치 단체, 공공 기관 등이 협력하여 해결하는 협업 체계", example_f:"다양한 지리적 문제를 해결하고 더 나은 지역을 만들기 위해",example_b:" 등의 협업 체계를 통해 여러 주체가 노력하고 있다.",hint:"ㅈㅇㅁㅈ ㅎㄱ ㅍㄹㅍ",hint_b:" 등의 협업 체계를 통해 여러 주체가 노력하고 있다.", imageBool: false,lineBreak:4,abbreviastion:false },
        { word: "정책 제안서", mean: "새롭게 제정이 필요한 정책이나 기존 정책의 수정이 필요함을 정부에 제안하기 위한 서식", example_f:"",example_b:"는 깔끔한 형식과 명료한 내용, 그리고 설득력 있는 어투로 작성해 지방 자치 단체에 지역의 지리적 문제 해결 방안을 제안할 수 있다.",hint:"ㅈㅊ ㅈㅇㅅ",hint_b:"은/는 깔끔한 형식과 명료한 내용, 그리고 설득력 있는 어투로 작성해 지방 자치 단체에 지역의 지리적 문제 해결 방안을 제안할 수 있다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "마을 공동체", mean: "지역의 문제를 함께 고민하고 스스로 해결해 나가는 지역 주민 간의 관계망", example_f:"",example_b:"는 지역의 지리적 문제 해결을 위해 함께 계획을 수립하고 실행하면서 주민들의 삶의 질을 높이는 것을 목적으로 한다.",hint:"ㅁㅇ ㄱㄷㅊ",hint_b:"은/는 지역의 지리적 문제 해결을 위해 함께 계획을 수립하고 실행하면서 주민들의 삶의 질을 높이는 것을 목적으로 한다.", imageBool: false,lineBreak:0,abbreviastion:false },
        { word: "협동조합", mean: "비슷한 목적을 가진 생산자 또는 소비자가 조합하여 만든 단체", example_f:"아이들의 성장에 따른 생애 주기 교육과 생활 속 안전한 먹거리에 대한 문제를 고민하여 대안 학교와 생활",example_b:"등을 만들었다.",hint:"ㅎㄷㅈㅎ",hint_b:"등을 만들었다.", imageBool: false,lineBreak:0,abbreviastion:false },
      ],
    },
  
  ],


  // quiz: [
  //   {
  //     // 1단원 
  //     list: [
  //       { word: "지도", mean: "위에서 내려다본 땅의 실제 모습을 일정한 약속에 따라 줄여서 나타낸 것", imageBool: true ,lineBreak:0,abbreviastion:false},
  //       { word: "항공 사진", mean: "비행 중인 항공기에서 땅의 모습을 찍은 사진", imageBool: true ,lineBreak:0,abbreviastion:false},
  //       { word: "방위", mean: "방향의 위치", imageBool: false,lineBreak:0,abbreviastion:false },
  //     ],
  //   },
  //   {
  //     // 2단원 
  //     list: [
  //       { word: "문화유산", mean: "옛날 사람들의 생활 모습을 알려 주는 것 중 후손들에게 물려줄 만한 가치가 있는 것", imageBool: true ,lineBreak:0,abbreviastion:false},
  //       { word: "유형 문화유산", mean: "그림이나 책, 건물처럼 형태가 있는 문화유산", imageBool: true ,lineBreak:0,abbreviastion:false},
  //       { word: "무형 문화유산", mean: "음악이나 춤, 연극, 기술과 같이 형태가 없는 문화유산", imageBool: true ,lineBreak:0,abbreviastion:false},
  //       { word: "목판", mean: "책을 인쇄하려고 나무에 글씨를 새긴 것", imageBool: false,lineBreak:0,abbreviastion:false }
  //     ],
  //   },
  //   {
  //     // 3단원 
  //     list: [
  //       { word: "경제활동", mean: "사람들이 생활하는 데 필요한 여러 가지 물건을 만들고 사용하는 것과 관련된 활동", imageBool: true ,lineBreak:0,abbreviastion:false},
  //       { word: "자원", mean: "생활에 필요한 것을 만드는 데 사용되는 모든 것", imageBool: false,lineBreak:0,abbreviastion:false },
  //       { word: "한정", mean: "수량이나 범위가 정해져 있음.", imageBool: false,lineBreak:0,abbreviastion:false }
  //     ],
  //   },
  // ],
};
