var dicData = {
  // 4학년 1학기
  part: [
    // {
      // 전체 단원
      // list: [
        // 전체 단원 
      // ],
    // },
    {
      // 사회 1권 1단원
      
      list: [
        { word: "절대적 위치", word_q: "절대적 위치", mean: "어떤 지역의 변하지 않는 고정적인 정보", example_f: "위도와 경도를 이용하여 우리나라의", example_b:"를 나타낼 수 있다.",hint:"ㅈㄷㅈ ㅇㅊ", hint_b: "을/를 나타낼 수 있다. ", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "상대적 위치", word_q: "상대적 위치", mean: "주변 국가와의 관계에 따라 결정되는 위치", example_f:"한 국가의",example_b:"는 시대나 상황에 따라 변화한다.",hint:"ㅅㄷㅈ ㅇㅊ",hint_b:"은/는 시대나 상황에 따라 변화한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "경도", word_q: "경도", mean: "본초 자오선을 기준으로 동서로 얼마나 떨어졌는지 나타내는 각도. 동쪽과 서쪽을 각각 180°로 나눔.", example_f:"세계 여러 지역은",example_b:"에 따라 시간이 달라진다.",hint:"ㄱㄷ",hint_b:"에 따라 시간이 달라진다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "위도", word_q: "위도", mean: "적도를 기준으로 남북으로 얼마나 떨어졌는지 나타내는 각도. 북쪽과 남쪽을 각각 90°로 나눔.", example_f:"세계의 기온 분포는",example_b:"에 따라 달라진다.",hint:"ㅇㄷ",hint_b:"에 따라 달라진다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "표준 경선", word_q: "표준 경선", mean: "영국을 지나는 경도 0°를 기준으로, 15°의 배수에 해당하는 지역을 지나가는 경선", example_f:"우리나라는 동경 135°를",example_b:"으로 한다.",hint:"ㅍㅈ ㄱㅅ",hint_b:"(으)로 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "산맥", word_q: "산맥", mean: "산지의 여러 산들이 이어진 지형", example_f:"태백산맥은 우리나라에서 가장 긴",example_b:"이다.",hint:"ㅅㅁ",hint_b:"이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "평야", word_q: "평야", mean: "기복이 적으며 넓고 평평한 땅", example_f:"넓게 펼쳐진",example_b:"에서 논농사를 짓기도 한다.",hint:"ㅍㅇ",hint_b:"에서 논농사를 짓기도 한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "하천", word_q: "하천", mean: "빗물이 낮은 곳으로 흘러가면서 만든 크고 작은 물줄기", example_f:"",example_b:"주변은 물을 쉽게 구할 수 있어 도시가 발달하였다.",hint:"ㅎㅊ",hint_b:"주변은 물을 쉽게 구할 수 있어 도시가 발달하였다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "해안", word_q: "해안", mean: "바다와 육지가 만나는 곳", example_f:"",example_b:" 지역의 사람들은 어업과 양식업에 종사하기도 한다.",hint:"ㅎㅇ",hint_b:"지역의 사람들은 어업과 양식업에 종사하기도 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "판", word_q: "판", mean: "지구의 겉 부분을 둘러싸는 넓은 암석 판", example_f:"",example_b:"의 경계에서는 지진과 화산 활동이 활발히 이루어진다.",hint:"ㅍ",hint_b:"의 경계에서는 지진과 화산 활동이 활발히 이루어진다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "도시", word_q: "도시", mean: "사람들의 생활 공간이자 정치·경제·사회·문화의 중심지", example_f:"",example_b:"에는 회사나 공장이 많아 일자리가 풍부하다.",hint:"ㄷㅅ",hint_b:"에는 회사나 공장이 많아 일자리가 풍부하다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "히말라야산맥", word_q: "히말라야산맥", mean: "중국, 인도, 파키스탄 등 여러 국가에 걸쳐 있는 산맥", example_f:"",example_b:"의 높은 봉우리들을 오르고 싶어 하는 산악인들이 많다.",hint:"ㅎㅁㄹㅇㅅㅁ",hint_b:"의 높은 봉우리들을 오르고 싶어 하는 산악인들이 많다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "기후", word_q: "기후", mean: "어떤 지역에서 여러 해 걸쳐 나타난 날씨의 평균적인 상태", example_f:"세계 각 지역의",example_b:"는 위도, 해발 고도 등에 따라 다양하게 나타난다.",hint:"ㄱㅎ",hint_b:"은/는 위도, 해발 고도 등에 따라 다양하게 나타난다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "열대 기후", word_q: "열대 기후", mean: "일 년 내내 기온이 높고 강수량이 많은 기후", example_f:"인도네시아 보르네오섬은",example_b:"가 나타나 일 년 내내 기온이 높고 비가 많이 오는 편이다.",hint:"ㅇㄷ ㄱㅎ",hint_b:"이/가 나타나 일 년 내내 기온이 높고 비가 많이 오는 편이다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "온대 기후", word_q: "온대 기후", mean: "기온이 온화하며 강수량이 풍부한 편인 기후", example_f:"캐나다 서부의 밴쿠버는 사계절이 뚜렷하고 기온이 온화한",example_b:"가 나타난다",hint:"ㅇㄷ ㄱㅎ",hint_b:"이/가 나타난다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "냉대 기후", word_q: "냉대 기후", mean: "온대 기후보다 겨울이 길고 추운 기후", example_f:"",example_b:" 지역은 겨울이 춥고 긴 반면, 여름은 짧다.",hint:"ㄴㄷ ㄱㅎ",hint_b:"지역은 겨울이 춥고 긴 반면, 여름은 짧다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "한대 기후", word_q: "한대 기후", mean: "일 년 내내 평균 기온이 매우 낮은 기후", example_f:"",example_b:" 지역은 몹시 추워서 나무가 자라지 못하지만, 여름에 이끼와 풀이 자라기도 한다.",hint:"ㅎㄷ ㄱㅎ",hint_b:"지역은 몹시 추워서 나무가 자라지 못하지만, 여름에 이끼와 풀이 자라기도 한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "건조 기후", word_q: "건조 기후", mean: "일 년 동안의 강수량이 500mm보다 적은 기후", example_f:"",example_b:"지역은 강수량보다 증발량이 많아 나무가 거의 자라지 못한다.",hint:"ㄱㅈ ㄱㅎ",hint_b:"지역은 강수량보다 증발량이 많아 나무가 거의 자라지 못한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "고산 기후", word_q: "고산 기후", mean: "높은 산지에서 나타나며, 주변의 고도가 낮은 지역보다 기온이 낮은 기후", example_f:"",example_b:"는 살기 좋은 온화한 기온이 나타나, 남아메리카의 적도 부근 고산 지역에서는 아스테카 문명, 잉카 문명이 발달했다.",hint:"ㄱㅅ ㄱㅎ",hint_b:"은/는 살기 좋은 온화한 기온이 나타나, 남아메리카의 적도 부근 고산 지역에서는 아스테카 문명, 잉카 문명이 발달했다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "산업", word_q: "산업", mean: "인간의 생활을 경제적으로 풍요롭게 하기 위한 활동", example_f:"어떤",example_b:"이 발달했느냐에 따라 주민들이 살아가는 방식이 달라진다.",hint:"ㅅㅇ",hint_b:"이/가 발달했느냐에 따라 주민들이 살아가는 방식이 달라진다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "종교", word_q: "종교", mean: "신이나 절대적인 힘에 대한 믿음을 통해 고민을 해결하고 삶의 궁극적인 의미를 추구하는 문화 체계", example_f:"",example_b:"가 다르면 문화 경관 또한 다르게 나타난다.",hint:"ㅈㄱ",hint_b:"이/가 다르면 문화 경관 또한 다르게 나타난다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "언어", word_q: "언어", mean: "생각이나 느낌을 나타내거나 전달하는 데에 쓰는 말 또는 글", example_f:"의사소통의 수단인",example_b:"는 오랜 시간을 거쳐 세계 여러 지역으로 전파되고 정착되었다.",hint:"ㅇㅇ",hint_b:"은/는 오랜 시간을 거쳐 세계 여러 지역으로 전파되고 정착되었다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "인문환경", word_q: "인문환경", mean: "사람들이 자연을 이용하여 만들어낸 것", example_f:"",example_b:"은 산업, 종교, 언어 등을 포함하며, 세계 여러 지역의 특성을 다채롭게 만든다.",hint:"ㅇㅁㅎㄱ",hint_b:"은/는 산업, 종교, 언어 등을 포함하며, 세계 여러 지역의 특성을 다채롭게 만든다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "백야", word_q: "백야", mean: "고위도 지역에서 여름 동안 밤에도 어두워지지 않는 현상", example_f:"핀란드는 여름에",example_b:" 현상이 나타나 하루 종일 해가 떠 있다.",hint:"ㅂㅇ",hint_b:"현상이 나타나 하루 종일 해가 떠 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "세계시민", word_q: "세계시민", mean: "자신을 지구 공동체의 구성원으로 여기고, 지구촌 문제 해결에 적극적으로 노력하는 사람", example_f:"우리는",example_b:"으로서 세계 각 지역의 특성을 이해하고, 다양성과 고유성을 존중해야 한다.",hint:"ㅅㄱㅅㅁ",hint_b:"(으)로서 세계 각 지역의 특성을 이해하고, 다양성과 고유성을 존중해야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "중계 무역", word_q: "중계 무역", mean: "다른 국가에서 사들인 물자를 다른 국가로 수출하는 형식의 무역", example_f:"싱가포르는 태평양과 인도양을 연결하는 해상 교통의 중요 지점에 위치하여 일찍부터",example_b:"이 발달하였다.",hint:"ㅈㄱ ㅁㅇ",hint_b:"이/가 발달하였다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "공간적 상호 작용", word_q: "공간적 상호 작용", mean: "여러 장소 간에 사람, 물자, 정보 등이 이동하는 것으로, 장소 사이의 거리가 가까울수록 활발히 일어남. ", example_f:"",example_b:"이 활발해지면서 사람과 정보의 이동이 활발해졌다.",hint:"ㄱㄱㅈ ㅅㅎ ㅈㅇ",hint_b:"이/가 활발해지면서 사람과 정보의 이동이 활발해졌다.", imageBool: false ,lineBreak:3,abbreviastion:false },
        { word: "시공간 압축", word_q: "시공간 압축", mean: "교통과 통신이 발달하면서 장소 간 이동에 필요한 시간이 줄어드는 현상", example_f:"",example_b:"으로 국가나 지역 간 교류가 늘어나고 있다.",hint:"ㅅㄱㄱ ㅇㅊ",hint_b:"(으)로 국가나 지역 간 교류가 늘어나고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "네트워크", word_q: "네트워크", mean: "장소, 사람, 시설 등이 그물망처럼 연결되어 있는 것", example_f:"다양한",example_b:"를 통해 사람과 정보 등이 이동할 수 있다.",hint:"ㄴㅌㅇㅋ",hint_b:"을/를 통해 사람과 정보 등이 이동할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "교통 네트워크", word_q: "교통 네트워크", mean: "지하철과 버스 노선도 등의 교통로가 그물망처럼 연결된 것", example_f:"",example_b:"를 통해 편리하게 이동할 수 있다.",hint:"ㄱㅌ ㄴㅌㅇㅋ",hint_b:"을/를 통해 편리하게 이동할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "통신 네트워크", word_q: "통신 네트워크", mean: "인터넷, 컴퓨터, 스마트폰 등을 이용하여 실시간으로 정보를 주고받을 수 있도록 하는 것", example_f:"",example_b:"의 발달로, 어디서든 쇼핑을 하거나 강의를 들을 수 있다.",hint:"ㅌㅅ ㄴㅌㅇㅋ",hint_b:"의 발달로, 어디서든 쇼핑을 하거나 강의를 들을 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "항공 네트워크", word_q: "항공 네트워크", mean: "세계의 주요 공항들 간 항공 노선이 그물망처럼 연결된 것", example_f:"세계의 주요 공항들은",example_b:"상에서 중요한 역할을 한다.",hint:"ㅎㄱ ㄴㅌㅇㅋ",hint_b:"상에서 중요한 역할을 한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "해저 케이블", word_q: "해저 케이블", mean: "통신을 목적으로 바닷속에 설치한 케이블", example_f:"",example_b:"이 설치되어 다른 대륙의 사람과도 정보를 주고받을 수 있다.",hint:"ㅎㅈ ㅋㅇㅂ",hint_b:"이/가 설치되어 다른 대륙의 사람과도 정보를 주고받을 수 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "해운", word_q: "해운", mean: "배로 사람을 태우거나 화물을 실어 나르는 일", example_f:"",example_b:" 교통이 발달하여 다른 국가와의 무역이 활발해졌다.",hint:"ㅎㅇ",hint_b:"교통이 발달하여 다른 국가와의 무역이 활발해졌다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "컨테이너", word_q: "컨테이너", mean: "화물 수송에 이용하는, 쇠로 만들어진 큰 상자", example_f:"이 항구에는 무역품을 실은 수많은",example_b:"가 모여 있다.",hint:"ㅋㅌㅇㄴ",hint_b:"이/가 모여 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "세계화", word_q: "세계화", mean: "세계가 국경을 넘어 하나로 통합되고 지역 간 상호 의존성이 커지는 현상", example_f:"",example_b:" 시대인 오늘날에는 사람과 정보의 국제 이동이 활발하여, 우리나라 길거리에서도 외국인과 쉽게 마주칠 수 있다.",hint:"ㅅㄱㅎ",hint_b:"시대인 오늘날에는 사람과 정보의 국제 이동이 활발하여, 우리나라 길거리에서도 외국인과 쉽게 마주칠 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "문화의 세계화", word_q: "문화의 세계화", mean: "세계 어디서나 비슷한 문화를 즐기는 현상", example_f:"",example_b:"에 따라 음식, 영화 등 다양한 문화가 빠르게 확산된다.",hint:"ㅁㅎㅇ ㅅㄱㅎ",hint_b:"에 따라 음식, 영화 등 다양한 문화가 빠르게 확산된다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "경제의 세계화", word_q: "경제의 세계화", mean: "상품과 서비스, 자본, 노동력 등을 활발하게 교류하고 세계가 하나의 시장으로 통합되는 현상", example_f:"",example_b:"에 따라, 우리가 사용하는 스마트폰의 생산과 판매 과정에 여러 국가와 기업이 관여한다.",hint:"ㄱㅈㅇ ㅅㄱㅎ",hint_b:"에 따라, 우리가 사용하는 스마트폰의 생산과 판매 과정에 여러 국가와 기업이 관여한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "아이스 버킷 챌린지", word_q: "아이스 버킷 챌린지", mean: "루게릭병 환자를 위한 기부금을 모으기 위해 미국에서 시작된 모금 캠페인", example_f:"",example_b:"는 사회 관계망 서비스(SNS)를 통해 전 세계로 확산하였다.",hint:"ㅇㅇㅅ ㅂㅋ ㅊㄹㅈ",hint_b:"은/는 사회 관계망 서비스(SNS)를 통해 전 세계로 확산하였다.", imageBool: false ,lineBreak:6,abbreviastion:false },
        { word: "지역화 전략", word_q: "지역화 전략", mean: "지역의 고유한 전통이나 지리적 특성을 살려 지역 경쟁력을 높이는 전략", example_f:"우리 지역은",example_b:"을 잘 활용하여 세계에 널리 알려졌다.",hint:"ㅈㅇㅎ ㅈㄹ",hint_b:"을/를 잘 활용하여 세계에 널리 알려졌다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "지리적 표시제", word_q: "지리적 표시제", mean: "상품에 지역의 기후, 지형, 토양 등의 지리적 특성이 반영된 경우, 해당 지역에서 생산, 제조, 가공되었음을 표시할 수 있도록 하는 제도", example_f:"우리나라에서는 2002년 보성 녹차가 최초로",example_b:"에 등록되었다.",hint:"ㅈㄹㅈ ㅍㅅㅈ",hint_b:"에 등록되었다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "지역 브랜드", word_q: "지역 브랜드", mean: "지역의 상품과 서비스가 하나의 브랜드로 인식되도록 하여 지역의 이미지를 형성하는 것", example_f:"",example_b:"는 도시의 가치와 특별함을 담고 있다.",hint:"ㅈㅇ ㅂㄹㄷ",hint_b:"은/는 도시의 가치와 특별함을 담고 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "장소 마케팅", word_q: "장소 마케팅", mean: "장소 또는 도시 공간의 고유한 특성에 맞는 이미지와 상품을 개발하여 지역 가치를 높이는 홍보 전략", example_f:"우리 도시는",example_b:"을 통해 친환경적인 도시 이미지를 만들어냈다.",hint:"ㅈㅅ ㅁㅋㅌ",hint_b:"을/를 통해 친환경적인 도시 이미지를 만들어냈다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "문화 콘텐츠", word_q: "문화 콘텐츠", mean: "음악, 영화 등 문화적 요소를 지닌 내용물이 인터넷 등 통신 네트워크를 통해 유통될 수 있도록 매체에 담긴 것", example_f:"우리나라의",example_b:"는 세계로 확산하여 성공을 거두고 있다.",hint:"ㅁㅎ ㅋㅌㅊ",hint_b:"은/는 세계로 확산하여 성공을 거두고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "한류", word_q: "한류", mean: "대한민국의 대중문화가 여러 국가에서 유행하는 현상", example_f:"",example_b:" 열풍으로 우리나라의 대중 가수들이 미국, 영국 등에서 인기를 얻고 있다.",hint:"ㅎㄹ",hint_b:"열풍으로 우리나라의 대중 가수들이 미국, 영국 등에서 인기를 얻고 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
      ],
    },
    {
      // 사회 1권 2단원
      
      list: [
        { word: "우랄산맥", word_q: "우랄산맥", mean: "유럽과 아시아의 경계를 따라 남북으로 이어진 산맥", example_f:"아시아와 유럽은 러시아의 ",example_b:"을 경계로 구분할 수 있다.",hint:"ㅇㄹㅅㅁ",hint_b:"을/를 경계로 구분할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "아시아", word_q: "아시아", mean: "서쪽으로는 유럽, 서남쪽으로는 아프리카, 동쪽으로는 태평양과 접하며, 우리나라, 중국, 일본 등을 포함하는 대륙", example_f:"우리나라 사람들은 지리적으로 가까운",example_b:"의 국가로 해외여행을 많이 간다.",hint:"ㅇㅅㅇ",hint_b:"의 국가로 해외여행을 많이 간다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "기후변화", word_q: "기후변화", mean: "일정 지역에서 오랜 기간에 걸쳐서 기후가 변하는 현상", example_f:"",example_b:"에 따라 생물 종 다양성이 감소하는 등의 피해가 발생하고 있다.",hint:"ㄱㅎㅂㅎ",hint_b:"에 따라 생물 종 다양성이 감소하는 등의 피해가 발생하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "맹그로브 숲", word_q: "맹그로브 숲", mean: "주로 열대 기후 지역의 바다나 습지에서 발달하는 숲으로, 뿌리가 복잡하게 얽혀 있음.", example_f:"",example_b:"은 다양한 동물의 서식처가 되며 태풍으로부터의 피해를 완화한다.",hint:"ㅁㄱㄹㅂ ㅅ",hint_b:"은/는 다양한 동물의 서식처가 되며 태풍으로부터의 피해를 완화한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "유네스코 세계 유산", word_q: "유네스코 세계 유산", mean: "미래 세대에 전달할 만한 가치가 있는 자연이나 문화를 보존하기 위해 유네스코가 지정하는 유산", example_f:"우리나라의 제주도는",example_b:"에 등재된 아름다운 섬이다.",hint:"ㅇㄴㅅㅋ ㅅㄱ ㅇㅅ",hint_b:"에 등재된 아름다운 섬이다.", imageBool: false ,lineBreak:4,abbreviastion:false },
        { word: "열대림", word_q: "열대림", mean: "열대 기후가 나타나는 곳에 분포하는 숲으로, 키가 크고 작은 나무들과 다양한 식물들이 분포함.", example_f:"콩고 민주 공화국의",example_b:"에는 키가 크고 작은 나무들과 다양한 식물들이 분포한다.",hint:"ㅇㄷㄹ",hint_b:"에는 키가 크고 작은 나무들과 다양한 식물들이 분포한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "에베레스트산", word_q: "에베레스트산", mean: "높이가 약 8,848m에 달하는 세계에서 가장 높은 산", example_f:"이 산악회 회원 중에는",example_b:"을 오른 사람이 있다.",hint:"ㅇㅂㄹㅅㅌㅅ",hint_b:"을/를 오른 사람이 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "초원", word_q: "초원", mean: "짧은 풀이 자라는 넓은 들판", example_f:"몽골의 초원",example_b:"에서 양들이 풀을 뜯고 있다.",hint:"ㅊㅇ",hint_b:"에서 양들이 풀을 뜯고 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "게르", word_q: "게르", mean: "몽골인들의 이동식 천막집", example_f:"",example_b:"는 큰 천과 뼈대를 이용해 만들기 때문에 텐트처럼 간단히 설치하고 해체할 수 있다.",hint:"ㄱㄹ",hint_b:"은/는 큰 천과 뼈대를 이용해 만들기 때문에 텐트처럼 간단히 설치하고 해체할 수 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "고상 가옥", word_q: "고상 가옥", mean: "주로 열대 기후 지역에서 습기와 해충을 피하기 위해 기둥을 높이 세우고 그 위에 집을 지은 것", example_f:"",example_b:"은 가옥이 지면으로부터 떨어져 있어, 땅의 열기와 습기를 피할 수 있다.",hint:"ㄱㅅ ㄱㅇ",hint_b:"은/는 가옥이 지면으로부터 떨어져 있어, 땅의 열기와 습기를 피할 수 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "보편 종교", word_q: "보편 종교", mean: "국경과 민족을 초월하여 세계 여러 지역에 널리 퍼져 있는 종교", example_f:"",example_b:"에는 크리스트교, 이슬람교, 불교가 있다.",hint:"ㅂㅍ ㅈㄱ",hint_b:"에는 크리스트교, 이슬람교, 불교가 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "민족 종교", word_q: "민족 종교", mean: "특정 민족에게 태생적으로 부여되는 종교로, 다른 민족에게 포교를 적극적으로 시도하지 않는 종교", example_f:"",example_b:"로는 힌두교와 유대교 등이 있다.",hint:"ㅁㅈ ㅈㄱ",hint_b:"(으)로는 힌두교와 유대교 등이 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "불교", word_q: "불교", mean: "부처의 가르침을 따르며 수행하는 종교", example_f:"",example_b:" 신자인 내 친구는 절에 다닌다.",hint:"ㅂㄱ",hint_b:"신자인 내 친구는 절에 다닌다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "유대교", word_q: "유대교", mean: "유대인의 민족 종교로, 유일신인 야훼를 믿는 종교", example_f:"우리 회사의 유대교 신자들은",example_b:"의 성지인 예루살렘에 방문하고자 출발하였다.",hint:"ㅇㄷㄱ",hint_b:"의 성지인 예루살렘에 방문하고자 출발하였다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "이슬람교", word_q: "이슬람교", mean: "무함마드가 창시하였으며, 알라의 가르침을 따르는 종교", example_f:"",example_b:" 신자들은 성지 순례, 금식 기간 준수 등의 규칙을 지켜야 한다.",hint:"ㅇㅅㄹㄱ",hint_b:"신자들은 성지 순례, 금식 기간 준수 등의 규칙을 지켜야 한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "크리스트교", word_q: "크리스트교", mean: "신분과 민족을 초월한 사랑을 중시하며, 예수 그리스도의 가르침을 따르는 종교", example_f:"",example_b:" 신자들은 주로 일요일에 예배를 한다.",hint:"ㅋㄹㅅㅌㄱ",hint_b:"신자들은 주로 일요일에 예배를 한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "힌두교", word_q: "힌두교", mean: "인도의 민족 종교로, 선행과 고행을 통한 수련을 중시하며 많은 신을 믿는 종교", example_f:"",example_b:" 신자들이 사원에서 고행을 하고 있었다.",hint:"ㅎㄷㄱ",hint_b:"신자들이 사원에서 고행을 하고 있었다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "갠지스강", word_q: "갠지스강", mean: "인도 북부를 흐르는 강으로, 힌두교 신자들이 성스럽게 여기는 강", example_f:"힌두교 신자들은",example_b:"에 몸을 담그면 몸 안의 죄를 씻겨 준다고 믿는다.",hint:"ㄱㅈㅅㄱ",hint_b:"에 몸을 담그면 몸 안의 죄를 씻겨 준다고 믿는다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "모스크", word_q: "모스크", mean: "이슬람교 신자들이 예배하는 건물", example_f:"셰이크 자이드",example_b:"는 이슬람교 사원이자 아름다운 건축물로 알려져 있다.",hint:"ㅁㅅㅋ",hint_b:"은/는 이슬람교 사원이자 아름다운 건축물로 알려져 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "문화 상대주의", word_q: "문화 상대주의", mean: "문화의 우열을 평가하지 않고, 그 사회의 입장에서 문화를 이해하려는 태도", example_f:"우리는",example_b:"의 관점에서 세계의 다양한 종교와 문화를 존중해야 한다.",hint:"ㅁㅎ ㅅㄷㅈㅇ",hint_b:"의 관점에서 세계의 다양한 종교와 문화를 존중해야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "인구 밀도", word_q: "인구 밀도", mean: "일정 지역의 인구를 해당 지역의 면적으로 나눈 수치로, 인구 밀도를 통해 지역 간 인구 분포 차이를 파악할 수 있음.", example_f:"북위 20°~40°의 온화한 기후가 나타나는 지역은",example_b:"가 높다.",hint:"ㅇㄱ ㅁㄷ",hint_b:"이/가 높다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "인구", word_q: "인구", mean: "일정한 지역에 사는 사람의 수", example_f:"2022년 기준으로 세계",example_b:"의 약 60%는 아시아에 살고 있다.",hint:"ㅇㄱ",hint_b:"의 약 60%는 아시아에 살고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "기대 수명", word_q: "기대 수명", mean: "사람이 태어났을 때 앞으로 생존할 것으로 기대되는 평균 연수", example_f:"생활 수준의 향상과 의학 기술의 발달로 많은 국가에서는",example_b:"이 높아지고 있다.",hint:"ㄱㄷ ㅅㅁ",hint_b:"이/가 높아지고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "인구 분포", word_q: "인구 분포", mean: "사람들이 어디에 얼마나 모여 살고 있는지 나타낸 것", example_f:"",example_b:"를 살펴보면 어디에 많은 사람이 살고 있는지 알 수 있다.",hint:"ㅇㄱ ㅂㅍ",hint_b:"을/를 살펴보면 어디에 많은 사람이 살고 있는지 알 수 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "합계 출산율", word_q: "합계 출산율", mean: "한 여성이 가임 기간(15~49세)에 낳을 것으로 기대되는 평균 출생아 수로, 인구 규모를 유지하기 위한 합계 출산율은 약 2.1명임.", example_f:"필리핀은",example_b:"이 높게 나타나 인구가 빠르게 증가하고 있다.",hint:"ㅎㄱ ㅊㅅㅇ",hint_b:"이/가 높게 나타나 인구가 빠르게 증가하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "저출산", word_q: "저출산", mean: "태어나는 아이의 수가 줄어드는 현상", example_f:"우리나라는 태어나는 아이의 수가 적어",example_b:" 국가 중 하나이다.",hint:"ㅈㅊㅅ",hint_b:"국가 중 하나이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "고령화", word_q: "고령화", mean: "전체 인구에서 65세 이상의 노인 인구가 차지하는 비율이 높아지는 현상", example_f:"",example_b:"가 진행되어 노동력 부족, 노인 부양을 둘러싼 세대 간 갈등이 나타나기도 한다.",hint:"ㄱㄹㅎ",hint_b:"이/가 진행되어 노동력 부족, 노인 부양을 둘러싼 세대 간 갈등이 나타나기도 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "인구 구조", word_q: "인구 구조", mean: "인구 집단의 연령별, 산업별, 성별 인구 구성 상태", example_f:"",example_b:"는 지역별로 다양하게 나타난다.",hint:"ㅇㄱ ㄱㅈ",hint_b:"은/는 지역별로 다양하게 나타난다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "인구 피라미드", word_q: "인구 피라미드", mean: "한 국가나 지역의 인구 구성을 성별·연령별로 구분하여 나타낸 그래프", example_f:"",example_b:"를 보면 그 지역의 성별·연령별 인구 구조를 확인할 수 있다.",hint:"ㅇㄱ ㅍㄹㅁㄷ",hint_b:"을/를 보면 그 지역의 성별·연령별 인구 구조를 확인할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "천연자원", word_q: "천연자원", mean: "인간 생활에 이용할 수 있는 자연물", example_f:"아시아는",example_b:"이 풍부한 대륙이다.",hint:"ㅊㅇㅈㅇ",hint_b:"이/가 풍부한 대륙이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "팜유", word_q: "팜유", mean: "기름야자의 열매에서 뽑아내는 기름으로, 다양한 공업의 원료로도 쓰임.", example_f:"우리나라에서는 라면 등의 가공식품 생산에",example_b:"를 사용하고 있다.",hint:"ㅍㅇ",hint_b:"을/를 사용하고 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "제조업", word_q: "제조업", mean: "원료를 가공하여 제품을 생산하는 산업", example_f:"우리나라는 1960년대에는 식료품과 옷감을 만드는 공업이 발달하였고 1970-1980년대에는 기계, 조선, 자동차 등을 생산하는",example_b:"이 발달하였다.",hint:"ㅈㅈㅇ",hint_b:"이/가 발달하였다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "석유", word_q: "석유", mean: "땅속에서 얻은 기름으로, 다양한 공업에 이용됨.", example_f:"",example_b:"는 세계에서 가장 많이 소비하는 에너지 자원 중 하나이다.",hint:"ㅅㅇ",hint_b:"은/는 세계에서 가장 많이 소비하는 에너지 자원 중 하나이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "천연가스", word_q: "천연가스", mean: "기체 상태로 매장되어 있는 에너지 자원", example_f:"서남아시아 지역은 석유와",example_b:"가 풍부하게 매장되어 있다.",hint:"ㅊㅇㄱㅅ",hint_b:"이/가 풍부하게 매장되어 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "서비스업", word_q: "서비스업", mean: "사람들의 생활을 편리하게 해 주는 산업", example_f:"아시아의 여러 국가는 부가 가치가 높은",example_b:" 육성에 힘쓰고 있다.",hint:"ㅅㅂㅅㅇ",hint_b:"육성에 힘쓰고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "첨단 산업", word_q: "첨단 산업", mean: "부가 가치가 높으며, 고도의 지식과 기술을 필요로 하는 산업", example_f:"정보 통신 기술 산업, 우주 산업, 로봇 산업 등을 포함하는",example_b:"은 부가 가치가 높다.",hint:"ㅊㄷ ㅅㅇ",hint_b:"은/는 부가 가치가 높다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "석유 자본", word_q: "석유 자본", mean: "석유를 수출해 얻은 자본", example_f:"아랍 에미리트는",example_b:"을 바탕으로 고층 빌딩, 항구, 공항 등을 건설하였다.",hint:"ㅅㅇ ㅈㅂ",hint_b:"을/를 바탕으로 고층 빌딩, 항구, 공항 등을 건설하였다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "자유 무역 협정(FTA)", word_q: "자유 무역 협정(FTA)", mean: "국가 간 물건이나 서비스의 이동을 자유롭게 하기 위해서 세금, 법, 제도 등의 무역 장벽을 줄이거나 없애기로 한 약속", example_f:"우리 정부는",example_b:"체결을 통해 여러 국가와 경제적 협력을 강화하고 있다.",hint:"ㅈㅇ ㅁㅇ ㅎㅈ(FTA)",hint_b:"체결을 통해 여러 국가와 경제적 협력을 강화하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:true },
        { word: "문화 산업", word_q: "문화 산업", mean: "문화 상품을 제작하거나 판매하는 산업으로, 영화, 음악, 만화, 공연 등이 해당됨.", example_f:"",example_b:"이 성장하면서 우리나라 애니메이션의 수출도 증가하였다.",hint:"ㅁㅎ ㅅㅇ",hint_b:"이/가 성장하면서 우리나라 애니메이션의 수출도 증가하였다.", imageBool: false ,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 3단원
      list: [
        { word: "알프스산맥", word_q: "알프스산맥", mean: "유럽 남부의 해발 고도가 높은 산맥으로, 스위스, 프랑스, 이탈리아, 오스트리아에 걸쳐 있음.", example_f:" 유럽의",example_b:"에서 스키를 타는 것은 내 친구의 오랜 꿈이다.",hint:"ㅇㄹㅍㅅㅁ",hint_b:"에서 스키를 타는 것은 내 친구의 오랜 꿈이다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "유럽", word_q: "유럽", mean: "동쪽으로는 아시아, 서쪽으로는 대서양, 남쪽으로는 지중해와 접하는 대륙", example_f:"",example_b:"에는 서로 다른 특징을 지닌 다양한 국가가 있다.",hint:"ㅇㄹ",hint_b:"에는 서로 다른 특징을 지닌 다양한 국가가 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "지중해", word_q: "지중해", mean: "아시아, 유럽, 아프리카 세 대륙에 둘러싸인 바다", example_f:" 에스파냐, 이탈리아 등의 국가는",example_b:"와 접해 있으며 관광 산업이 발달하였다.",hint:"ㅈㅈㅎ",hint_b:"와 접해 있으며 관광 산업이 발달하였다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "랜드마크", word_q: "랜드마크", mean: "어떤 지역을 대표하는 사물로, 주위의 경관 중에서 두드러지게 눈에 띄는 것", example_f:" 높이 약 320m의 철탑인 에펠 탑은 프랑스 파리의",example_b:"이다.",hint:"ㄹㄷㅁㅋ",hint_b:"이다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "난류", word_q: "난류", mean: "따뜻한 바닷물의 흐름", example_f:" 이 바다에는",example_b:"가 흘러 기후가 온화하다.",hint:"ㄴㄹ",hint_b:"이/가 흘러 기후가 온화하다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "편서풍", word_q: "편서풍", mean: "위도 30°에서 60° 사이에 연중 서쪽에서 동쪽으로 부는 바람", example_f:"",example_b:"을 타고 공기 중의 오염 물질이 이동하기도 한다.",hint:"ㅍㅅㅍ",hint_b:"을/를 타고 공기 중의 오염 물질이 이동하기도 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "서안 해양성 기후", word_q: "서안 해양성 기후", mean: "온대 기후에 속하며, 일 년 내내 습윤하며 연교차가 작은 기후", example_f:"",example_b:" 지역은 흐리거나 비가 내리는 날이 많다.",hint:"ㅅㅇ ㅎㅇㅅ ㄱㅎ",hint_b:"지역은 흐리거나 비가 내리는 날이 많다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "낙농업", word_q: "낙농업", mean: "젖소를 사육하여 우유와 유제품을 생산하는 산업", example_f:" 이 지역은",example_b:"이 활발하게 이루어져 우유, 치즈 등이 유명하다.",hint:"ㄴㄴㅇ",hint_b:"이/가 활발하게 이루어져 우유, 치즈 등이 유명하다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "혼합 농업", word_q: "혼합 농업", mean: "가축 사육과 곡물 재배를 함께 하는 농업", example_f:" 우리 지역은",example_b:"을 하고 있어, 밀 농사도 짓고 소도 키운다.",hint:"ㅎㅇ ㄴㅇ",hint_b:"을/를 하고 있어, 밀 농사도 짓고 소도 키운다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "라인강", word_q: "라인강", mean: "알프스산맥에서 시작하여 북해로 흘러드는 강으로, 오스트리아, 독일, 프랑스 등을 거쳐 흐르는 강", example_f:"",example_b:"을 따라가다 보면 유럽의 많은 도시를 만날 수 있다.",hint:"ㄹㅇㄱ",hint_b:"을/를 따라가다 보면 유럽의 많은 도시를 만날 수 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "스칸디나비아산맥", word_q: "스칸디나비아산맥", mean: "북부 유럽에 남북으로 뻗어 있는 산맥", example_f:"",example_b:"의 아름다운 경관을 보러 많은 관광객이 노르웨이를 방문한다.",hint:"ㅅㅋㄷㄴㅂㅇㅅㅁ",hint_b:"의 아름다운 경관을 보러 많은 관광객이 노르웨이를 방문한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "지중해성 기후", word_q: "지중해성 기후", mean: "온대 기후에 속하며, 여름에 고온 건조하며 겨울에 온난 습윤한 기후", example_f:" 이탈리아는",example_b:"가 나타나, 여름에 비가 적게 내려 맑은 날이 많다.",hint:"ㅈㅈㅎㅅ ㄱㅎ",hint_b:"이/가 나타나, 여름에 비가 적게 내려 맑은 날이 많다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "수목 농업", word_q: "수목 농업", mean: "여름에 고온 건조한 기후에 잘 견디는 올리브, 오렌지, 코르크 등을 재배하는 농업", example_f:" 지중해성 기후 지역에서는",example_b:"이 발달해 오렌지, 레몬 등의 생산량이 많다.",hint:"ㅅㅁ ㄴㅇ",hint_b:"이/가 발달해 오렌지, 레몬 등의 생산량이 많다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "산업 클러스터", word_q: "산업 클러스터", mean: "서로 관련 있는 기업과 연구소, 대학, 정부 기관 등이 가까이 위치하여 긴밀한 협력이 가능한 지역", example_f:" 스웨덴의 시스타 사이언스 시티는 유럽의 대표적인 첨단 산업 도시로, 이 도시를 중심으로",example_b:"가 발달하였다.",hint:"ㅅㅇ ㅋㄹㅅㅌ",hint_b:"이/가 발달하였다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "세계 도시", word_q: "세계 도시", mean: "국가의 경계를 넘어 세계의 중심지 역할을 수행하는 도시", example_f:" 영국의 런던은 기업의 본사나 금융 기관 등이 모여 있어, 세계의 중심 도시 역할을 하는",example_b:"이다.",hint:"ㅅㄱ ㄷㅅ",hint_b:"이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "산업 혁명", word_q: "산업 혁명", mean: "18세기 후반 기계 발명 등의 기술 혁신으로 생산력이 크게 증가하면서 나타난 사회·경제적 변화", example_f:" 18세기 후반",example_b:"은 자본주의의 발달과 경제 성장의 계기가 되었지만, 각종 사회문제를 낳기도 했다.",hint:"ㅅㅇ ㅎㅁ",hint_b:"은/는 자본주의의 발달과 경제 성장의 계기가 되었지만, 각종 사회문제를 낳기도 했다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "도시 재생", word_q: "도시 재생", mean: "인구와 기능이 집중하여 도시 문제가 발생할 경우, 도시 환경을 개선하기 위해 정책적인 노력을 하는 것", example_f:" 에스파냐의 빌바오는 쇠퇴하던 공업 도시였으나,",example_b:" 사업을 통해 문화 도시로 변모하였다.",hint:"ㄷㅅ ㅈㅅ",hint_b:"사업을 통해 문화 도시로 변모하였다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "탄소 중립", word_q: "탄소 중립", mean: "이산화 탄소를 배출한 만큼 다시 흡수해, 실질적인 이산화 탄소 배출량을 '0'으로 만드는 일", example_f:" 우리 지역은",example_b:"을 실천하기 위해 자전거 이용을 장려하고 있다.",hint:"ㅌㅅ ㅈㄹ",hint_b:"을/를 실천하기 위해 자전거 이용을 장려하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "재생 에너지", word_q: "재생 에너지", mean: "화석 연료와 달리 태양광, 풍력, 조력 에너지처럼 고갈되지 않고 지속해서 사용할 수 있는 에너지", example_f:" 정부와 국제 사회는 해양 정화 활동을 하고, 기후변화를 완화하기 위해",example_b:"의 이용 비중을 늘려야 한다.",hint:"ㅈㅅ ㅇㄴㅈ",hint_b:"의 이용 비중을 늘려야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "온실 기체", word_q: "온실 기체", mean: "지구에서 우주로 나가려는 열에너지를 흡수하여 지구의 기온을 높이는 기체를 통틀어 이르는 말", example_f:" 자동차 대신 자전거를 이용하면",example_b:"배출량을 줄일 수 있다.",hint:"ㅇㅅ ㄱㅊ",hint_b:"배출량을 줄일 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "친환경 도시", word_q: "친환경 도시", mean: "사람과 자연이 조화롭게 공존할 수 있는 도시", example_f:" 덴마크의 코펜하겐, 스웨덴의 말뫼 등은 탄소 중립을 실천하는",example_b:"이다.",hint:"ㅊㅎㄱ ㄷㅅ",hint_b:"이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "유럽연합(EU)", word_q: "유럽연합(EU)", mean: "유럽의 여러 국가들이 정치·경제적 통합을 실현하기 위해 결성한 기구", example_f:" 유럽의 통합을 실현하기 위해 유럽의 여러 국가들은",example_b:"을 결성하였다.",hint:"ㅇㄹㅇㅎ(EU)",hint_b:"을/를 결성하였다.", imageBool: true  ,lineBreak:0,abbreviastion:true},
        { word: "유로화", word_q: "유로화", mean: "유럽연합 가입국들이 사용하는 화폐", example_f:" 유럽의 여러 국가는",example_b:"를 단일 화폐로 사용한다.",hint:"ㅇㄹㅎ",hint_b:"을/를 단일 화폐로 사용한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "에라스뮈스 프로그램", word_q: "에라스뮈스 프로그램", mean: "유럽연합에 속한 국가의 대학 간 교환 학생 프로그램", example_f:"",example_b:"에 참여하는 유럽 학생들은 학문 교류를 통해 견문을 넓힐 수 있다.",hint:"ㅇㄹㅅㅁㅅ ㅍㄹㄱㄹ",hint_b:"에 참여하는 유럽 학생들은 학문 교류를 통해 견문을 넓힐 수 있다.", imageBool: false ,lineBreak:5,abbreviastion:false },
        { word: "관세", word_q: "관세", mean: "국내에 반입하거나 국내에서 소비 또는 사용하는 외국 물품에 대해서 부과·징수하는 세금", example_f:" 유럽연합 회원국끼리는",example_b:"없이 물건을 수입할 수 있어, 상대적으로 저렴한 가격에 다양한 국가의 물건을 구입할 수 있다.",hint:"ㄱㅅ",hint_b:"없이 물건을 수입할 수 있어, 상대적으로 저렴한 가격에 다양한 국가의 물건을 구입할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "난민", word_q: "난민", mean: "정치적 박해나 전쟁을 피해 다른 지역이나 국가로 탈출하는 사람", example_f:" 내전을 피해 수많은",example_b:"이 피난길에 올랐다.",hint:"ㄴㅁ",hint_b:"이/가 피난길에 올랐다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "파다니아", word_q: "파다니아", mean: "밀라노, 베네치아, 볼로냐 등의 도시를 포함하는 이탈리아 북부 지역으로, 남부 지역에 비해 경제 수준이 높음.", example_f:" 이탈리아의",example_b:"지역에서는 분리·독립 움직임이 나타난다.",hint:"ㅍㄷㄴㅇ",hint_b:"지역에서는 분리·독립 움직임이 나타난다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "카탈루냐", word_q: "카탈루냐", mean: "에스파냐 동북부에 있는 지역으로, 경제 발전 수준이 높음.", example_f:" 에스파냐의",example_b:"는 독자적인 문화를 유지하고 있는 지역이다.",hint:"ㅋㅌㄹㄴ",hint_b:"은/는 독자적인 문화를 유지하고 있는 지역이다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "플랑드르", word_q: "플랑드르", mean: "벨기에 동북부에 있는 지역으로, 네덜란드어를 사용하며 경제 발전 수준이 높음.", example_f:" 네덜란드어를 쓰는 북부",example_b:"지역과 프랑스어를 쓰는 남부 왈롱 지역 사이에는 갈등이 존재한다.",hint:"ㅍㄹㄷㄹ",hint_b:"지역과 프랑스어를 쓰는 남부 왈롱 지역 사이에는 갈등이 존재한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "브렉시트", word_q: "브렉시트", mean: "영국(Britain)의 'Br', 탈출(Exit)의 'exit'가 합쳐진 단어", example_f:"",example_b:" 이후 영국에서는 유럽의 다른 국가와 자유로운 무역이 어려워지는 등의 변화가 생겼다.",hint:"ㅂㄹㅅㅌ",hint_b:"이후 영국에서는 유럽의 다른 국가와 자유로운 무역이 어려워지는 등의 변화가 생겼다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "킬트", word_q: "킬트", mean: "스코틀랜드의 전통 의상으로, 남성용 체크무늬 치마", example_f:"",example_b:"를 입은 스코틀랜드 남성이 지나가고 있다.",hint:"ㅋㅌ",hint_b:"을/를 입은 스코틀랜드 남성이 지나가고 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
      ],
    },
    {
      // 사회 1권 4단원
      list: [
        { word: "빅토리아호", word_q: "빅토리아호", mean: "아프리카에서 가장 큰 호수로, 케냐, 우간다, 탄자니아에 걸쳐 있음.", example_f:"아프리카에서 가장 큰",example_b:"는 나일강이 시작되는 곳이기도 하다.",hint:"ㅂㅌㄹㅇㅎ",hint_b:"은/는 나일강이 시작되는 곳이기도 하다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "사하라 사막", word_q: "사하라 사막", mean: "아프리카 북부의 사막으로, 세계에서 가장 넓은 사막", example_f:"",example_b:"은 비가 거의 오지 않고, 낮과 밤의 기온 차가 크다.",hint:"ㅅㅎㄹ ㅅㅁ",hint_b:"은/는 비가 거의 오지 않고, 낮과 밤의 기온 차가 크다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "아프리카", word_q: "아프리카", mean: "북쪽으로는 유럽, 서쪽으로는 대서양, 동쪽은 인도양에 접하는 대륙", example_f:"",example_b:"는 다양한 지하자원이 매장되어 있고, 인구가 많아 지역 잠재력을 지닌 대륙이다.",hint:"ㅇㅍㄹㅋ",hint_b:"은/는 다양한 지하자원이 매장되어 있고, 인구가 많아 지역 잠재력을 지닌 대륙이다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "킬리만자로산", word_q: "킬리만자로산", mean: "해발 고도 약 5,895m에 이르는 아프리카에서 가장 높은 산", example_f:"아프리카 동부에는",example_b:"과 같은 높은 화산이 발달해 있다.",hint:"ㅋㄹㅁㅈㄹㅅ",hint_b:"과 같은 높은 화산이 발달해 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "고원", word_q: "고원", mean: "해발 고도가 600m 이상이며, 상대적으로 기복이 작은 평평한 땅", example_f:"이 산을 오르면 넓은",example_b:"이 펼쳐진다.",hint:"ㄱㅇ",hint_b:"이/가 펼쳐진다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "레저 스포츠", word_q: "레저 스포츠", mean: "여가 시간에 즐기는 스포츠 활동", example_f:"다양한",example_b:"를 즐길 때는 늘 안전에 유의해야 한다.",hint:"ㄹㅈ ㅅㅍㅊ",hint_b:"을/를 즐길 때는 늘 안전에 유의해야 한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "나일강", word_q: "나일강", mean: "사하라 사막을 통과하여 흐르는 세계에서 가장 긴 하천", example_f:"",example_b:" 유역의 물을 구하기 좋은 곳에서는 고대 문명이 번성하기도 하였다.",hint:"ㄴㅇㄱ",hint_b:"유역의 물을 구하기 좋은 곳에서는 고대 문명이 번성하기도 하였다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "판의 경계", word_q: "판의 경계", mean: "지구의 표면을 구성하는 판들이 부딪치거나 멀어지는 곳으로, 지진이나 화산 활동이 자주 일어남.", example_f:"",example_b:"와 거리가 가까운 곳에는 아틀라스산맥과 같은 높고 험한 산맥이 분포하기도 한다.",hint:"ㅍㅇ ㄱㄱ",hint_b:"와 거리가 가까운 곳에는 아틀라스산맥과 같은 높고 험한 산맥이 분포하기도 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "지구대", word_q: "지구대", mean: "양쪽에서 잡아당기는 힘이 발생하여, 판이 갈라지고 그 사이는 내려앉은 지형", example_f:"동아프리카",example_b:"는 판이 갈라지고 있는 대표적인 지역이다.",hint:"ㅈㄱㄷ",hint_b:"은/는 판이 갈라지고 있는 대표적인 지역이다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "아틀라스산맥", word_q: "아틀라스산맥", mean: "아프리카 북서부에 위치한 높고 험한 산맥", example_f:"겨울에는",example_b:"정상부에 스키장이 열린다.",hint:"ㅇㅌㄹㅅㅅㅁ",hint_b:"정상부에 스키장이 열린다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "사바나 기후", word_q: "사바나 기후", mean: "다른 열대 기후 지역보다 연 강수량이 적고, 우기와 건기의 구분이 비교적 뚜렷한 기후", example_f:"",example_b:"지역의 초원은 야생 동물의 천국이라 불린다.",hint:"ㅅㅂㄴ ㄱㅎ",hint_b:"지역의 초원은 야생 동물의 천국이라 불린다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "사파리 관광", word_q: "사파리 관광", mean: "자동차를 타고 다니며 야생 동물을 관찰하는 관광", example_f:"이 지역에는 다양한 야생 동물이 살고 있어,",example_b:"을 하려는 사람들이 많이 방문한다.",hint:"ㅅㅍㄹ ㄱㄱ",hint_b:"을/를 하려는 사람들이 많이 방문한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "카사바", word_q: "카사바", mean: "열대 기후 지역에서 많이 재배하는 작물로, 고구마와 비슷하게 생김.", example_f:"적도 주변의 열대 기후 지역에서는",example_b:"등의 작물을 많이 재배한다.",hint:"ㅋㅅㅂ",hint_b:"등의 작물을 많이 재배한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "타진", word_q: "타진", mean: "원뿔 모양의 뚜껑이 달린 그릇을 이용하여 만든 모로코의 전통 요리", example_f:"모로코에서",example_b:"을 주문해 먹어본 것이 기억에 남는다.",hint:"ㅌㅈ",hint_b:"을/를 주문해 먹어본 것이 기억에 남는다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "구매력", word_q: "구매력", mean: "개인이나 단체가 어떤 물건이나 서비스를 살 수 있는 능력", example_f:"우리 회사는",example_b:"이 높은 소비자를 위한 고급 상품을 출시했다.",hint:"ㄱㅁㄹ",hint_b:"이/가 높은 소비자를 위한 고급 상품을 출시했다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "중위 연령", word_q: "중위 연령", mean: "한 국가의 인구를 일렬로 세웠을 때, 한가운데 서 있는 사람의 나이", example_f:"우리나라의",example_b:"은 2022년 기준 44.9세이다.",hint:"ㅈㅇ ㅇㄹ",hint_b:"은/는 2022년 기준 44.9세이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "국내 총생산(GDP)", word_q: "국내 총생산(GDP)", mean: "일정 기간 한 국가 안에서 새롭게 생산한 모든 최종 생산물의 가치를 합한 것", example_f:"이 국가는 빠르게 경제 성장을 이루었고",example_b:"이 10% 이상 성장했다.",hint:"ㄱㄴ ㅊㅅㅅ(GDP)",hint_b:"이/가 10% 이상 성장했다.", imageBool: false ,lineBreak:0,abbreviastion:true },
        { word: "상품 작물", word_q: "상품 작물", mean: "시장에 내다 팔기 위하여 재배하는 농작물", example_f:"아프리카는 커피, 카카오 등",example_b:" 재배가 활발하다.",hint:"ㅅㅍ ㅈㅁ",hint_b:"재배가 활발하다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "지속가능한 발전", word_q: "지속가능한 발전", mean: "지구촌 사람들이 현재뿐만 아니라 미래 세대의 환경과 발전을 위해 책임감 있게 행동할 때 다가올 미래", example_f:"우리 기업은",example_b:"을 위해 재생 용지를 이용한 제품을 만들었다.",hint:"ㅈㅅㄱㄴㅎ ㅂㅈ",hint_b:"을/를 위해 재생 용지를 이용한 제품을 만들었다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "지속가능 발전 목표", word_q: "지속가능 발전 목표", mean: "국제 연합(UN)이 지속가능한 미래를 위해 지구촌 사람들이 실천해야 한다고 발표한 17개의 목표", example_f:"",example_b:" 중 생활 속에서 실천할 수 있는 목표를 골라 보았다.",hint:"ㅈㅅㄱㄴ ㅂㅈ ㅁㅍ",hint_b:"중 생활 속에서 실천할 수 있는 목표를 골라 보았다.", imageBool: true  ,lineBreak:4,abbreviastion:false},
        { word: "아프리카 연합(AU)", word_q: "아프리카 연합(AU)", mean: "아프리카 국가들의 단결과 협력을 위해 2002년 출범한 국제기구", example_f:"지난주",example_b:"회원국들의 정기 회의가 개최되었다.",hint:"ㅇㅍㄹㅋ ㅇㅎ(AU)",hint_b:"회원국들의 정기 회의가 개최되었다.", imageBool: true  ,lineBreak:4,abbreviastion:true},
        { word: "아프리카 대륙 자유 무역 지대(AfCFTA)", word_q: "아프리카 대륙 자유 무역 지대(AfCFTA)", mean: "아프리카 연합의 주력 프로젝트로 지난 2019년 5월 30일 공식적인 출범을 선언한 신생 자유 무역 지대", example_f:"",example_b:"에서 무역이 활발히 시행되어 여러 국가의 경제가 성장하기를 기대한다.",hint:"ㅇㅍㄹㅋ ㄷㄹ ㅈㅇ ㅁㅇ ㅈㄷ(AfCFTA)",hint_b:"에서 무역이 활발히 시행되어 여러 국가의 경제가 성장하기를 기대한다.", imageBool: false ,lineBreak:7,abbreviastion:true },
        { word: "강원 동계 청소년 올림픽", word_q: "강원 동계 청소년 올림픽", mean: "2024년 대한민국 강원특별자치도에서 개최되었으며, 아시아에서 처음 개최된 동계 청소년 올림픽", example_f:"",example_b:"의 아이스 하키 경기를 관람하고 왔다.",hint:"ㄱㅇ ㄷㄱ ㅊㅅㄴ ㅇㅍㄹ",hint_b:"의 아이스 하키 경기를 관람하고 왔다.", imageBool: false ,lineBreak:5,abbreviastion:false },
        { word: "공중 풍력 발전소", word_q: "공중 풍력 발전소", mean: "고도가 높을수록 바람이 강하게 부는 현상을 이용하여, 공중에서 바람의 힘을 이용해 전력을 생산하는 시설", example_f:"아프리카의 섬나라 모리셔스는 커다란 연을 띄워 전기를 생산하는",example_b:"를 설치했다.",hint:"ㄱㅈ ㅍㄹ ㅂㅈㅅ",hint_b:"을/를 설치했다.", imageBool: true  ,lineBreak:5,abbreviastion:false},
      ],
    },
    {
     // 사회 1권 5단원
      list: [
        { word: "지협", word_q: "지협", mean: "두 개의 육지를 연결하는 좁고 잘록한 땅", example_f:"파나마",example_b:"을 경계로 북아메리카와 남아메리카로 구분할 수 있다.",hint:"ㅈㅎ",hint_b:"을/를 경계로 북아메리카와 남아메리카로 구분할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "사탕수수", word_q: "사탕수수", mean: "줄기에 당분이 함유되어 있어 주로 설탕의 원료로 사용되는 작물로 주로 열대 기후 지역에서 재배", example_f:"적도와 가까운 카리브해 일대에는 커피와",example_b:"생산으로 잘 알려진 쿠바와 코스타리카 등이 있다.",hint:"ㅅㅌㅅㅅ",hint_b:"생산으로 잘 알려진 쿠바와 코스타리카 등이 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "고산 도시", word_q: "고산 도시", mean: "해발 2,000m 이상의 높은 고산 지대에 발달한 도시", example_f:"",example_b:"는 적도 부근의 높은 산지에 위치해 연중 온화한 기후가 나타난다.",hint:"ㄱㅅ ㄷㅅ",hint_b:"은/는 적도 부근의 높은 산지에 위치해 연중 온화한 기후가 나타난다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "그레이트플레인스", word_q: "그레이트플레인스", mean: "북아메리카 대륙 중앙에 남북으로 길게 뻗어 있는 고원 모양의 대평원", example_f:"로키산맥과 애팔래치아산맥 사이에는 세계적인 곡창 지대를 이루는",example_b:"가 펼쳐져 있다.",hint:"ㄱㄹㅇㅌㅍㄹㅇㅅ",hint_b:"이/가 펼쳐져 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "안정 지괴", word_q: "안정 지괴", mean: "지각 변동이 발생한 뒤 오랜 시간 심한 변동이 나타나지 않아 안정된 땅덩어리", example_f:"아마존 분지 동남쪽에는",example_b:"로 이루어진 브라질고원이 위치한다.",hint:"ㅇㅈ ㅈㄱ",hint_b:"(으)로 이루어진 브라질고원이 위치한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "아마존강", word_q: "아마존강", mean: "남아메리카 대륙의 북부 평원에 있는 세계에서 가장 넓은 강", example_f:"",example_b:" 유역의 열대림에는 다양한 동물과 식물이 살고있다.",hint:"ㅇㅁㅈㄱ",hint_b:"유역의 열대림에는 다양한 동물과 식물이 살고있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "고산 기후", word_q: "고산 기후", mean: "높은 산지에서 나타나며, 주변의 고도가 낮은 지역보다 기온이 낮은 기후", example_f:"",example_b:"는 살기 좋은 온화한 기온이 나타나, 남아메리카의 적도 부근 고산 지역에서는 아스테카 문명, 잉카 문명이 발달했다.",hint:"ㄱㅅ ㄱㅎ",hint_b:"은/는 살기 좋은 온화한 기온이 나타나, 남아메리카의 적도 부근 고산 지역에서는 아스테카 문명, 잉카 문명이 발달했다.", imageBool: true ,lineBreak:0,abbreviastion:false },
        { word: "히스패닉", word_q: "히스패닉", mean: "에스파냐어를 모국어로 쓰는 라틴 아메리카계(중 · 남부 아메리카)의 이주민과 그 후손", example_f:"북아메리카는 아시아계와",example_b:" 등 일자리를 찾기 위해 여러 대륙과 국가에서 이주해 온 사람들이 공존하고 있다.",hint:"ㅎㅅㅍㄴ",hint_b:"등 일자리를 찾기 위해 여러 대륙과 국가에서 이주해 온 사람들이 공존하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "문화 혼종성", word_q: "문화 혼종성", mean: "서로 다른 문화가 섞여 여러 가지 정체성을 지닌 새로운 문화를 만드는 현상", example_f:"아메리카의 예술 작품, 축제, 음식, 건축 경관 등에서 다양한 문화가 융합된",example_b:"의 사례를 찾아볼 수 있다.",hint:"ㅁㅎ ㅎㅈㅅ",hint_b:"의 사례를 찾아볼 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "재즈", word_q: "재즈", mean: "아프리카의 전통 음악과 미국 남북 전쟁 이후 군악대 연주 기법이 결합해 만들어진 새로운 장르의 음악", example_f:"",example_b:"는 즉흥적이고 자유로운 연주를 바탕으로 다양한 장르와 결합하여 대중 음악으로 발전하였다.",hint:"ㅈㅈ",hint_b:"은/는 즉흥적이고 자유로운 연주를 바탕으로 다양한 장르와 결합하여 대중 음악으로 발전하였다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "이주민", word_q: "이주민", mean: "다른 지역에서 옮겨 오거나 옮겨 가서 사는 사람", example_f:"최근에는 세계화로",example_b:"이 늘어났다",hint:"ㅇㅈㅁ",hint_b:"이/가 늘어났다", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "타코", word_q: "타코", mean: "둥글고 납작한 빵인 토르티야에 살사소스와 고기, 야채를 넣어 먹는 멕시코의 전통 음식", example_f:"",example_b:"는 여러 국가에 전파되면서 여러가지 재료를 넣어 먹는 음식으로 발전하였다.",hint:"ㅌㅋ",hint_b:"은/는 여러 국가에 전파되면서 여러가지 재료를 넣어 먹는 음식으로 발전하였다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "탱고", word_q: "탱고", mean: "에스파냐 이민자들이 추던 춤에 아프리카의 리듬, 원주민들의 전통 음악이 섞여서 만들어진 음악", example_f:"",example_b:"는 여러 가지 악기의 연주에 맞춰 열정적인 추는 춤으로 유네스코 무형 문화유산에 등재되었다.",hint:"ㅌㄱ",hint_b:"은/는 여러 가지 악기의 연주에 맞춰 열정적인 추는 춤으로 유네스코 무형 문화유산에 등재되었다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "초국적 기업", word_q: "초국적 기업", mean: "모기업이 세계 각지에 자회사·지사·합병회사·공장 등의 자산을 확보하고 글로벌하게 생산과 판매 활동을 벌이는 기업", example_f:"교통·통신의 발달로 국가 간 교류가 늘어나면서",example_b:"의 영향력은 점차 확대되고 있다.",hint:"ㅊㄱㅈ ㄱㅇ",hint_b:"의 영향력은 점차 확대되고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "해외 직구", word_q: "해외 직구", mean: "‘해외 직접 구매’의 줄임말로, 인터넷을 통해 국내에 수입되지 않는 상품 등을 해외에서 직접 사들이는 소비 형태", example_f:"",example_b:"는 개인 통관 번호를 부여 받고, 해외에서 물건을 직접 구매할 수 있다.",hint:"ㅎㅇ ㅈㄱ",hint_b:"은/는 개인 통관 번호를 부여 받고, 해외에서 물건을 직접 구매할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "세계 무역 기구(WTO)", word_q: "세계 무역 기구(WTO)", mean: "세계의 교역 증진과 경제 발전을 목적으로 설립된 국제기구", example_f:"",example_b:"의 등장으로 자본, 기술, 서비스의 국제 이동이 활발해졌다.",hint:"ㅅㄱ ㅁㅇ ㄱㄱ(WTO)",hint_b:"의 등장으로 자본, 기술, 서비스의 국제 이동이 활발해졌다.", imageBool: false ,lineBreak:5,abbreviastion:true },
        { word: "공간적 분업", word_q: "공간적 분업", mean: "경영 효율성과 이윤을 높이기 위해 기업 조직의 기능을 서로 다른 국가와 지역에 나누어 배치", example_f:"초국적 기업의 본사는 자본이 풍부하고 인력 확보가 유리한 지역에 위치하고, 생산 공장은 땅값이 낮고 저렴한 노동력이 풍부한 지역에 위치하는",example_b:"이 이뤄진다.",hint:"ㄱㄱㅈ ㅂㅇ",hint_b:"이/가 이뤄진다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "실리콘 밸리", word_q: "실리콘 밸리", mean: "미국 캘리포니아주 샌프란시스코 지역 남부 일대로 실리콘 반도체를 제조하는 업체가 많이 모여 있는 곳이다.", example_f:"",example_b:"에는 초국적 기업의 본사들이 밀집해 있다.",hint:"ㅅㄹㅋ ㅂㄹ",hint_b:"에는 초국적 기업의 본사들이 밀집해 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "사회 기반 시설", word_q: "사회 기반 시설", mean: "사회 유지와 경제발전에 기초가 되는 도로, 교량, 통신, 수도, 전력 등의 공공시설", example_f:"초국적 기업의 관련 시설이 들어서면 지역의",example_b:"이나 편의 시설이 개선되는 등 지역 경제가 활성화된다.",hint:"ㅅㅎ ㄱㅂ ㅅㅅ",hint_b:"(이)나 편의 시설이 개선되는 등 지역 경제가 활성화된다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "장소 마케팅", word_q: "장소 마케팅", mean: "장소 또는 도시 공간의 고유한 특성에 맞는 이미지와 상품을 개발하여 지역 가치를 높이는 홍보 전략", example_f:"우리 도시는",example_b:"을 통해 친환경적인 도시 이미지를 만들어냈다.",hint:"ㅈㅅ ㅁㅋㅌ",hint_b:"을/를 통해 친환경적인 도시 이미지를 만들어냈다.", imageBool: false ,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 6단원
      list: [
        { word: "계획도시", word_q: "계획도시", mean: "중앙 정부 또는 지방 자치 단체의 계획에 의해 재정비되거나 새로 개발되는 지역", example_f:"오스트레일리아의 주요 도시로는 인구가 가장 많은 시드니,",example_b:"인 수도 캔버라 등이 있다.",hint:"ㄱㅎㄷㅅ",hint_b:"인 수도 캔버라 등이 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "그레이트디바이딩 산맥", word_q: "그레이트디바이딩 산맥", mean: "오스트레일리아 동부에 있는 해안을 따라 남북으로 길게 뻗은 산맥", example_f:"오스트레일리아의",example_b:"은 지형의 높낮이가 크지 않고 평탄하다.",hint:"ㄱㄹㅇㅌㄷㅂㅇㄷ ㅅㅁ",hint_b:"은/는 지형의 높낮이가 크지 않고 평탄하다.", imageBool: false ,lineBreak:8,abbreviastion:false },
        { word: "산호초", word_q: "산호초", mean: "산호 군락과 그 분비물인 탄산 칼슘이 쌓여서 만들어진 암초", example_f:"태평양의 작은 섬들은 대부분 화산 활동으로 형성되었거나,",example_b:"로 이루어져 있다.",hint:"ㅅㅎㅊ",hint_b:"(으)로 이루어져 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "지하자원", word_q: "지하자원", mean: "땅속에 묻혀 있는 자원으로 철, 석탄, 석유와 같이 인간 생활에 도움을 주는 광산물", example_f:"오스트레일리아는 석탄, 철광석, 금 등의",example_b:"이 풍부해 이를 전 세계에 수출하고 있다.",hint:"ㅈㅎㅈㅇ",hint_b:"이/가 풍부해 이를 전 세계에 수출하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "간헐천", word_q: "간헐천", mean: "일정한 간격을 두고 뜨거운 물이나 수증기가 나왔다가 멎었다가 하는 온천", example_f:"뉴질랜드의 북섬 로토루아 화산 지대에서는 뜨거운 물이 치솟는",example_b:"을 구경할 수 있다.",hint:"ㄱㅎㅊ",hint_b:"을/를 구경할 수 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "마오리족", word_q: "마오리족", mean: "폴리네시아계의 해양 종족으로, 피부는 엷은 갈색이고 머리는 노란색의 곱슬머리인 뉴질랜드의 원주민", example_f:"뉴질랜드의 원주민인",example_b:"의 춤은 우렁찬 구호에 맞춰 발 구르기, 혀 내밀기, 위협적인 표정 짓기 등의 특징이 나타난다.",hint:"ㅁㅇㄹㅈ",hint_b:"의 춤은 우렁찬 구호에 맞춰 발 구르기, 혀 내밀기, 위협적인 표정 짓기 등의 특징이 나타난다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "제조업", word_q: "제조업", mean: "원료를 가공하여 제품을 생산하는 산업", example_f:"우리나라는 1960년대에는 식료품과 옷감을 만드는 공업이 발달하였고 1970-1980년대에는 기계, 조선, 자동차 등을 생산하는",example_b:"이 발달하였다.",hint:"ㅈㅈㅇ",hint_b:"이/가 발달하였다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "동남아시아 국가 연합(ASEAN)", word_q: "동남아시아 국가 연합(ASEAN)", mean: "1967년에 결성된 동남아시아 지역 내 여러 나라의 경제적, 사회적으로 협력하기 위해 설립된 기구", example_f:"",example_b:"은 인도네시아, 태국, 말레이시아 등 10개국이 가입되어 있다.",hint:"ㄷㄴㅇㅅㅇ ㄱㄱ ㅇㅎ(ASEAN)",hint_b:"은/는 인도네시아, 태국, 말레이시아 등 11개국이 가입되어 있다.", imageBool: false ,lineBreak:5,abbreviastion:true },
        { word: "역내 포괄적 경제 동반자 협정(RCEP)", word_q: "역내 포괄적 경제 동반자 협정(RCEP)", mean: "동남아시아 국가 연합(ASEAN) 10개국과 한국, 중국, 일본, 오스트레일리아, 뉴질랜드까지 총 15개국이 가입한 세계 최대 규모의 다자간 자유 무역 협정", example_f:"",example_b:"은 역내 국가들의 제반 경제 상황을 고려해 단계적이고 점진적인 개방을 기본 개념으로 설정해 협상을 진행했다.",hint:"ㅇㄴ ㅍㄱㅈ ㄱㅈ ㄷㅂㅈ ㅎㅈ(RCEP)",hint_b:"은/는 역내 국가들의 제반 경제 상황을 고려해 단계적이고 점진적인 개방을 기본 개념으로 설정해 협상을 진행했다.", imageBool: false ,lineBreak:6,abbreviastion:true },
        { word: "남획", word_q: "남획", mean: "사냥과 어업 등에서 자원량의 변동에 영향을 미칠 정도로 많이 잡는 일", example_f:"식물성 참치는 태평양 지역의 물고기가",example_b:"되는 것을 막고, 환경 오염으로 중금속이나 미세 플라스틱이 많이 검출되는 참치를 대체하기 위해 만들어졌다.",hint:"ㄴㅎ",hint_b:"되는 것을 막고, 환경 오염으로 중금속이나 미세 플라스틱이 많이 검출되는 참치를 대체하기 위해 만들어졌다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "해양 쓰레기", word_q: "해양 쓰레기", mean: "해양으로 유입, 배출되어 해양을 오염시키고 생태계에 영향을 주는 쓰레기", example_f:"",example_b:"는 바닷물의 흐름에 따라 태평양 전 지역을 이동하면서 섬 국가의 주민들에게 피해를 주기도 한다.",hint:"ㅎㅇ ㅆㄹㄱ",hint_b:"은/는 바닷물의 흐름에 따라 태평양 전 지역을 이동하면서 섬 국가의 주민들에게 피해를 주기도 한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "해수면 상승", word_q: "해수면 상승", mean: "바람, 파도의 작용이나 기후 변화로 해수의 온도가 상승하여 빙하가 녹으면서 해수면이 올라가는 현상", example_f:"태평양의 작은 섬 국가에서는 기후변화에 따른",example_b:"으로 바닷물이 육지로 넘쳐 시설물이 무너지거나, 지하수에 바닷물이 섞여 마실 물이 줄어들고 있다.",hint:"ㅎㅅㅁ ㅅㅅ",hint_b:"(으)로 바닷물이 육지로 넘쳐 시설물이 무너지거나, 지하수에 바닷물이 섞여 마실 물이 줄어들고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "쓰레기 섬", word_q: "쓰레기 섬", mean: "파도의 흐름에 따라 플라스틱 쓰레기들이 모여서 마치 섬처럼 보이는 지대", example_f:"태평양에는 주변 국가들에서 버려진 쓰레기들로 이루어진 거대한",example_b:"이 있다.",hint:"ㅆㄹㄱ ㅅ",hint_b:"이/가 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "기후변화", word_q: "기후변화", mean: "일정 지역에서 오랜 기간에 걸쳐서 기후가 변하는 현상", example_f:"",example_b:"에 따라 생물 종 다양성이 감소하는 등의 피해가 발생하고 있다.",hint:"ㄱㅎㅂㅎ",hint_b:"에 따라 생물 종 다양성이 감소하는 등의 피해가 발생하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "백화 현상", word_q: "백화 현상", mean: "산호의 서식지 내에서 일어나는 수온의 급격한 상승이나 저하로 하얗게 색이 변하여 죽는 현상", example_f:"오스트레일리아 북동부의 대보초에서는 해수 온도의 상승으로 산호가 죽어서 하얗게 변하는",example_b:"이 나타나고 있다.",hint:"ㅂㅎ ㅎㅅ",hint_b:"이/가 나타나고 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "자원 순환", word_q: "자원 순환", mean: "재사용이 가능한 자원을 효율적으로 활용하여 불필요한 자원의 배출을 줄이는 것", example_f:"기업은",example_b:"기술을 개발하고, 제품의 생산과 이동, 폐기 과정에서 환경이 오염되지 않도록 노력해야 한다.",hint:"ㅈㅇ ㅅㅎ",hint_b:"기술을 개발하고, 제품의 생산과 이동, 폐기 과정에서 환경이 오염되지 않도록 노력해야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "재생 에너지", word_q: "재생 에너지", mean: "화석 연료와 달리 태양광, 풍력, 조력 에너지처럼 고갈되지 않고 지속해서 사용할 수 있는 에너지", example_f:"정부와 국제 사회는 해양 정화 활동을 하고, 기후변화를 완화하기 위해",example_b:"의 이용 비중을 늘려야 한다.",hint:"ㅈㅅ ㅇㄴㅈ",hint_b:"의 이용 비중을 늘려야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "파리 협정", word_q: "파리 협정", mean: "파리에서 온실 기체 배출량을 단계적으로 줄이는 내용을 담고 있는 협정", example_f:"",example_b:"에서 세계 195개국은 지구 평균 기온 상승을 1.5℃ 이내로 제한하기로 약속하였다.",hint:"ㅍㄹ ㅎㅈ",hint_b:"에서 세계 195개국은 지구 평균 기온 상승을 1.6℃ 이내로 제한하기로 약속하였다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "분리배출", word_q: "분리 배출", mean: "종이, 플라스틱, 캔, 유리 등의 쓰레기 따위를 종류별로 나누어서 배출하는 것", example_f:"투명 페트병은 내용물을 깨끗하게 비워서 별도의 배출 전용함을 이용해",example_b:"한다.",hint:"ㅂㄹㅂㅊ",hint_b:"한다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "과학 기지", word_q: "과학 기지", mean: "극지방의 기후변화, 극지 생물, 해양 생태계 등을 연구하기 위해 설치한 기지", example_f:"우리나라의",example_b:"는 남극에는 세종 과학 기지와 장보고 과학 기지가, 북극에는 다산 과학 기지가 있다.",hint:"ㄱㅎ ㄱㅈ",hint_b:"은/는 남극에는 세종 과학 기지와 장보고 과학 기지가, 북극에는 다산 과학 기지가 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "북극 항로", word_q: "북극 항로", mean: "기후변화로 북극해의 빙하가 녹으면서 대형 선박이 다닐 수 있는 항로", example_f:"",example_b:"를 이용하면 북태평양을 지나 유럽과 아메리카 동부로 이동하는 거리와 시간을 단축할 수 있다.",hint:"ㅂㄱ ㅎㄹ",hint_b:"을/를 이용하면 북태평양을 지나 유럽과 아메리카 동부로 이동하는 거리와 시간을 단축할 수 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "남극 조약", word_q: "남극 조약", mean: "남극의 평화적 이용, 자유로운 과학·학술 조사, 영유권 주장 금지, 자연 보호 등의 내용을 지키기 위해 맺은 조약", example_f:"남극 대륙은 특정 국가가 소유하지 않은 채 세계의 여러 국가가",example_b:"을 맺어 공동으로 관리하며 과학 연구와 탐사를 진행하고 있다.",hint:"ㄴㄱ ㅈㅇ",hint_b:"을/를 맺어 공동으로 관리하며 과학 연구와 탐사를 진행하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "영유권", word_q: "영유권", mean: "일정한 영토에 대한 해당 국가의 관할권으로 통치할 권리와 영역을 관리 할 권리", example_f:"북극해에는 약 900억 배럴의 석유가 매장되어 있는 것으로 추정되는데, 이를 둘러싸고 북극해 연안 국가들이 서로",example_b:"을 주장하고 있다.",hint:"ㅇㅇㄱ",hint_b:"을/를 주장하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "온실 기체", word_q: "온실 기체", mean: "지구에서 우주로 나가려는 열에너지를 흡수하여 지구의 기온을 높이는 기체를 통틀어 이르는 말", example_f:"자동차 대신 자전거를 이용하면",example_b:"배출량을 줄일 수 있다.",hint:"ㅇㅅ ㄱㅊ",hint_b:"배출량을 줄일 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "원양 어업", word_q: "원양 어업", mean: "근거지로부터 며칠 또는 수십일 걸리는 먼 바다에서 하는 어업", example_f:"태평양은 수산 자원이 풍부해",example_b:"이 발달했다.",hint:"ㅇㅇ ㅇㅇ",hint_b:"이/가 발달했다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
      ],
    },
    {
      // 사회 1권 7단원
      list: [
        { word: "또래 집단", word_q: "또래 집단", mean: "주로 놀이를 중심으로 비슷한 나이의 구성원들이 형성한 집단", example_f:"",example_b:"과 어울리며 놀이를 통해 공동체 생활의 규칙과 규범을 배운다.",hint:"ㄸㄹ ㅈㄷ",hint_b:"과/와 어울리며 놀이를 통해 공동체 생활의 규칙과 규범을 배운다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "대중 매체", word_q: "대중 매체", mean: "신문, 잡지, 텔레비전과 같이 많은 사람에게 대량으로 정보를 전달하는 매체", example_f:"인터넷과 같은",example_b:"에서 다양한 지식과 정보를 얻는다.",hint:"ㄷㅈ ㅁㅊ",hint_b:"에서 다양한 지식과 정보를 얻는다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "사회화", word_q: "사회화", mean: "개인이 자신이 속한 사회의 언어, 규범, 가치관, 행동 양식 등을 배워 나가는 과정", example_f:"개인은",example_b:"를 통해 자신이 속한 사회에 적응한다.",hint:"ㅅㅎㅎ",hint_b:"을/를 통해 자신이 속한 사회에 적응한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "개성", word_q: "개성", mean: "다른 사람이나 개체와 구별되는 고유의 특성", example_f:"개인은 사회화를 통해 자신만의 독특한",example_b:"을 형성한다.",hint:"ㄱㅅ",hint_b:"을/를 형성한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "정체성", word_q: "정체성", mean: "한 개인의 사회화의 결과로 형성되는 자아 인식", example_f:"개인은 사회화를 통해 자아",example_b:"을 형성한다.",hint:"ㅈㅊㅅ",hint_b:"을/를 형성한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "자아 정체성", word_q: "자아 정체성", mean: "다른 사람들과 구별되는 자신의 고유성을 이해하고 자신이 누구인지를 명확하게 알고 있는 것", example_f:"사회화 과정에서 겪은 고유한 경험들은 그 사람만의",example_b:"을 형성한다.",hint:"ㅈㅇ ㅈㅊㅅ",hint_b:"을/를 형성한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "청소년기", word_q: "청소년기", mean: "아동기에서 성인기로 이르는 과도기", example_f:"",example_b:"에는 사회화가 활발하게 이루어진다.",hint:"ㅊㅅㄴㄱ",hint_b:"에는 사회화가 활발하게 이루어진다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "거울 자아", word_q: "거울 자아", mean: "거울에 비친 모습처럼 다른 사람의 눈에 비친 자신의 모습을 상상하고, 이를 바탕으로 만들어 가는 자아에 대한 인식", example_f:"미국의 사회학자 쿨리는",example_b:"라는 개념을 통해 자아 정체성은 다른 사람들의 반응에 영향을 받으며 형성된다고 말했다.",hint:"ㄱㅇ ㅈㅇ",hint_b:"(이)라는 개념을 통해 자아 정체성은 다른 사람들의 반응에 영향을 받으며 형성된다고 말했다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "사회적 지위", word_q: "사회적 지위", mean: "개인이 자신이 속한 사회에서 차지하고 있는 다양한 위치", example_f:"",example_b:"에는 개인의 노력이나 선택과 상관없이 타고난 지위와 노력이나 능력, 선택으로 얻게 되는 지위가 있다.",hint:"ㅅㅎㅈ ㅈㅇ",hint_b:"에는 개인의 노력이나 선택과 상관없이 타고난 지위와 노력이나 능력, 선택으로 얻게 되는 지위가 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "역할", word_q: "역할", mean: "마땅히 해야 한다고 기대되는 행동 양식", example_f:"사회적 지위에 따른",example_b:"을 잘 수행하는 것이 중요하다.",hint:"ㅇㅎ",hint_b:"을/를 잘 수행하는 것이 중요하다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "보상", word_q: "보상", mean: "어떤 일을 잘 해냈을 때 그 대가로 받는 물질이나 칭찬", example_f:"지위에 따른 역할을 훌륭하게 수행하면 사회적 인정이나",example_b:"을 받는다.",hint:"ㅂㅅ",hint_b:"을/를 받는다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "제재", word_q: "제재", mean: "법이나 규정, 관습 따위를 어겼을 때 이를 제한하거나 금지하는 것", example_f:"지위에 따른 역할을 제대로 수행하지 못하면 비난이나",example_b:"를 받게 된다.",hint:"ㅈㅈ",hint_b:"을/를 받게 된다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "역할 갈등", word_q: "역할 갈등", mean: "한 개인이 가진 여러 지위에 따른 역할들이 동시에 요구되면서 역할 간에 충돌이 발생할 때 개인이 겪는 갈등", example_f:"회사원으로서의 역할과 어머니로서의 역할 사이에서",example_b:"을 겪고 있다.",hint:"ㅇㅎ ㄱㄷ",hint_b:"을/를 겪고 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "가족 돌봄 휴가", word_q: "가족 돌봄 휴가", mean: "근로자가 부모, 배우자, 자녀 등 가족의 질병, 사고, 노령으로 그 가족으로 돌보아야 할 때 사용하는 휴가", example_f:"가족 구성원으로서의 역할과 근로자의 역할 사이에서의 역할 갈등에 대응하기 위해",example_b:" 제도를 실시하고 있다.",hint:"ㄱㅈ ㄷㅂ ㅎㄱ",hint_b:"제도를 실시하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "갈등", word_q: "갈등", mean: "개인이나 집단이 서로의 가치관이나 생활 방식을 이해하지 못하거나, 서로의 이해관계가 달라 자신만의 이익을 추구할 때 나타나는 다툼, 충돌", example_f:"다양한 사람들이 살아가는 사회에서는",example_b:"과 다툼이 발생할 수밖에 없다.",hint:"ㄱㄷ",hint_b:"과/와 다툼이 발생할 수밖에 없다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "계층 갈등", word_q: "계층 갈등", mean: "빈부 격차, 소득 격차 등 서로 다른 사회적 지위를 가진 집단 간의 갈등", example_f:"부의 재분배를 둘러싸고",example_b:"이 발생한다.",hint:"ㄱㅊ ㄱㄷ",hint_b:"이/가 발생한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "세대 갈등", word_q: "세대 갈등", mean: "세대 간 가치관, 생활 방식, 이해관계가 달라 발생하는 갈등", example_f:"청년 세대와 중장년 세대 간의",example_b:"이 발생하고 있다.",hint:"ㅅㄷ ㄱㄷ",hint_b:"이/가 발생하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "지역 갈등", word_q: "지역 갈등", mean: "지역 간 서로 다른 이해관계를 추구하는 과정에서 발생하는 갈등", example_f:"지역 균형 발전을 둘러싸고 수도권과 지방 사이에서",example_b:"이 발생한다.",hint:"ㅈㅇ ㄱㄷ",hint_b:"이/가 발생한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "성별 갈등", word_q: "성별 갈등", mean: "서로 다른 성별 간 발생하는 갈등", example_f:"남성과 여성 간의",example_b:"이 점점 심해지고 있다.",hint:"ㅅㅂ ㄱㄷ",hint_b:"이/가 점점 심해지고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "편견", word_q: "편견", mean: "공정하지 못하고 한쪽으로 치우친 생각", example_f:"장애인이라고 해서",example_b:"을 가지면 안 된다.",hint:"ㅍㄱ",hint_b:"을/를 가지면 안 된다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "차별", word_q: "차별", mean: "자신과 다르다고 해서 편견을 갖고 부당하게 대우하는 것", example_f:"",example_b:"은 다른 사람의 인권을 침해한다.",hint:"ㅊㅂ",hint_b:"은/는 다른 사람의 인권을 침해한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "차이", word_q: "차이", mean: "서로 다른 것", example_f:"차별은",example_b:"를 근거로 부당하게 대우하는 것이다.",hint:"ㅊㅇ",hint_b:"을/를 근거로 부당하게 대우하는 것이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "인종 차별", word_q: "인종 차별", mean: "인종에 대한 편견으로 특정한 인종에 대하여 차별하는 것", example_f:"1800년대의 노예 제도는 대표적인",example_b:"의 사례이다.",hint:"ㅇㅈ ㅊㅂ",hint_b:"의 사례이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "성차별", word_q: "성차별", mean: "성이 다르다는 이유만으로 남녀를 차별하는 것", example_f:"여자는 축구를 하면 안 된다는 것은",example_b:"이다.",hint:"ㅅㅊㅂ",hint_b:"이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "장애인 차별", word_q: "장애인 차별", mean: "장애가 있다는 이유만으로 차별하는 것", example_f:"장애를 가졌다는 이유로 채용하지 않는 것은",example_b:"이다.",hint:"ㅈㅇㅇ ㅊㅂ",hint_b:"이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "관용", word_q: "관용", mean: "자기와 다른 점을 받아들이고 인정하는 능동적이고 개방적인 자세", example_f:"차별하지 않기 위해 서로의 차이를 인정하는",example_b:"의 자세를 길러야 한다.",hint:"ㄱㅇ",hint_b:"의 자세를 길러야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "사회적 약자", word_q: "사회적 약자", mean: "사회에서 신체적, 사회적 등의 이유의 소외되어 인간다운 삶을 영위하는데 어려움을 겪는 개인이나 집단", example_f:"우리 사회에서 소외되기 쉬운",example_b:"를 보호해야 한다.",hint:"ㅅㅎㅈ ㅇㅈ",hint_b:"을/를 보호해야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "실질적 평등", word_q: "실질적 평등", mean: "개인의 차이와 능력의 차이에 따른 사회적 격차를 인정하고, 이에 따라 평등이 실질적으로 이루어질 수 있도록 하는 것", example_f:"사회적 약자를 보호하고",example_b:"을 실현할 수 있는 방안을 마련하고자 노력해야 한다.",hint:"ㅅㅈㅈ ㅍㄷ",hint_b:"을/를 실현할 수 있는 방안을 마련하고자 노력해야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 8단원
      list: [
        { word: "문화", word_q: "문화", mean: "한 사회 구성원이 공유하는 생활양식", example_f:"개인적인 버릇이나 습관은",example_b:"가 아니다.",hint:"ㅁㅎ",hint_b:"이/가 아니다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "생활양식", word_q: "생활양식", mean: "사회나 집단에 속한 사람들이 공통으로 갖는 생활에 대한 인식이나 생활하는 방식", example_f:"문화란 인간이 주어진 환경에 적응하면서 형성해 온",example_b:"이다.",hint:"ㅅㅎㅇㅅ",hint_b:"이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "의식주", word_q: "의식주", mean: "옷과 음식과 집을 통틀어 이르는 말", example_f:"",example_b:"와 같이 한 사회 구성원이 공유하는 생활양식을 통틀어 문화라고 한다.",hint:"ㅇㅅㅈ",hint_b:"과/와 같이 한 사회 구성원이 공유하는 생활양식을 통틀어 문화라고 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "문화의 보편성", word_q: "문화의 보편성", mean: "대부분의 사회에서 공통적인 문화 현상이 나타나는 것", example_f:"어느 사회나 부부가 될 사람들은 결혼을 하는 문화 현상이 나타나는 것은",example_b:"이다.",hint:"ㅁㅎㅇ ㅂㅍㅅ",hint_b:"이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "문화의 특수성", word_q: "문화의 특수성", mean: "각 사회가 처한 환경이나 역사에 따라 문화의 세부적인 모습이 다르게 나타나는 것", example_f:"나라마다 결혼식의 모습이 다른 것은",example_b:"이다.",hint:"ㅁㅎㅇ ㅌㅅㅅ",hint_b:"이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "문화의 다양성", word_q: "문화의 다양성", mean: "문화가 다양하게 나타나는 것", example_f:"문화의 특수성으로",example_b:"이 나타난다.",hint:"ㅁㅎㅇ ㄷㅇㅅ",hint_b:"이/가 나타난다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "미디어", word_q: "미디어", mean: "정보 등을 전달하고 공유하는 수단", example_f:"우리는 일상생활에서",example_b:"를 통해 여러 문화와 정보를 접한다.",hint:"ㅁㄷㅇ",hint_b:"을/를 통해 여러 문화와 정보를 접한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "동영상 공유 플랫폼", word_q: "동영상 공유 플랫폼", mean: "동영상을 업로드하고 공유하는 플랫폼", example_f:"",example_b:"에서 다양한 영상을 쉽게 검색하고 시청할 수 있다.",hint:"ㄷㅇㅅ ㄱㅇ ㅍㄹㅍ",hint_b:"에서 다양한 영상을 쉽게 검색하고 시청할 수 있다.", imageBool: true  ,lineBreak:3,abbreviastion:false},
        { word: "사회 관계망 서비스(SNS)", word_q: "사회 관계망 서비스(SNS)", mean: "온라인상에서 인맥을 형성하고 관계를 확장하기 위한 목적으로 제공되는 서비스", example_f:"아침에 일어나면",example_b:"를 확인한다.",hint:"ㅅㅎ ㄱㄱㅁ ㅅㅂㅅ(SNS)",hint_b:"를 확인한다.", imageBool: true  ,lineBreak:6,abbreviastion:true},
        { word: "인쇄 매체", word_q: "인쇄 매체", mean: "책이나 신문과 같이 문자로 정보를 전달하는 매체", example_f:"",example_b:"에는 책이나 신문, 잡지 등이 있다.",hint:"ㅇㅅ ㅁㅊ",hint_b:"에는 책이나 신문, 잡지 등이 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "영상 매체", word_q: "영상 매체", mean: "텔레비전 방송과 영화 등 영상으로 정보를 전달하는 매체", example_f:"20세기 이후에는 영상으로 정보를 전달하는",example_b:"가 발달하였다.",hint:"ㅇㅅ ㅁㅊ",hint_b:"이/가 발달하였다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "뉴 미디어", word_q: "뉴 미디어", mean: "정보를 만드는 사람과 소비하는 사람이 쌍방향으로 소통하는 매체", example_f:"최근에는 인터넷의 발달로",example_b:"가 등장하였다.",hint:"ㄴ ㅁㄷㅇ",hint_b:"이/가 등장하였다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "미디어 리터러시", word_q: "미디어 리터러시", mean: "미디어에 담긴 지식과 정보를 분석∙이해하고 평가하며, 이를 적절하게 활용해 창조적으로 재생산하는 능력", example_f:"건강한 미디어 환경을 만들기 위해",example_b:"가 더욱 중요해지고 있다.",hint:"ㅁㄷㅇ ㄹㅌㄹㅅ",hint_b:"이/가 더욱 중요해지고 있다.", imageBool: false ,lineBreak:3,abbreviastion:false },
        { word: "가짜 뉴스", word_q: "가짜 뉴스", mean: "뉴스의 형태를 띠고 있지만 사실이 아닌 거짓 뉴스", example_f:"미디어가 발달하면서 미디어 속",example_b:"를 구별하기 어려워졌다.",hint:"ㄱㅉ ㄴㅅ",hint_b:"을/를 구별하기 어려워졌다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "편향적", word_q: "편향적", mean: "한쪽으로 치우친 경향이 있는 것", example_f:"미디어를 올바르게 활용하려면 미디어가 전달하는 정보가",example_b:"인 시각을 담고 있지 않은지 비판적으로 검토해야 한다.",hint:"ㅍㅎㅈ",hint_b:"인 시각을 담고 있지 않은지 비판적으로 검토해야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "저작권", word_q: "저작권", mean: "저작자가 그 자신이 창작한 저작물에 대해서 갖는 권리", example_f:"",example_b:"을 보호하여 건강한 미디어 환경을 만들기 위해 노력해야 한다.",hint:"ㅈㅈㄱ",hint_b:"을/를 보호하여 건강한 미디어 환경을 만들기 위해 노력해야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "이주민", word_q: "이주민", mean: "다른 지역에서 옮겨 오거나 옮겨 가서 사는 사람", example_f:"최근에는 세계화로",example_b:"이 늘어났다.",hint:"ㅇㅈㅁ",hint_b:"이/가 늘어났다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "다문화 사회", word_q: "다문화 사회", mean: "한 국가나 한 사회 속에 다른 인종, 민족 등 여러 집단이 지닌 문화가 함께 존재하는 사회", example_f:"우리나라도 지역, 종교, 언어 등 배경이 서로 다른 다양한 집단의 문화가 나타나는",example_b:"로 변화하고 있다.",hint:"ㄷㅁㅎ ㅅㅎ",hint_b:"(으)로 변화하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "우열", word_q: "우열", mean: "나음과 못함.", example_f:"어떤 사람들은 문화에",example_b:"이 있다고 생각하고 문화를 평가한다.",hint:"ㅇㅇ",hint_b:"이/가 있다고 생각하고 문화를 평가한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "자문화 중심주의", word_q: "자문화 중심주의", mean: "자기 문화를 우월하게 보고 다른 문화를 열등하게 여기는 문화 이해 태도", example_f:"",example_b:"는 다른 사람에게 자신의 문화를 강요함으로써 다른 문화와 갈등이 발생할 수 있다.",hint:"ㅈㅁㅎ ㅈㅅㅈㅇ",hint_b:"은/는 다른 사람에게 자신의 문화를 강요함으로써 다른 문화와 갈등이 발생할 수 있다.", imageBool: false ,lineBreak:3,abbreviastion:false },
        { word: "문화 사대주의", word_q: "문화 사대주의", mean: "다른 문화를 우월하게 보고 자신의 문화를 열등하게 여기는 태도", example_f:"",example_b:"는 자신의 문화를 지키려는 노력을 소홀히 하기 때문에 문화의 주체성과 정체성을 잃어버리기 쉽다.",hint:"ㅁㅎ ㅅㄷㅈㅇ",hint_b:"은/는 자신의 문화를 지키려는 노력을 소홀히 하기 때문에 문화의 주체성과 정체성을 잃어버리기 쉽다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "문화 상대주의", word_q: "문화 상대주의", mean: "문화의 우열을 평가하지 않고, 그 사회의 입장에서 문화를 이해하려는 태도", example_f:"우리는",example_b:"의 관점에서 세계의 다양한 종교와 문화를 존중해야 한다.",hint:"ㅁㅎ ㅅㄷㅈㅇ",hint_b:"의 관점에서 세계의 다양한 종교와 문화를 존중해야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 9단원
      list: [
        { word: "이해관계", word_q: "이해관계", mean: "서로 이익과 손해가 걸려 있는 관계", example_f:"",example_b:"에 따라 정책이 결정된다.",hint:"ㅇㅎㄱㄱ",hint_b:"에 따라 정책이 결정된다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "정치", word_q: "정치", mean: "사회 구성원들의 다양한 의견과 이해관계를 조정하여 의사를 결정하고 공동체의 문제를 해결하는 과정", example_f:"국가의 일을 결정하는 것 뿐만 아니라 주민 회의나 학급 회의도 모두",example_b:"이다.",hint:"ㅈㅊ",hint_b:"이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "민주주의", word_q: "민주주의", mean: "시민이 권력을 가지고 스스로 그 권리를 행사하는 정치 형태이자 일상 속 생활양식", example_f:"현대 사회에서 공동체의 의사 결정 과정이 정당하게 이루어졌다고 평가받기 위한 기준으로",example_b:"는 필수적이다.",hint:"ㅁㅈㅈㅇ",hint_b:"은/는 필수적이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "공동체 의식", word_q: "공동체 의식", mean: "한 사회에 함께하고 있다는 생각과 감정이며 공동의 문제 해결에 함께 참여하려는 의식", example_f:"대화와 토론을 통해",example_b:"을 기를 수 있다.",hint:"ㄱㄷㅊ ㅇㅅ",hint_b:"을/를 기를 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "민회", word_q: "민회", mean: "고대 그리스 도시 국가에서 모든 시민이 참여했던 최고 의결 기관", example_f:"아테네 시민들은",example_b:"에서 국가의 주요 정책들을 직접 토의하고 결정하였다.",hint:"ㅁㅎ",hint_b:"에서 국가의 주요 정책들을 직접 토의하고 결정하였다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "차티스트 운동", word_q: "차티스트 운동", mean: "영국의 노동자들이 주체가 되어 선거권을 요구한 민중 운동", example_f:"",example_b:"의 주체는 근대 시민 혁명 이후에도 여전히 정치에 참여할 수 없었던 노동자들이었다.",hint:"ㅊㅌㅅㅌ ㅇㄷ",hint_b:"의 주체는 근대 시민 혁명 이후에도 여전히 정치에 참여할 수 없었던 노동자들이었다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "보통 선거 제도", word_q: "보통 선거 제도", mean: "일정 나이에 도달한 국민이면 누구나 선거에 참여할 수 있는 제도", example_f:"20세기 중반에",example_b:"가 확립되면서 모든 사회 구성원이 정치에 참여할 수 있게 되었다.",hint:"ㅂㅌ ㅅㄱ ㅈㄷ",hint_b:"이/가 확립되면서 모든 사회 구성원이 정치에 참여할 수 있게 되었다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "간접 민주주의", word_q: "간접 민주주의", mean: "시민들이 선출한 대표가 국가 정책을 결정하는 민주주의 형태", example_f:"대부분의 현대 민주 국가에서는",example_b:"를 실시하고 있다.",hint:"ㄱㅈ ㅁㅈㅈㅇ",hint_b:"을/를 실시하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "현대 민주주의", word_q: "현대 민주주의", mean: "현대 사회에 나타난 민주주의", example_f:"",example_b:"는 간접 민주주의 형태로 이루어지고 있다.",hint:"ㅎㄷ ㅁㅈㅈㅇ",hint_b:"은/는 간접 민주주의 형태로 이루어지고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "국민 주권의 원리", word_q: "국민 주권의 원리", mean: "국가의 의사를 결정하는 최고 권력이 국민에게 있다는 민주주의의 기본 원리", example_f:"",example_b:"에 따라 국가가 권력을 행사하기 위해서는 국민의 뜻에 따라야 한다.",hint:"ㄱㅁ ㅈㄱㅇ ㅇㄹ",hint_b:"에 따라 국가가 권력을 행사하기 위해서는 국민의 뜻에 따라야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "국민 자치의 원리", word_q: "국민 자치의 원리", mean: "주권자인 국민이 스스로 국가를 다스려야 한다는 민주주의의 기본 원리", example_f:"",example_b:"에 따라 우리나라에서는 국민 투표, 주민 투표 등을 실시하고 있다.",hint:"ㄱㅁ ㅈㅊㅇ ㅇㄹ",hint_b:"에 따라 우리나라에서는 국민 투표, 주민 투표 등을 실시하고 있다.", imageBool: true ,lineBreak:0,abbreviastion:false },
        { word: "입헌주의의 원리", word_q: "입헌주의의 원리", mean: "국가 최고법인 헌법에 따라 권력을 행사해야 한다는 민주주의의 기본 원리", example_f:"",example_b:"를 통해 국가의 권력 남용을 막을 수 있다.",hint:"ㅇㅎㅈㅇㅇ ㅇㄹ",hint_b:"을/를 통해 국가의 권력 남용을 막을 수 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "권력 분립의 원리", word_q: "권력 분립의 원리", mean: "국가 권력을 서로 다른 독립된 기관이 나누어 맡아 견제와 균형을 이루어야 한다는 민주주의의 기본 원리", example_f:"",example_b:"에 따라 우리나라는 입법부, 사법부, 행정부를 두고 있다.",hint:"ㄱㄹ ㅂㄹㅇ ㅇㄹ",hint_b:"에 따라 우리나라는 입법부, 사법부, 행정부를 두고 있다.", imageBool: false  ,lineBreak:0,abbreviastion:false},
        { word: "자유", word_q: "자유", mean: "외부의 간섭과 통제를 받지 않고 자신의 뜻대로 생각하고 결정하는 것", example_f:"인간의 존엄성을 실현하기 위해",example_b:"는 반드시 보장되어야 한다.",hint:"ㅈㅇ",hint_b:"는 반드시 보장되어야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "평등", word_q: "평등", mean: "인간의 가치는 모두 동등하다는 것", example_f:"성별, 종교, 지역에 따라 사람을 차별하지 않고 모든 사람을 균등하게 대우할 때",example_b:"이 실현된다.",hint:"ㅍㄷ",hint_b:"이/가 실현된다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "대의제", word_q: "대의제", mean: "시민들이 선출한 대표가 국가 정책을 결정하는 제도", example_f:"현대 민주 국가에서",example_b:"를 실현하는 이유는 영토와 인구 규모의 확대, 사람들의 요구가 다양해지면서 전문성을 갖춘 사람이 필요해졌기 때문이다.",hint:"ㄷㅇㅈ",hint_b:"을/를 실현하는 이유는 영토와 인구 규모의 확대, 사람들의 요구가 다양해지면서 전문성을 갖춘 사람이 필요해졌기 때문이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "국민 투표", word_q: "국민 투표", mean: "국정의 중요한 사안을 국민이 투표로 결정하는 것", example_f:"우리나라 헌법상 헌법 개정안은 반드시",example_b:"에 붙여서 확정하여야 한다.",hint:"ㄱㅁ ㅌㅍ",hint_b:"에 붙여서 확정하여야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "국민 발안", word_q: "국민 발안", mean: "헌법 개정안이나 법률안을 국민이 제출하는 것", example_f:"",example_b:" 제도는 직접 민주주의의 한 형태로, 우리나라에서는 현재 이 제도를 시행하고 있지 않다.",hint:"ㄱㅁ ㅂㅇ",hint_b:"제도는 직접 민주주의의 한 형태로, 우리나라에서는 현재 이 제도를 시행하고 있지 않다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "국민 소환", word_q: "국민 소환", mean: "대표의 임기가 끝나기 전에 국민의 뜻에 따라 대표를 파면하는 것", example_f:"",example_b:" 제도의 장점은 대표에 대한 제재가 가능하다는 것이다.",hint:"ㄱㅁ ㅅㅎ",hint_b:"제도의 장점은 대표에 대한 제재가 가능하다는 것이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "전자 민주주의", word_q: "전자 민주주의", mean: "정보 매체를 활용하여 정치에 참여하는 민주주의의 한 형태", example_f:"정보 매체를 통한",example_b:"가 실현됨으로써 시민은 자신의 의사를 적극적으로 표현할 수 있게 되었다.",hint:"ㅈㅈ ㅁㅈㅈㅇ",hint_b:"이/가 실현됨으로써 시민은 자신의 의사를 적극적으로 표현할 수 있게 되었다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "공론화", word_q: "공론화", mean: "특정 문제를 많은 사람들이 의논하는 대상이 되도록 하는 것", example_f:"국가 차원에서 사회문제를",example_b:"하기 위해 TV 생중계를 하기도 한다.",hint:"ㄱㄹㅎ",hint_b:"하기 위해 TV 생중계를 하기도 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 10단원
      list: [
        { word: "선거", word_q: "선거", mean: "대표를 선출하는 제도", example_f:"",example_b:"는 민주주의의 꽃으로, 민주주의를 실현하기 위한 가장 중요하고 기본적인 제도이다.",hint:"ㅅㄱ",hint_b:"은/는 민주주의의 꽃으로, 민주주의를 실현하기 위한 가장 중요하고 기본적인 제도이다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "보통 선거", word_q: "보통 선거", mean: "일정 나이 이상이 되면 모든 국민에게 선거권을 부여해야 한다는 원칙", example_f:"일정 나이가 되었는데도 성별, 재산 등에 의해 선거에 참여할 권리를 제한할 수 없게 한 것은",example_b:"에 어긋난다.",hint:"ㅂㅌ ㅅㄱ",hint_b:"에 어긋난다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "직접 선거", word_q: "직접 선거", mean: "대리인을 거치지 않고 유권자가 직접 투표하는 원칙", example_f:"",example_b:"가 지켜지지 않는다면 유권자가 지지하지 않는 후보자가 득표할 수도 있다.",hint:"ㅈㅈ ㅅㄱ",hint_b:"이/가 지켜지지 않는다면 유권자가 지지하지 않는 후보자가 득표할 수도 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "평등 선거", word_q: "평등 선거", mean: "유권자가 행사하는 표의 가치가 모두 동등해야 한다는 원칙", example_f:"",example_b:"가 지켜지지 않는다면 표의 가치에 차등이 생겨 민주적인 선거가 될 수 없다.",hint:"ㅍㄷ ㅅㄱ",hint_b:"이/가 지켜지지 않는다면 표의 가치에 차등이 생겨 민주적인 선거가 될 수 없다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "비밀 선거", word_q: "비밀 선거", mean: "누구에게 투표했는지 다른 사람은 알 수 없게 비밀이 보장되어야 한다는 원칙", example_f:"",example_b:"를 지키기 위해 투표용지에 투표한 사람의 이름을 적지 않는다.",hint:"ㅂㅁ ㅅㄱ",hint_b:"을/를 지키기 위해 투표용지에 투표한 사람의 이름을 적지 않는다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "비례 대표", word_q: "비례 대표", mean: "정당의 득표 수에 따라 선출하는 국회 의원", example_f:"",example_b:"로 어떤 후보를 세울지 정당들은 여러 날에 걸쳐 면접을 실시한다.",hint:"ㅂㄹ ㄷㅍ",hint_b:"(으)로 어떤 후보를 세울지 정당들은 여러 날에 걸쳐 면접을 실시한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "유권자", word_q: "유권자", mean: "선거할 권리가 있는 사람", example_f:"",example_b:"는 자신의 표를 행사하여 정치과정에 참여할 수 있다.",hint:"ㅇㄱㅈ",hint_b:"은/는 자신의 표를 행사하여 정치과정에 참여할 수 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "정당", word_q: "정당", mean: "정치적 견해가 같은 사람들이 모여 정치권력 획득을 위해 모인 단체", example_f:"현대 민주 국가의",example_b:"은 국민들로부터 높은 지지율을 끌어내야 정치권력을 획득할 수 있다.",hint:"ㅈㄷ",hint_b:"은/는 국민들로부터 높은 지지율을 끌어내야 정치권력을 획득할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "정부", word_q: "정부", mean: "삼권 분립의 원리에 따라 행정을 맡는 기관", example_f:"",example_b:"는 어린이들의 안전을 위해 학교 앞 제한 속도를 올릴 것이라고 발표했다.",hint:"ㅈㅂ",hint_b:"은/는 어린이들의 안전을 위해 학교 앞 제한 속도를 올릴 것이라고 발표했다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "전당 대회", word_q: "전당 대회", mean: "당의 중요한 사안을 결정하기 위해 모이는 회의", example_f:"당은",example_b:"를 통해 당 내부의 결속력을 다진다.",hint:"ㅈㄷ ㄷㅎ",hint_b:"을/를 통해 당 내부의 결속력을 다진다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "이익 집단", word_q: "이익 집단", mean: "이해관계가 같은 사람들이 모여 자신들의 이익을 실현하기 위해 만든 단체", example_f:"현대 사회가 다원화되면서",example_b:"의 종류도 더 다양해지고 있다.",hint:"ㅇㅇ ㅈㄷ",hint_b:"의 종류도 더 다양해지고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "시민 단체", word_q: "시민 단체", mean: "사회의 보편적인 이익을 추구하기 위해 시민들이 자발적으로 만든 단체", example_f:"환경에 대한 사람들의 관심이 높아지면서 환경 관련",example_b:"의 수가 증가하였다.",hint:"ㅅㅁ ㄷㅊ",hint_b:"의 수가 증가하였다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "언론", word_q: "언론", mean: "매체를 통해 어떤 사실을 알리거나 여론을 형성하는 활동", example_f:"",example_b:"의 보도는 여론을 형성하여 새로운 정책을 만들거나 기존의 정책이 수정되는데 기여한다.",hint:"ㅇㄹ",hint_b:"의 보도는 여론을 형성하여 새로운 정책을 만들거나 기존의 정책이수정되는데 기여한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "정책", word_q: "정책", mean: "공익을 실현하기 위해 정부나 공공 기관에서 행하는 방침", example_f:"",example_b:"은 일상생활에 큰 영향을 미치기 때문에 민주적인 정치과정을 통해 결정되어야 한다.",hint:"ㅈㅊ",hint_b:"은/는 일상생활에 큰 영향을 미치기 때문에 민주적인 정치과정을 통해 결정되어야 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "정치과정", word_q: "정치과정", mean: "시민들의 다양한 요구와 이익을 집약하여 정책으로 만들고 집행한 후 피드백을 통해 환류되는 과정", example_f:"민주주의 국가에서 사람들은",example_b:"을 통해 자신의 요구와 이익을 표출할 수 있다.",hint:"ㅈㅊㄱㅈ",hint_b:"을/를 통해 자신의 요구와 이익을 표출할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "지방 자치", word_q: "지방 자치", mean: "주민들과 주민들이 뽑은 대표가 지역의 일을 자율적으로 처리하는 과정", example_f:"",example_b:"는 주민들의 책임감을 높이고, 지역의 상황에 맞는 효율적인 정책이 집행될 수 있도록 한다.",hint:"ㅈㅂ ㅈㅊ",hint_b:"은/는 주민들의 책임감을 높이고, 지역의 상황에 맞는 효율적인 정책이 집행될 수 있도록 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "풀뿌리 민주주의", word_q: "풀뿌리 민주주의", mean: "위로부터의 민주주의가 아닌, 민중으로부터 지지를 얻어 이루어지는 민주주의", example_f:"",example_b:"의 실현을 위해서는 주민들이 자신의 의사를 표현할 수 있는 기회를 풍부하게 마련하고 그들의 의견을 경청하는 체계가 구축되어야 한다.",hint:"ㅍㅃㄹ ㅁㅈㅈㅇ",hint_b:"의 실현을 위해서는 주민들이 자신의 의사를 표현할 수 있는 기회를 풍부하게 마련하고 그들의 의견을 경청하는 체계가 구축되어야 한다.", imageBool: false ,lineBreak:3,abbreviastion:false },
        { word: "집약", word_q: "집약", mean: "한 데 모아서 요약하는 것", example_f:"회의의 목적은 사람들의 다양한 의견을 듣고",example_b:"하고자 하는 데에 있다.",hint:"ㅈㅇ",hint_b:"하고자 하는 데에 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "지방 선거", word_q: "지방 선거", mean: "지역의 일을 맡을 지방 의회 의원과 지방 자치 단체장을 주민이 뽑는 선거", example_f:"",example_b:"의 투표율을 높이기 위해 각 지자체는 선거 홍보에 힘을 쓰고 있다.",hint:"ㅈㅂ ㅅㄱ",hint_b:"의 투표율을 높이기 위해 각 지자체는 선거 홍보에 힘을 쓰고 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "주민 투표", word_q: "주민 투표", mean: "지역의 중요한 문제를 주민의 투표로 직접 결정하는 것", example_f:"갑지역과 을지역의 통합을 묻는",example_b:"를 실시하기 위해 지역 대표간 협의가 이루어졌다.",hint:"ㅈㅁ ㅌㅍ",hint_b:"을/를 실시하기 위해 지역 대표간 협의가 이루어졌다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "주민 청원", word_q: "주민 청원", mean: "주민이 요구 사항을 직접 지방 자치 단체에 문서로 제출하는 것", example_f:"한 교육청에서",example_b:"을 통해 학교 급식 제도를 개선하여 많은 주민들의 호응을 얻고 있다.",hint:"ㅈㅁ ㅊㅇ",hint_b:"을/를 통해 학교 급식 제도를 개선하여 많은 주민들의 호응을 얻고 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "공청회", word_q: "공청회", mean: "중요 정책의 해결이나 결정을 위해 관련된 사람들의 의견을 듣는 것", example_f:"정부는 지방 자치법 개정에 대한 사람들의 의견을 듣기 위해",example_b:"를 열 계획이라고 밝혔다.",hint:"ㄱㅊㅎ",hint_b:"을/를 열 계획이라고 밝혔다.", imageBool: false ,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 11단원
      list: [
        { word: "법", word_q: "법", mean: "사회 구성원들의 합의를 반영하여 국가 및 공공 기관이 만든 가장 대표적인 사회 규범", example_f:"우리 사회에는 다양한",example_b:"이 존재하며 우리의 일상생활과 밀접하게 연결되어 있다.",hint:"ㅂ",hint_b:"이/가 존재하며 우리의 일상생활과 밀접하게 연결되어 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "사회 규범", word_q: "사회 규범", mean: "사회의 질서를 유지하고 사회생활을 바람직하게 이끄는 여러 규범", example_f:"사람들 간 갈등을 해결하고 질서를 유지하기 위해 사회에는 다양한",example_b:"이 존재한다.",hint:"ㅅㅎ ㄱㅂ",hint_b:"이/가 존재한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "관습", word_q: "관습", mean: "어떤 사회에서 오랫동안 지켜져 내려와 그 사회 구성원들이 널리 인정하는 질서나 풍습", example_f:"우리 사회는 사람이 죽으면 장례식을 치르는",example_b:"이 있다.",hint:"ㄱㅅ",hint_b:"이/가 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "종교 규범", word_q: "종교 규범", mean: "특정한 종교를 믿는 사람들 사이에서 지키도록 정해 놓은 교리나 규율", example_f:"불교를 믿는 사람들은 불경이라는",example_b:"을 지키며 살아간다.",hint:"ㅈㄱ ㄱㅂ",hint_b:"을/를 지키며 살아간다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "도덕", word_q: "도덕", mean: "사회 구성원들이 양심 등에 비추어 옳다고 여기는 행동 기준", example_f:"",example_b:"에 어긋나는 행동을 하면 양심의 가책을 느끼거나 다른 사람에게 비난받는다.",hint:"ㄷㄷ",hint_b:"에 어긋나는 행동을 하면 양심의 가책을 느끼거나 다른 사람에게 비난받는다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "제재", word_q: "제재", mean: "법이나 규정, 관습 따위를 어겼을 때 이를 제한하거나 금지하는 것", example_f:"지위에 따른 역할을 제대로 수행하지 못하면 비난이나",example_b:"를 받게 된다.",hint:"ㅈㅈ",hint_b:"을/를 받게 된다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "정의", word_q: "정의", mean: "옳고 그름을 판단하여 모든 사람에게 각자가 받아야 할 정당한 몫을 주는 것", example_f:"모든 법의 궁극적인 목적은",example_b:"를 실현하는 것이다.",hint:"ㅈㅇ",hint_b:"을/를 실현하는 것이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "준법", word_q: "준법", mean: "법률이나 규칙을 좇아 지키는 것", example_f:"법을 통해 정의를 실현하려면 우리 모두가",example_b:" 의식을 갖추는 일도 중요하다.",hint:"ㅈㅂ",hint_b:"의식을 갖추는 일도 중요하다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "헌법", word_q: "헌법", mean: "국민의 기본권을 규정하고, 국가기관을 어떻게 구성하고 운영할 것인지 정해 놓은 법", example_f:"",example_b:"은 국가 운영의 바탕이 되는 가장 기본적인 법이다.",hint:"ㅎㅂ",hint_b:"은/는 국가 운영의 바탕이 되는 가장 기본적인 법이다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "민법", word_q: "민법", mean: "개인 간 권리관계를 다루는 법", example_f:"",example_b:"은 개인이 일상생활에서 마주하는 다양한 분쟁 해결의 기준을 제공한다.",hint:"ㅁㅂ",hint_b:"은/는 개인이 일상생활에서 마주하는 다양한 분쟁 해결의 기준을 제공한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "범죄", word_q: "범죄", mean: "국가가 보호하는 이익과 가치를 침해하는 중대한 반사회적 행위", example_f:"",example_b:"를 저지르면 법 규범에 따라 형벌이 부과된다.",hint:"ㅂㅈ",hint_b:"을/를 저지르면 법 규범에 따라 형벌이 부과된다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "형벌", word_q: "형벌", mean: "국가가 법에 따라 범죄자에게 제재를 가하는 것", example_f:"범죄를 저지른 경우",example_b:"의 범위 안에서만 처벌함으로써 국민의 자유와 권리를 보호한다.",hint:"ㅎㅂ",hint_b:"의 범위 안에서만 처벌함으로써 국민의 자유와 권리를 보호한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "형법", word_q: "형법", mean: "어떤 행위가 범죄이고, 어떤 처벌을 받는지 정해 놓은 법", example_f:"",example_b:"은 범죄와 형벌의 내용을 명확히 하여 공공질서를 유지한다.",hint:"ㅎㅂ",hint_b:"은/는 범죄와 형벌의 내용을 명확히 하여 공공질서를 유지한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "사회법", word_q: "사회법", mean: "사적 생활 영역인 개인 간의 법률관계에 국가가 개입하는 법", example_f:"오늘날 모든 국민의 인간답게 살 권리를 보장하기 위해",example_b:"을 강조하고 있다.",hint:"ㅅㅎㅂ",hint_b:"을/를 강조하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "산업 혁명", word_q: "산업 혁명", mean: "18세기 후반 기계 발명 등의 기술 혁신으로 생산력이 크게 증가하면서 나타난 사회·경제적 변화", example_f:"18세기 후반",example_b:"은 자본주의의 발달과 경제 성장의 계기가 되었지만, 각종 사회문제를 낳기도 했다.",hint:"ㅅㅇ ㅎㅁ",hint_b:"은/는 자본주의의 발달과 경제 성장의 계기가 되었지만, 각종 사회문제를 낳기도 했다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "노동법", word_q: "노동법", mean: "노동자의 권리를 보호하기 위해 근로자의 권리와 근로 조건을 규정하고, 노사 간의 이해관계를 조정하기 위한 법", example_f:"",example_b:"의 종류로는 근로 기준법, 노동조합 및 노동관계 조정법 등이 있다.",hint:"ㄴㄷㅂ",hint_b:"의 종류로는 근로 기준법, 노동조합 및 노동관계 조정법 등이 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "경제법", word_q: "경제법", mean: "공정한 경제 질서를 유지하여 기업 간 자유로운 경쟁을 보장하고 소비자의 권익을 보호하기 위한 법", example_f:"",example_b:"의 종류로는 독점 규제 및 공정 거래에 관한 법률, 소비자 기본법 등이 있다.",hint:"ㄱㅈㅂ",hint_b:"의 종류로는 독점 규제 및 공정 거래에 관한 법률, 소비자 기본법 등이 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "사회 보장법", word_q: "사회 보장법", mean: "실업, 빈곤, 질병, 고령 등으로 어려움을 겪고 있는 사람들을 돕고, 모든 국민의 인간다운 생활을 보장하기 위한 법", example_f:"",example_b:"의 종류로는 국민 기초 생활 보장법, 국민 건강 보험법, 국민 연금법 등이 있다.",hint:"ㅅㅎ ㅂㅈㅂ",hint_b:"의 종류로는 국민 기초 생활 보장법, 국민 건강 보험법, 국민 연금법 등이 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "재판", word_q: "재판", mean: "법원이 법을 적용하여 옳고 그름을 밝히는 과정", example_f:"대화나 타협으로 문제를 원만하게 해결하기 어려울 때",example_b:"을 통해 분쟁을 예방하고 해결하여 사회 질서를 유지할 수 있다.",hint:"ㅈㅍ",hint_b:"을/를 통해 분쟁을 예방하고 해결하여 사회 질서를 유지할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "민사 재판", word_q: "민사 재판", mean: "개인 간 권리와 의무에 관한 분쟁을 해결하는 재판", example_f:"",example_b:"에서 재판을 청구한 사람은 원고이다.",hint:"ㅁㅅ ㅈㅍ",hint_b:"에서 재판을 청구한 사람은 원고이다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "형사 재판", word_q: "형사 재판", mean: "범죄가 발생했을 때 범죄 여부를 판단하고 범죄자에게 형벌을 부과하기 위한 재판", example_f:"",example_b:"에서 재판을 청구한 사람은 검사이다.",hint:"ㅎㅅ ㅈㅍ",hint_b:"에서 재판을 청구한 사람은 검사이다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "기소", word_q: "기소", mean: "검사가 형사 사건에 관하여 법원의 심판을 청구하는 행위", example_f:"자전거 도난 사고에 대해 수사해 본 검사는 갑을",example_b:"하였다.",hint:"ㄱㅅ",hint_b:"하였다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "공개 재판주의", word_q: "공개 재판주의", mean: "재판 과정은 재판 당사자뿐만 아니라 일반인에게도 공개되어야 한다는 원칙", example_f:"공정한 재판을 위한 여러 가지 원칙과 제도 중에",example_b:"와 증거 재판주의가 있다.",hint:"ㄱㄱ ㅈㅍㅈㅇ",hint_b:"와 증거 재판주의가 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "증거 재판주의", word_q: "증거 재판주의", mean: "재판은 오직 구체적인 증거를 바탕으로 이루어져야 한다는 원칙", example_f:"공정한 재판을 위한 여러 가지 원칙과 제도 중에 공개 재판주의와",example_b:"가 있다.",hint:"ㅈㄱ ㅈㅍㅈㅇ",hint_b:"이/가 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "심급 제도", word_q: "심급 제도", mean: "소송 당사자가 재판 결과에 승복하지 않을 때 급을 달리하는 법원에서 여러 번 재판을 받을 수 있게 하는 제도", example_f:"우리나라는",example_b:"를 기본적으로 삼심제로 운영하고 있다.",hint:"ㅅㄱ ㅈㄷ",hint_b:"을/를 기본적으로 삼심제로 운영하고 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "항소", word_q: "항소", mean: "1심 법원의 판결에 불복해 2심 재판을 청구하는 것", example_f:"우리나라는 1심 법원의 판결에 불복할 시",example_b:"할 수 있다.",hint:"ㅎㅅ",hint_b:"할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "상고", word_q: "상고", mean: "2심 법원의 판결에 불복해 대법원에 3심 재판을 청구하는 것", example_f:"우리나라는 2심 법원의 판결에 불복할 시",example_b:"할 수 있다.",hint:"ㅅㄱ",hint_b:"할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "국민 참여 재판", word_q: "국민 참여 재판", mean: "국민이 배심원 또는 예비 배심원으로 참여하는 형사 재판", example_f:"",example_b:"은 국민의 사법 참여를 확대하고 재판의 민주적 정당성과 투명성을 높이는 데 기여하고 있다.",hint:"ㄱㅁ ㅊㅇ ㅈㅍ",hint_b:"은/는 국민의 사법 참여를 확대하고 재판의 민주적 정당성과 투명성을 높이는 데 기여하고 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
      ],
    },
    {
      // 사회 1권 12단원
      list: [
        { word: "인권", word_q: "인권", mean: "인간이 태어날 때부터 인간답게 살아갈 권리", example_f:"",example_b:"은 인간이 인간답게 살아가기 위해 누려야 하는 기본적인 권리이다.",hint:"ㅇㄱ",hint_b:"은/는 인간이 인간답게 살아가기 위해 누려야 하는 기본적인 권리이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "인권 감수성", word_q: "인권 감수성", mean: "인권과 관련된 문제에 관해 예민하고 섬세하게 받아들이는 것", example_f:"",example_b:"을 가지고 주변에 차별로 인식하지 못한 차별적인 요소들이 있는지 스스로 살펴 보는 자세가 중요하다.",hint:"ㅇㄱ ㄱㅅㅅ",hint_b:"을/를 가지고 주변에 차별로 인식하지 못한 차별적인 요소들이 있는지 스스로 살펴 보는 자세가 중요하다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "기본권", word_q: "기본권", mean: "인권 중 헌법 조항을 통해 보장하는 권리", example_f:"명문화 되지 않은 인간이 마땅히 가져야 할 권리를 헌법 조항을 통해 보장하는 권리를",example_b:"이라고 한다.",hint:"ㄱㅂㄱ",hint_b:"(이)라고 한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "인간의 존엄과 가치 및 행복 추구권", word_q: "인간의 존엄과 가치 및 행복 추구권", mean: "모든 인간이 인간이라는 이유만으로 존중받으며 행복을 추구할 권리", example_f:"헌법 10조에서는",example_b:"을 명시하고 있으며 이 권리는 모든 기본권의 토대가 된다.",hint:"ㅇㄱㅇ ㅈㅇㄱ ㄱㅊ ㅁ ㅎㅂ ㅊㄱㄱ",hint_b:"을/를 명시하고 있으며 이 권리는 모든 기본권의 토대가 된다.", imageBool: false ,lineBreak:10,abbreviastion:false },
        { word: "평등권", word_q: "평등권", mean: "성별, 종교 등으로 불합리한 차별을 받지 않을 권리", example_f:"우리 헌법은",example_b:"을 보장하기 위해 특수 계급을 인정하고 있지 않다.",hint:"ㅍㄷㄱ",hint_b:"을/를 보장하기 위해 특수 계급을 인정하고 있지 않다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "자유권", word_q: "자유권", mean: "개인의 자신의 자유로운 영역에서 국가 권력에 의한 간섭이나 침해를 받지 않을 권리", example_f:"",example_b:"에는 신체의 자유, 정신적 자유, 사회 경제적 자유 등이 있다.",hint:"ㅈㅇㄱ",hint_b:"에는 신체의 자유, 정신적 자유, 사회 경제적 자유 등이 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "참정권", word_q: "참정권", mean: "국가의 의사 결정에 참여할 수 있는 권리", example_f:"",example_b:"에는 선거권, 공무 담임권 등이 있다.",hint:"ㅊㅈㄱ",hint_b:"에는 선거권, 공무 담임권 등이 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "청구권", word_q: "청구권", mean: "국가에 대해 일정한 행위를 요구할 수 있는 권리", example_f:"",example_b:"에는 청원권, 재판 청구권, 국가 배상 청구권 등이 있다.",hint:"ㅊㄱㄱ",hint_b:"에는 청원권, 재판 청구권, 국가 배상 청구권 등이 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "사회권", word_q: "사회권", mean: "인간다운 생활의 보장을 국가에 요구할 수 있는 권리", example_f:"",example_b:"에는 교육을 받을 권리, 근로의 권리, 사회 보장을 받을 권리 등이 있다.",hint:"ㅅㅎㄱ",hint_b:"에는 교육을 받을 권리, 근로의 권리, 사회 보장을 받을 권리 등이 있다.", imageBool: true  ,lineBreak:0,abbreviastion:false},
        { word: "국민 권익 위원회", word_q: "국민 권익 위원회", mean: "불합리한 행정으로 인한 국민의 권릭 침해를 신속하게 해결하고 부패 행위를 효과적으로 예방하기 위한 목적으로 설립된 국가기관", example_f:"",example_b:"는 국민의 고충 민원을 처리하고 불합리한 제도를 개선하는 기관이다.",hint:"ㄱㅁ ㄱㅇ ㅇㅇㅎ",hint_b:"은/는 국민의 고충 민원을 처리하고 불합리한 제도를 개선하는 기관이다.", imageBool: false ,lineBreak:5,abbreviastion:false },
        { word: "국가인권위원회", word_q: "국가인권위원회", mean: "모든 개인의 기본적 인권을 보호, 향상하고 인간으로서의 존엄과 가치를 실현하기 위한 목적으로 설립된 국가기관", example_f:"",example_b:"는 인권 침해나 차별 행위를 조사하여 구제하는 기관이다.",hint:"ㄱㄱㅇㄱㅇㅇㅎ",hint_b:"은/는 인권 침해나 차별 행위를 조사하여 구제하는 기관이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "사용자", word_q: "사용자", mean: "근로자를 채용하거나 해고하고, 근로에 대해 지휘할 책임을 지는 사람", example_f:"갑은 회사에 취직하게 되어",example_b:"인 을에게 근로 계약서 작성을 요구하였다.",hint:"ㅅㅇㅈ",hint_b:"인 을에게 근로 계약서 작성을 요구하였다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "근로의 권리", word_q: "근로의 권리", mean: "일할 의사와 능력을 갖춘 사람이 일할 기회와 인간다운 생활의 보장을 요구할 권리", example_f:"우리나라 헌법은 모든 국민이",example_b:"를 가진다고 명시하고 있으며 이에 따라 일할 의사와 능력을 갖춘 사람은 일할 기회를 국가에 요구할 수 있다.",hint:"ㄱㄹㅇ ㄱㄹ",hint_b:"을/를 가진다고 명시하고 있으며 이에 따라 일할 의사와 능력을 갖춘 사람은 일할 기회를 국가에 요구할 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "근로자", word_q: "근로자", mean: "직업의 종류와 관계 없이 사용자에게 노동을 제공하고 임금을 받는 사람", example_f:"노동의 형태가 육체적이든 정신적이든 임금을 목적으로 노동을 제공하는 자는",example_b:"이다.",hint:"ㄱㄹㅈ",hint_b:"이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "단결권", word_q: "단결권", mean: "근로 조건의 향상을 위하여 노동조합과 같은 단체를 만들 수 있는 근로자의 권리", example_f:"대학교수들이 노동조합을 설립할 수 있는",example_b:"을 인정하지 않는 교원노조법은 헌법에 어긋난다고 헌법재판소는 결정했다.",hint:"ㄷㄱㄱ",hint_b:"을/를 인정하지 않는 교원 노조법은 헌법에 어긋난다고 헌법재판소는 결정했다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "단체 교섭권", word_q: "단체 교섭권", mean: "노동조합을 통해 사용자와 근로 조건에 대하여 협상할 수 있는 근로자의 권리", example_f:"A회사 노동조합은",example_b:"을 통해 임금 인상율을 회사와 협상할 것이라고 밝혔다.",hint:"ㄷㅊ ㄱㅅㄱ",hint_b:"을/를 통해 임금 인상율을 회사와 협상할 것이라고 밝혔다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "단체 행동권", word_q: "단체 행동권", mean: "단체 교섭이 원만하게 이루어지지 않았을 때 쟁의 행위를 할 수 있는 근로자의 권리", example_f:"",example_b:"은 헌법 제33조에 보장되어 있으나 공무원, 교원 등 특정 산업에 종사하는 사람들에게는 제한되어 있다.",hint:"ㄷㅊ ㅎㄷㄱ",hint_b:"은/는 헌법 제33조에 보장되어 있으나 공무원, 교원 등 특정 산업에 종사하는 사람들에게는 제한되어 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "노동조합", word_q: "노동조합", mean: "근로 조건의 개선과 근로자들의 지위 향상 등을 목적으로 근로자들이 조직한 단체", example_f:"",example_b:" 설립은 근로자들의 권리이므로, 사측이 이를 막거나 방해하면 처벌받을 수 있다.",hint:"ㄴㄷㅈㅎ",hint_b:"설립은 근로자들의 권리이므로, 사측이 이를 막거나 방해하면 처벌받을 수 있다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "쟁의", word_q: "쟁의", mean: "파업 등 근로자와 사용자 사이에 일어나는 분쟁", example_f:"",example_b:" 행위는 근로자, 사용자 어느 쪽이든 자신의 주장을 관철할 목적으로 할 수 있으며, 근로자의 대표적인 쟁의 행위는 파업, 사용자의 대표적인 쟁의 행위는 직장 폐쇄이다.",hint:"ㅈㅇ",hint_b:"행위는 근로자, 사용자 어느 쪽이든 자신의 주장을 관철할 목적으로 할 수 있으며, 근로자의 대표적인 쟁의 행위는 파업, 사용자의 대표적인 쟁의 행위는 직장 폐쇄이다.", imageBool: false ,lineBreak:0,abbreviastion:false },
        { word: "부당 노동 행위", word_q: "부당 노동 행위", mean: "헌법으로 보장된 노동 3권을 침해 또는 방해하는 행위", example_f:"사용자가 자신의 우월한 지위를 이용하여",example_b:"를 할 경우 관련 법을 통해 근로자를 구제하고 사용자를 처벌한다.",hint:"ㅂㄷ ㄴㄷ ㅎㅇ",hint_b:"을/를 할 경우 관련 법을 통해 근로자를 구제하고 사용자를 처벌한다.", imageBool: false ,lineBreak:0,abbreviastion:false },
      ],
    },
  
  ],


  // quiz: [
  //   {
  //     // 1단원 
  //     list: [
  //      word: "지도word_q: mean: "위에서 내려다본 땅의 실제 모습을 일정한 약속에 따라 줄여서 나타낸 것", imageBool: true },
  //      word: "항공 사진word_q: "항공mean: "비행 중인 항공기에서 땅의 모습을 찍은 사진", imageBool: true },
  //      word: "방위word_q: mean: "방향의 위치", imageBool: false },
  //     ],
  //   },
  //   {
  //     // 2단원 
  //     list: [
  //      word: "문화유산word_q: "문mean: "옛날 사람들의 생활 모습을 알려 주는 것 중 후손들에게 물려줄 만한 가치가 있는 것", imageBool: true },
  //      word: "유형 문화유산word_q: "유형 문mean: "그림이나 책, 건물처럼 형태가 있는 문화유산", imageBool: true },
  //      word: "무형 문화유산word_q: "무형 문mean: "음악이나 춤, 연극, 기술과 같이 형태가 없는 문화유산", imageBool: true },
  //      word: "목판word_q: mean: "책을 인쇄하려고 나무에 글씨를 새긴 것", imageBool: false },
  //     ],
  //   },
  //   {
  //     // 3단원 
  //     list: [
  //      word: "경제활동word_q: "경mean: "사람들이 생활하는 데 필요한 여러 가지 물건을 만들고 사용하는 것과 관련된 활동", imageBool: true },
  //      word: "자원word_q: mean: "생활에 필요한 것을 만드는 데 사용되는 모든 것", imageBool: false },
  //      word: "한정word_q: mean: "수량이나 범위가 정해져 있음.", imageBool: false },
  //     ],
  //   },
  // ],
};
